services/ui-src/src/verbiage/pages/home.ts

Small bug fix to set the landing page "Work Plan" card to route to /wp

Landing Page Work Plan Re-route - Bug fix

---

services/ui-src/src/components/accordions/TemplateCardAccordion.test.tsx
services/ui-src/src/components/app/AppRoutes.test.tsx
services/ui-src/src/components/app/AppRoutes.tsx
services/ui-src/src/components/cards/TemplateCard.tsx
services/ui-src/src/components/pages/Home/HomePage.test.tsx
services/ui-src/src/components/pages/Home/HomePage.tsx
services/ui-src/src/components/pages/ReviewSubmit/ReviewSubmitPage.tsx
services/ui-src/src/types/reports.ts
services/ui-src/src/verbiage/pages/home.ts

Wrapping each `TemplateCard` buttons behind a LaunchDarkly feature flag (WP and SAR) for deployments into higher environments.
N/A
---
You should see the `Enter WP report` buttons just fine for now, but once we're in higher environments those buttons won't show ❇️ 
N/A
---
---

Feature Flags for WP and SAR Reports

---

services/app-api/handlers/reports/fetch.test.ts
services/app-api/handlers/reports/fetch.ts
services/app-api/handlers/reports/update.test.ts
services/app-api/handlers/reports/update.ts
services/app-api/serverless.yml
services/app-api/utils/testing/mocks/mockDynamo.ts
services/app-api/utils/testing/mocks/mockReport.ts
services/app-api/utils/testing/setupJest.ts
services/app-api/utils/types/reports.ts
services/ui-src/src/utils/api/requestMethods/report.test.ts
services/ui-src/src/utils/api/requestMethods/report.ts
services/ui-src/src/utils/testing/mockLaunchDarkly.tsx

https://github.com/Enterprise-CMCS/macpro-mdct-mfp/assets/19439679/7543b160-bf5a-46b4-8224-b5e114651c00
MDCT-2723
---
You can create a test bed to see this in action by updating your standardReportPage file to the following code, and then navigating to `/standard` once you run `./dev local`. You'll need to click **create report** to be able to get an idea for a report that you want to fetch, and then plug that in to the parameters passed in the fetch function. 
```
// components
import { Box, Button } from "@chakra-ui/react";
import { Form, ReportPageFooter, ReportPageIntro } from "components";
// types
import {
AnyObject,
ReportKeys,
ReportStatus,
StandardReportPageShape,
} from "types";
// utils
import {
getReport,
getReportsByState,
postReport,
} from "utils/api/requestMethods/report"; …
```

API Handler - Fetch/Update Report

---

services/ui-src/src/components/app/App.tsx
services/ui-src/src/components/reports/ReportPageFooter.test.tsx
services/ui-src/src/components/reports/ReportPageFooter.tsx
services/ui-src/src/components/reports/StandardReportPage.tsx
services/ui-src/src/utils/index.ts
services/ui-src/src/utils/reports/routing.test.ts
services/ui-src/src/utils/reports/routing.ts

Video of MFP dev behavior vs. new routing behavior
- Report page footer buttons don't route in dev, but they do with these changes
- The both navigate to the fallback route '/' at the moment since the other pages don't exist yet
https://github.com/Enterprise-CMCS/macpro-mdct-mfp/assets/57802560/a1ca7d18-4486-4e7e-8806-5cf7a8c44af4
MDCT-2747
---
- Login as state user
- Navigate to `/wp/general-information`
- Click 'Next' and 'Previous' buttons and verify it changes pages
---
---

add routing to report page footer and other uses

---

services/ui-src/src/components/fields/ChoiceListField.tsx
services/ui-src/src/utils/forms/forms.ts

https://github.com/Enterprise-CMCS/macpro-mdct-mfp/assets/19439679/fb0bf878-19be-4f6d-b8fd-9a824da270e3
---
Create a WP
Go to a page with nested choices (Like the first page's drawer!)
See the nested choices appear
---

Make nested choices show again

---

services/app-api/forms/wp.json
services/ui-src/src/components/cards/EntityCard.tsx
services/ui-src/src/components/cards/EntityCardTopSection.tsx
services/ui-src/src/components/forms/Form.tsx
services/ui-src/src/components/index.ts
services/ui-src/src/components/reports/ModalDrawerReportPage.tsx
services/ui-src/src/components/reports/OverlayModalPage.test.tsx
services/ui-src/src/components/reports/OverlayModalPage.tsx
services/ui-src/src/components/reports/ReportPageWrapper.tsx
services/ui-src/src/types/formFields.ts
services/ui-src/src/types/other.ts
services/ui-src/src/types/reports.ts
services/ui-src/src/utils/reports/entities.ts
services/ui-src/src/utils/testing/mockForm.tsx

State and Territory Specific Initiatives: II. Evaluation Plan
This page is showing up in the sidebar right now but will be moved to open up from a dashboard (currently WIP). 
Everything should look like the spec except for the year and quarter numberfield data in the EntityCard -- per the card, we are waiting on BO feedback for that functionality. For the time being that data is not in the EntityCard, and I will create a separate Jira card to address this functionality. Also the hint text on the `yes` radio option has been changed to show up beneath the question itself, and says `Note: If 'Yes', fields use calendar year quarters.`. This is a Design-approved change.
MDCT-2815
---
Create a work plan, go to State and Territory Specific Initiatives: II. Evaluation Plan inside State and …

Mdct 2815 - State and Territory Specific Initiatives: II. Evaluation Plan

---

services/ui-src/src/components/pages/Dashboard/DashboardTable.tsx
services/ui-src/src/utils/other/time.test.ts
services/ui-src/src/utils/other/time.ts

This change updates the name of the Work Plan as displayed on the Dashboard page. (i.e. revises it from `<program name> // <submission name>` to `{State} <program name> {<year> - Period <period>})`
Note: The requirement is to add the "State" to the submission name. I pulled the state from the `report`. Given that the mocks show that {State} should also appear in the **Page Title**, I assumed this was the correct value to fetch? Open to thoughts!! 🙏
MDCT-2794
---
1. Log in as a state user
2. Navigate to work plan page (i.e. /wp)
3. Create a new work plan 
4. Confirm that the work plan name matches the requirements ({State} <program name> {<year> - Period <period>})
---
- [✅ ] I have performed a self-review of my code
--- …

MDCT-2794: Update submission name

---

services/app-api/handlers/banners/fetch.test.ts
services/app-api/handlers/banners/fetch.ts
services/ui-src/src/components/banners/AdminBannerProvider.tsx

Successful retrieval of an empty banner returns a 200 status code instead of a 404 error.
MDCT-
---
Open inspect -> Network tab. Login and see that the adminBanner request results in a 200 status code with an empty object in the body.
---
---

replace non-existent banner status code to 200 from 404

---

services/app-api/handlers/banners/create.ts
services/ui-src/src/components/app/AppRoutes.test.tsx
services/ui-src/src/components/banners/AdminBannerProvider.test.tsx
services/ui-src/src/components/banners/AdminBannerProvider.tsx
services/ui-src/src/components/forms/AdminBannerForm.tsx
services/ui-src/src/components/pages/Admin/AdminPage.test.tsx
services/ui-src/src/components/pages/Admin/AdminPage.tsx
services/ui-src/src/components/pages/Home/HomePage.tsx
services/ui-src/src/types/banners.ts
services/ui-src/src/types/states.ts
services/ui-src/src/utils/state/useStore.ts
services/ui-src/src/utils/testing/setupJest.tsx
services/ui-src/src/verbiage/errors.ts

This PR adds validation to the Admin Banner create API call and then further integrates Zustand into it. You should now see the full Admin Banner experience!
https://github.com/Enterprise-CMCS/macpro-mdct-mfp/assets/19439679/424dd941-ebc2-431b-b14a-b3d7a355280a
MDCT-2964
MDCT-2965
---
Login as an admin (adminuser@test.com)
Open My Account through the top right dropdown
Open the Banner Editor
Create/Delete banners and visit the home page to see it live!

[MDCT-2964 + 2965] Admin Banner Handler Validation + Zustand Integration

---

services/ui-src/src/components/pages/Dashboard/DashboardTable.test.tsx

This PR replaces this other PR: https://github.com/Enterprise-CMCS/macpro-mdct-mfp/pull/113
I updated the branch name so that the deployment can successfully create an S3 bucket. My previous branch name was too many characters, causing the deployment to fail 
The error from the previous PR: 
```
Deploying uploads to stage mdct-2794-submission-name-tests (***)
CREATE_FAILED: AttachmentsBucket (AWS::S3::Bucket)
Bucket name should be between 3 and 63 characters long
```
The test results: 
```
PASS  src/components/pages/Dashboard/DashboardTable.test.tsx
Test getStatus utility
✓ should render the correct status if report has been unlocked (1 ms)
✓ should render the correct status if report has been unlocked
✓ should render the correct status if report has been archived
✓ should render the …
```

MDCT-2794 Dashboard Tests

---

services/ui-src/src/components/cards/EntityCardTopSection.tsx
services/ui-src/src/utils/reports/entities.ts

This fixes bug when adding new funding source.
I will be making another Funding Source branch which will take care of functionality for displaying funding source card quarters. This is just to stop the page from erroring out. https://qmacbis.atlassian.net/jira/software/c/projects/MDCT/boards/232?modal=detail&selectedIssue=MDCT-2982
---
https://github.com/Enterprise-CMCS/macpro-mdct-mfp/assets/14514294/f048a8a9-8d88-46c5-bad1-3be7f58f0541
1. Go to funding source page. 
2. Create new funding source. 
3. Card should display without throwing page error
---
---

Funding Sources - Bugfix

---

services/ui-src/src/components/accordions/FaqAccordion.tsx
services/ui-src/src/components/app/AppRoutes.tsx
services/ui-src/src/components/index.ts
services/ui-src/src/components/pages/HelpPage/HelpPage.tsx
services/ui-src/src/components/pages/HelpPage/HelpPageTest.tsx
services/ui-src/src/verbiage/pages/help.ts

This change adds a HelpPage that a user can navigate to when they click `Get Help` on the MFP pages
MDCT-2953
---
1. Log in as a user
2. Click 'Get Help' in the top right corner of the page 
https://github.com/Enterprise-CMCS/macpro-mdct-mfp/assets/9246062/4ed21b80-e485-4bdc-8051-231ff6f6cc7d
---
---

MDCT-2953: Add HelpPage

---

.github/workflows/dependabot-auto-merge.yml
.github/workflows/deploy.yml
.github/workflows/destroy.yml
.github/workflows/pull-request.yml
.github/workflows/scan_secrets.yaml
.github/workflows/scan_security-hub-jira-integration.yml
.github/workflows/scan_snyk-jira-integration.yml

Updating versions to avoid warnings and deprecations
Also modified deploy workflow to block using concurrency rather than lock script. That way only the `deploy` from the same branch can make it wait, and it uses native github actions logic rather than custom scripts. we are already using this in CARTS and QMR. More info from [QMR PR](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/pull/1968) and [docs for concurrency](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#examples-using-concurrency-and-the-default-behavior)
Also fixes application endpoint output to show up in summary
Also removing some unnecessary `cat .nvmrc` logic since we can read from that file with the setup node step
Note: these have already been tested in …

update workflows to avoid deprecations

---

services/app-api/forms/wp.json
services/ui-src/src/components/alerts/getWPAlertStatus.test.tsx
services/ui-src/src/components/alerts/getWPAlertStatus.tsx
services/ui-src/src/verbiage/pages/wp/wp-alerts.ts

More of less a final clean up for the alert box, I had talked to Megan about the conditional and made some updates. 
If the previous page questions were not answered, the alert box will stay up no matter what the user has entered. Also some text updates to match the figma.
MDCT-2795
---
1) Sign into MFP
2) Go to "State and Territory-Specific Initiatives" page
3) Do not answer the questions in "State & Territory Specific Initiatives Instructions"
4) Start adding one of each topic that has a * (5 total)
5) Answer the questions, the alert box will go away.
N/A
---
---

WP Initiative Alert Cleanup

---

services/ui-src/src/components/fields/CheckboxField.tsx
services/ui-src/src/components/forms/Form.tsx
services/ui-src/src/utils/forms/forms.ts

The 'Define Initiative' page now reflects “other target populations” that are entered in the 'Benchmark Projections' section. There's only target population logic ( repeatableTargetPopulationChoices function in form.ts) to fufill the ticket but the *getRepeatableChoiceLists* function can be used as a utility to create other repeat other choice lists.
https://github.com/Enterprise-CMCS/macpro-mdct-mfp/assets/14514294/1624fa75-5902-4056-a5fb-d5c4e94afbca
MDCT-[https://qmacbis.atlassian.net/browse/MDCT-2813]
---
1. Go to Transition Benchmark Projections
2. Create new target population and save
3. Go to State and Territory-Specific Initiatives: I. Define initiative
4. In the Target Populations section there should be a new Other option
---
--- …

WP - Repeatable ChoiceList Options ( Total Population Logic)

---

services/ui-src/src/components/forms/AdminDashSelector.tsx
services/ui-src/src/components/index.ts
services/ui-src/src/components/pages/Home/HomePage.tsx
services/ui-src/src/verbiage/pages/accordion.ts

This PR is to add the admin dashboard instructions:
But in order to show up I had to add the `AdminDashSelector` component from MFP and modify it a little for MFP so the user can select a state. I can remove that file and associated code after this is reviewed.
MDCT-2992
---
Login as an admin user, select a state, expand the `instructions` accordion and see the text matches the spec; login as a state user and see the instructions are unchanged.
---
---

Mdct 2992 - static text for admin dashboard instructions

---

services/ui-src/src/components/forms/AdminDashSelector.tsx
services/ui-src/src/forms/adminDashSelector/adminDashSelector.ts
services/ui-src/src/verbiage/pages/home.ts

clean up the AdminDashboardSelector files .
Admin user should be able to select the state and report they would like to view. This shouldn't change the State User's experience.
MDCT-2991
---
- log in as an admin, you should be redirected to this selection page
- upon selecting a report, the button becomes enabled (following the pattern of MCR)
- if button is clicked before selecting a state, the validation msg is show asking the admin to select a state
- once a state and a report is selected, you should be brought to that specific dashboard
---
---

clean up admin dashboard first page

---

services/ui-src/src/components/reports/ModalDrawerReportPage.tsx
services/ui-src/src/components/reports/ModalOverlayReportPage.tsx
services/ui-src/src/components/reports/OverlayModalPage.tsx
services/ui-src/src/utils/forms/forms.ts

The nested fields in our choice lists weren't correctly hydrating when a user selected a different radio option, exited the modal or drawer, and then re-entered it. This code fixes that issue. It's not pretty but the plan is to let Zustand take care of state management issues like these so this code won't be around long-term.
This is a cleaned up version of [this closed PR ](https://github.com/Enterprise-CMCS/macpro-mdct-mfp/pull/150) that had some extra code from a merge conflict.
https://jiraent.cms.gov/browse/CMDCT-2
---
Go into a drawer that has radio options (like the initiatives).
1. See that it saves correctly and hydrates correctly when you re-enter
2. Choose a different selection, go back to the original selection, see that all data has been cleared out.
Don't save, just exit. …

fix bug involving nested fields correctly clearing out and also repopulating with data

---

services/ui-src/src/components/accordions/FaqAccordion.test.tsx
services/ui-src/src/components/pages/Dashboard/DashboardPage.test.tsx
services/ui-src/src/forms/addEditMfpReport/addEditMfpReport.json
services/ui-src/src/utils/testing/mockFullReportJSON.tsx
services/ui-src/src/utils/testing/mockReport.ts

This change adds an FaqAccordion test and increases the test coverage on the DashboardPage tests. 
CMDCT-159
https://jiraent.cms.gov/projects/CMDCT/issues/CMDCT-159?filter=allopenissues
---
1. change directories to `services/ui-src`
2. run `yarn test` and `yarn test --coverage`
Note: coverage for the DashboardPage is not at 100 percent, but I wanted to put this code out since multiple people are working in the same test package
---
- [✅] I have performed a self-review of my code
- [✅ ] I have added [thorough](https://bit.ly/3zPrxuZ) tests, if necessary
- [N/A] I have updated relevant documentation, if necessary
---

CMDCT-159 UI tests (FaqAccordion and DashboardPage)

---

services/ui-src/src/components/modals/AddEditReportModal.test.tsx

This change adds tests for the AddEditReportModal for Work Plans. The test coverage is not at 100 percent yet as we need to add tests for SAR submissions. That will be in another PR :) 
CMDCT-159
---
1. change directories to `/services/ui-src`
2. Run `yarn test`
3. Check that tests pass
---
---

CMDCT-159 AddEditReportModal (WP) tests

---

services/ui-src/src/components/pages/Dashboard/DashboardPage.tsx
services/ui-src/src/verbiage/pages/accordion.ts
services/ui-src/src/verbiage/pages/sar/sar-dashboard.ts
services/ui-src/src/verbiage/pages/wp/wp-dashboard.ts

Empty view of the SAR dashboard for a state user, including an alert banner that shows if a user doesn't have an ongoing Work Plan.
Follow-up items / not covered in this pull request:
- Once statusing is in place for the Work Plan, the alert banner will need to be updated to show if a Work Plan is submitted and approved by an admin
- Table contents themselves are covered in a separate ticket
MDCT-2877
---
- Navigate to the `/sar` page
You should see an alert banner ⏰ 
- Navigate to the `/wp` 
- Create a new Work Plan
- Navigate back to the `/sar` page
The alert should be gone! 🪄 
---
---

MDCT-2877: SAR Dashboard (State User + Empty View)

---

services/ui-src/src/components/modals/Modal.tsx
services/ui-src/src/components/pages/ReviewSubmit/AdminReview.test.tsx
services/ui-src/src/components/pages/ReviewSubmit/AdminReview.tsx
services/ui-src/src/components/pages/ReviewSubmit/ReviewSubmitPage.tsx
services/ui-src/src/verbiage/pages/mfp/mfp-review-and-submit.ts

This is ONLY the UI portion of the following ticket. https://jiraent.cms.gov/secure/RapidBoard.jspa?rapidView=5874&projectKey=CMDCT&view=detail&selectedIssue=CMDCT-2995&quickFilter=32496
Once a state user submits a report, the admin can go into that report and see the following admin view.
What this ticket covers:
1. Admin Review verbiage on the Review & Submit page ( admin login only )
2. Unlock and Approve buttons
3. Modal pop-ups for both buttons
MDCT-[CMDCT-2995](https://jiraent.cms.gov/browse/CMDCT-2995)
---
1. Enter the app as a state user and fill out a report. 
2. Sign in as an admin user and select the state the form as filed in. 
3. In the Review and Submit section the admin view should show up. 
The unlock and approve buttons trigger the modals but the modals aren't currently …

MDCT -  WP Admin Review and Submit (UI only)

---

services/app-api/forms/sar.json
services/ui-src/src/components/reports/ReportPageIntro.tsx
services/ui-src/src/components/reports/ReportPeriod.tsx
services/ui-src/src/components/reports/StandardReportPage.tsx
services/ui-src/src/utils/other/time.ts

Each page in the `Recruitment, Enrollment, and Transitions` section needs the reporting period displayed. The exception is page 9, so I've excluded it and that work is its own card. I put this section into its own component and then brought it into the `ReportPageIntro` component. 
Also, the design has been updated, here is a screenshot of the spec:
CMDCT-3019
---
See that the reporting period text only appears in the Recruitment, Enrollment, and Transitions section, and page 9 differs. Also see that this text doesn't appear on any other pages (this component is shared across the WP and SAR.
---
---

Cmdct 3019 - add period info for R, E, T pages except for page nine

---

services/ui-src/src/components/reports/ReportPeriod.tsx

Currently when creating a new form, the initiative dashboard page will error out due to the reporting period being undefined.
https://github.com/Enterprise-CMCS/macpro-mdct-mfp/assets/127151429/54c88c5e-7e64-451e-a6f1-5baee76d993e
---
1) Sign into MFP
2) Create a new form
3) Create a new Initiative, and click the edit button. There should be no issues editing
N/A
---
---

Bug Fix Reporting Period

---

.github/workflows/deploy.yml
.github/workflows/snyk-auto-merge.yml

The Snyk integration's branch name lengths are too long, which is causing all the auto-opened PRs to fail during the deploy step. This is similar to an issue we've always had with dependabot. Adding this should fix it. 
n/a
---
Will have to merge and see 🤷
n/a
---
---

add branch name length check & automerge for snyk

---

services/app-api/forms/wp.json

Displays "Other Specify" Funding Source name in Funding Source card.
[### Related ticket(s)
[CMDCT-262]https://jiraent.cms.gov/browse/CMDCT-262
---
1. Login and go to "State and Territory-Specific Initiatives"
2. Create an initiative and edit it
3. Go to "Funding Sources" and create a source. 
4. Select "Other, Specify" and enter custom source name.
5. Fill out quarterly expenditures and save
6. The custom source name should show up in card
---
---

Missing Funding Source Other in Card  - Bugfix

---

services/ui-src/src/components/reports/ReportPageWrapper.tsx

Description
bug: sidebar would disappear if a user tries to return to all initiatives without clicking one of the buttons provided:
https://github.com/Enterprise-CMCS/macpro-mdct-mfp/assets/22454493/62acdc41-c34f-4431-9b96-f43c8551d19e
Related ticket(s)
[CMDCT-2364](https://jiraent.cms.gov/browse/CMDCT-2364)
How to test
Go to initiatives section, add initiative, enter it, and see that if you use your trackpad to go back, you'll land on the description page w/ the sidebar showing.
---
---

make sidebar show when user tries to return to all initiatives

---

services/ui-src/src/utils/other/time.ts

Just removing brackets from the long form period display
---
See that in the SAR,  no {} brackets appear
---
---

remove brackets

---

services/uploads/src/antivirus.js
services/uploads/src/clamav.js

Our virus scan started failing after upgrading the lambda runtime to node 18 because node 16 and below included aws-sdkv2 and node18+ includes aws-sdkv3
V2 to V3 upgrade suggestion from [this forum](https://stackoverflow.com/questions/74549995/error-cannot-find-module-aws-sdk-in-nodejs-aws-lambda-function) and confirmed by [AWS announcement](https://aws.amazon.com/blogs/compute/node-js-18-x-runtime-now-available-in-aws-lambda/)
Explanation of changes:
- Import changed from all of `aws-sdk` to modulized `@aws-sdk/client-s3`
- v2 [required](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/using-async-await.html) `.promise()` on awaits and [v3 does not](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/using-async-await.html)
- The …

Update antivirus and clamav to use aws-sdk-v3

---

services/ui-src/src/components/pages/Dashboard/DashboardPage.tsx

User could create another workplan before the latest one got admin approval. This disables the button unless the status of the latest wp is 'approved' 
CMDCT-424
---
-Create a workplan and submit it
-See that the create button is disabled
-Login as admin, approve the workplam
-login as state user, see that button is enabled
---
---

disable start wp button until wp is approved

---

services/ui-src/src/components/overlays/EntityDetailsOverlay.tsx
services/ui-src/src/components/tables/getEntityStatus.tsx

I missed this condition during the initial autosave fix. Sometimes auto save run a millisecond earlier than the submit button and therefore the submit function doesn't think anything had changed.
This fix prevents the page from returning to the dashboard if autosave is running and the user clicked the save & return button
P.S. Sneaking in an addon to fix the status not checking empty arrays correctly.
CMDCT-2812
---
1) Sign into MFP
2) Create a new WP
3) Enter WP and click **State and Territory-Specific Initiatives**
4) Add a new initiative and press Edit
5) Fill out Define Initiative and click Save & Return. The spinner in the button should run.
Before this update, save & return just immediately returns you to the dashboard
---
--- …

Add Autosave Check to I. Define Initiative 

---

services/ui-src/src/components/pages/Dashboard/DashboardPage.tsx

See title
[chakra docs for accordion props](https://chakra-ui.com/docs/components/accordion/props) -> see `defaultIndex`
CMDCT-3038
---
Login as a state user
Go to `/wp` and `/sar` in any order
Verify the instructions accordion on both pages is open by default
---
---

Make WP and SAR dashboard instructions open by default

---

services/ui-src/src/components/export/ExportedEntityDetailsOverlaySection.tsx
services/ui-src/src/components/export/ExportedEntityDetailsTable.tsx
services/ui-src/src/components/export/ExportedEntityDetailsTableRow.tsx
services/ui-src/src/components/export/ExportedModalDrawerReportSection.tsx
services/ui-src/src/components/export/ExportedModalOverlayReportSection.tsx
services/ui-src/src/components/export/ExportedReportFieldTable.tsx
services/ui-src/src/components/export/ExportedReportMetadataTable.tsx
services/ui-src/src/components/export/ExportedReportWrapper.tsx
services/ui-src/src/components/export/ExportedSectionHeading.tsx
services/ui-src/src/components/index.ts
services/ui-src/src/components/pages/Export/ExportedReportPage.tsx
services/ui-src/src/utils/index.ts
services/ui-src/src/utils/other/export.tsx
services/ui-src/src/verbiage/pages/wp/wp-export.ts

The second step in creating the WP PDF - porting over PDF components from MCR. 
There is probably a component or two that I won't end up needing, but I'm bringing them over now, and will delete later if I don't need them, or can't repurpose them.
CMDCT-218
---
You can create a workplan and then click Review PDF to be taken to the PDF export - there are a few things showing up, and hopefully no breaking errors.
You can fill out a WP and click Review PDF to see the export, which should have a little bit more info and components to see, and also no breaking errors.
---
---

start bringing over PDF components from MCR

---

services/ui-src/src/utils/validation/schemas.test.ts
services/ui-src/src/utils/validation/schemas.ts
services/ui-src/src/verbiage/errors.ts

Number validation was allowing lowercase letters and mixtures of numbers, decimals, and letters. This fix was taken from the fix made recently to MCR. The ratio validation was updated as well, since the function already existed in the `checkInputValidity` file.
https://github.com/Enterprise-CMCS/macpro-mdct-mfp/assets/22454493/e54af1cd-6ba1-4d8b-ac84-7765c6bd728d
CMDCT-2371
---
Create a workplan, create an initiative, edit it, go to Funding Sources, see that you can only enter numbers, `N/A`, and` Data not available`
https://github.com/Enterprise-CMCS/macpro-mdct-mfp/assets/22454493/711303ac-74a9-403f-a375-a5c037b793e1
---
---

fix number validation

---

services/ui-src/src/components/modals/DeleteEntityModal.tsx
services/ui-src/src/components/tables/EntityRow.tsx
services/ui-src/src/utils/other/renderHtml.ts

renderHTML was being called in entityRows and allowing for user entered data to be shown. Whoops! Was an accidental copy from MCR's exportedEntityRow and has now been removed.
---
Create a Workplan
Create a transition benchmark or initiative and pass into the textbox `<iframe src=javascript:alert(document.domain)>`
See that no alert pops up!
---
---

[PenTest] - Remove renderHTML from places it dont belong

---

services/app-api/utils/formTemplates/formTemplates.ts

Quarters were being determined by the date, but it needed to be set by the period. 
CMDCT-2372
---
See that when you create a workplan, the first quarter you see in the repeating quarter fields right now is 'Q3' instead of 'Q4'.
---
---

set repeating quarters to 1 or 3 depending on the period

---

services/ui-src/src/components/modals/AddEditEntityModal.test.tsx
services/ui-src/src/components/modals/AddEditEntityModal.tsx
services/ui-src/src/components/modals/Modal.tsx
services/ui-src/src/components/reports/ModalDrawerReportPage.tsx
services/ui-src/src/components/reports/ModalOverlayReportPage.tsx

Users should not be able to add multiple "Other" target populations with the same name. In this PR, we're disabling the `Save & close` button whenever a user attempts to add duplicated target populations and showing the following error:
**Note:** this was co-authored with @ailZhou and @gmrabian 🌟 
CMDCT-2229
---
- Create a WP
- Navigate to `wp/transition-benchmarks`
- Add a new Target Population
Try to add another target population with the exact same name and you should see an error message pop up with the Save & close button disabled.
N/A
---
---

CMDCT-2229: Error when trying to add a duplicated "Other" target population

---

services/ui-src/src/components/pages/Dashboard/DashboardPage.test.tsx
services/ui-src/src/components/pages/Dashboard/DashboardPage.tsx

See title.
CMDCT-2980
---
- Navigate to `DashboardPage.tsx`
- Comment out Line #325 [see here](https://github.com/Enterprise-CMCS/macpro-mdct-mfp/blob/997d1e5e420df86108a8a690ee028edb754f3f82/services/ui-src/src/components/pages/Dashboard/DashboardPage.tsx#L325)
- Create multiple Work Plans
To really visualize this, I'd recommend: 
- Creating a WP
- Filling a few fields so it's set to `In progress`
- Creating a new one
The newest one (with `Not started` status) should be at the top of the submissions dashboard.
N/A
---
---

CMDCT-2980: Sort WP & SAR Reports from Newest to Oldest on the Submissions Dashboard

---

services/app-api/forms/sar.json
services/app-api/forms/wp.json
services/app-api/utils/testing/mocks/mockForm.ts
services/app-api/utils/types/reports.ts
services/ui-src/src/components/tables/EntityRow.tsx
services/ui-src/src/types/reports.ts
services/ui-src/src/utils/testing/mockForm.tsx
services/ui-src/src/utils/testing/mockFullReportJSON.tsx

If a WP has been submitted or approved, the Transition Benchmarks buttons should read "View" instead of "Edit", and the other Transition Benchmarks buttons should read "View name" instead of "Edit name".
CMDCT-3044
---
- Log in and create a new WP
- Submit that WP
- Navigate to the `Transition Benchmark Projections` page
The buttons should now say "View":
---
---

CMDCT-3044: Change "Edit" button text to "View" in a submitted WP

---

services/ui-src/src/components/forms/Form.tsx
services/ui-src/src/utils/forms/forms.test.ts
services/ui-src/src/utils/forms/forms.ts
services/ui-src/src/utils/testing/mockEntities.tsx

Target populations that were not applicable to the Work Plan were being shown in the Define Initiative screen. This makes it so that those populations will not show as choices under the Target Population question! Questions that are not yet answered will still currently show.
https://github.com/Enterprise-CMCS/macpro-mdct-mfp/assets/19439679/5b513ce6-24ed-4fce-8184-8c9067b91667
CMDCT-2376
---
Create a workplan
Go to the Transition Benchmarks page and update some target populations with Yes or No, or simply leave them be
Create a couple Other target populations
Go to the Iniatives screen and create an initiative
Enter the created initiative and then go to Define Initiative
See the Target populations you marked as no not show as choices.
---

[CMDCT-2376] Make target populations only show if applicable

---

services/ui-src/src/components/modals/Modal.tsx
services/ui-src/src/forms/addEditWpReport/addEditWpReport.json

Addressed a lack of italics in the Create or Copy modal in the WorkPlan
CMDCT-419
---
in the Create modal, "Continue from previous period" should be italicized
in the Continue from Previous modal, "Continue from previous period" and "Reset Work Plan" should be italicized
link to figma
https://www.figma.com/file/oOJMUZerbafZefLQQ33GwI/MFP_Playground?type=design&node-id=4150%3A110854&mode=design&t=jcBVta11shAii8J9-1
---
---

Cmdct 419 bug

---

services/app-api/forms/wp.json
services/ui-src/src/components/cards/EntityCardTopSection.tsx
services/ui-src/src/components/cards/EntityStepCard.tsx
services/ui-src/src/components/reports/OverlayModalPage.tsx
services/ui-src/src/constants.ts
services/ui-src/src/utils/forms/forms.test.ts
services/ui-src/src/utils/forms/forms.ts
services/ui-src/src/utils/other/time.test.ts
services/ui-src/src/utils/other/time.ts

When copying over evaluation plan and funding source in the initiatives, there needs to be two need alert messages and changes to the cards. It should display something similar to the screenshot below.
CMDCT-2823
---
Because this only shows up after you copy over an already filled out WP, please follow the instructions in this PR: https://github.com/Enterprise-CMCS/macpro-mdct-mfp/pull/247
1) Once you have created a copy over WP, just verified that in that WP, any Evaluation Plan and Funding Source with quarters card look similar to the image above.
Evaluation Plan Alert Message : _Add the quantitative targets for the next 2 quarters by editing the objective._
Funding Source Alert Message: _Add the Projected quarterly expenditures for the next 2 quarters by editing funding source._
N/A …

WP Copy: Evaluation Plan and Funding Source Card Alerts

---

services/ui-src/src/components/export/PrintButton.test.tsx
services/ui-src/src/components/export/PrintButton.tsx
services/ui-src/src/components/index.ts
services/ui-src/src/components/pages/ReviewSubmit/ReviewSubmitPage.tsx
services/ui-src/src/components/reports/ModalDrawerReportPage.tsx

Made the PrintButton more reusable and added tests
Fixed PrintButton styling to match Figma
CMDCT-3102
---
- Create a WP
- Navigate to Transition Benchmarks and verify the "Review PDF" button opens a new tab with the export page
- Navigate to Review and Submit and verify the same
- In `PrintButton.tsx` set `isNonEditable` to true on line 16
- Verify on both pages that it now shows "Download PDF" with a different icon and styling (check against [Figma](https://www.figma.com/file/oOJMUZerbafZefLQQ33GwI/MFP_Playground?type=design&node-id=0-1&mode=design&t=Xj0CT1IGrqDUI8I2-0))
---
---

Make the print button work on transition benchmark page

---

services/app-api/utils/validation/completionSchemaMap.ts
services/app-api/utils/validation/completionSchemas.test.ts
services/app-api/utils/validation/completionSchemas.ts
services/app-api/utils/validation/schemaMap.test.ts
services/app-api/utils/validation/schemaMap.ts
services/ui-src/src/utils/validation/schemas.test.ts
services/ui-src/src/utils/validation/schemas.ts
services/ui-src/src/verbiage/errors.ts

- Added test to frontend and backend number schemas to prevent negative numbers from being entered
- Update test files to check for this case
- Removed unused `validNumber` and `numberNotLessThan*` schemas from frontend and backend (wasn't in WP or SAR and would cause more problems than it's worth maintaining. I imagine all schemas may end up in core eventually, in which case we'd only pull in what we need.)
CMDCT-3100
---
- Create a WP
- Go to Transition Benchmarks and open one of them
- Click "Yes" and play around with inputs to any number field
- Verify
- Negative numbers aren't allowed, and receive the proper error message
- "N/A" and "Data not available" are valid inputs
- Numbers with decimals are allowed
---
---

Disallow negative numbers; cleanup unused schemas

---

services/ui-src/src/components/modals/AddEditReportModal.tsx

When you are in the AddEditReportModal you can click the "Start new" button fast and it'll create multiple reports. Now these buttons are disabled when `submitting` is set to true, which happens at the top of the `writeReport` method the button triggers.
CMDCT-3101
---
- Go to WP dashboard and click "Start MFP Work Plan" 
- Click "Start new" as fast as you can multiple times
- Ensure only one WP gets created
To retest you can log in as an admin and archive the created WP, or restart the app.
---
---

Disable create report button while creating is in progress

---

services/app-api/forms/wp.json
services/ui-src/src/components/accordions/InstructionsAccordion.tsx
services/ui-src/src/components/alerts/Alert.tsx
services/ui-src/src/components/cards/EntityCardTopSection.tsx
services/ui-src/src/components/modals/AddEditEntityModal.test.tsx
services/ui-src/src/components/modals/AddEditEntityModal.tsx
services/ui-src/src/components/modals/AddEditOverlayEntityModal.test.tsx
services/ui-src/src/components/modals/AddEditOverlayEntityModal.tsx
services/ui-src/src/components/reports/ModalOverlayReportPage.tsx
services/ui-src/src/components/reports/ReportPageIntro.tsx
services/ui-src/src/components/tables/EntityRow.tsx
services/ui-src/src/styles/theme.ts

Per Kim's QA doc https://docs.google.com/spreadsheets/d/1HNW-ENP8JEQGvKIF9Urqn_lsIO9vveO7NGHHXEF3T2E/edit?pli=1#gid=279024116
Items addressed:
- WP All Initiatives Dashboard: Wrong icon is used in the alert. Should be the [alert circle icon](https://qmacbis.atlassian.net/wiki/spaces/CM/pages/2954887194/Graphic+Assets) (line 4)
- update header alignment in specific initiative dashboard (line 7)
- Close out disabled button should be gray (line 8)
- Previous page is missing the underline on initatives dashboard (line 3)
- update AddEditEntityModals to say Save instead of Save & close (line 5)
- update reportPage width to match basicPageWidth (line 7, also)
- update initiative entityRow margins (line 21)
- update theme color to match figma and add colors to the overModal page accordion (line …

Address WP UI bugs

---

services/app-api/handlers/reports/release.ts
services/ui-src/src/components/pages/ReviewSubmit/ReviewSubmitPage.test.tsx
services/ui-src/src/components/pages/ReviewSubmit/ReviewSubmitPage.tsx
services/ui-src/src/types/reportContext.ts

State users should be able to re-submit a Work Plan after it's been unlocked by an Admin user and it is `In revision` (even if they haven't made any changes since it unlocked)
CMDCT-3097
---
- Create and submit a new WP
- Log in as an admin user
- Unlock the submitted WP
- Log back in as the state user
Check for these two use-cases:
**You haven't made any changes**
- Navigate directly to `Review & submit`
- The `Submit WP` button should be enabled and you are able to submit
**You've made some new changes in this revision**
- Change anything in the WP, I'd recommend adding a new Transition Benchmark and NOT completing it yet
- Navigate to `Review & submit` 
- The `Submit WP` button should be disabled 'cause your WP is not complete
- Complete the WP
- Now you should …

CMDCT-3097: Allow state user to re-submit WP that is "In Revision" status

---

services/ui-src/src/components/export/ExportedModalDrawerReportSection.tsx
services/ui-src/src/components/modals/AddEditReportModal.tsx
services/ui-src/src/components/tables/Table.tsx
services/ui-src/src/types/other.ts

This is part one of completing the PDF target population table. 
This includes:
1. Header truncate {Other} target populations
2. Asterisks show on rows that have missing data
3. N/A displays in total column for cols that are all "N/A"
4. Totals for rows and columns
5. Display hyphens on the total row and total colums when a user doesn't have all values filled
6. When there are more than 2 Transition Benchmark Projections a overflow table is generated
Overflow
Work in progress:
7. Giving the overflow table cells a max width
CMDCT-](https://jiraent.cms.gov/secure/RapidBoard.jspa?rapidView=5874&projectKey=CMDCT&view=detail&selectedIssue=CMDCT-3061)
---
1. Fill out and Submit a WP 
4. Click the "Review and Submit" tab and go to "Review PDF"
---
--- …

PDF - Transition Benchmark Table - ( Includes Table Overflow )

---

services/ui-src/src/components/cards/TemplateCard.test.tsx
services/ui-src/src/components/drawers/ReportDrawer.test.tsx
services/ui-src/src/components/drawers/ReportDrawer.tsx
services/ui-src/src/components/export/ExportedReportBanner.test.tsx
services/ui-src/src/components/fields/ChoiceListField.tsx
services/ui-src/src/components/forms/Form.tsx
services/ui-src/src/components/modals/AddEditEntityModal.test.tsx
services/ui-src/src/components/modals/AddEditEntityModal.tsx
services/ui-src/src/components/modals/AddEditOverlayEntityModal.test.tsx
services/ui-src/src/components/modals/DeleteEntityModal.test.tsx
services/ui-src/src/components/modals/DeleteEntityModal.tsx
services/ui-src/src/components/modals/Modal.tsx
services/ui-src/src/components/overlays/EntityDetailsOverlay.test.tsx
services/ui-src/src/components/overlays/EntityDetailsOverlay.tsx
services/ui-src/src/components/pages/Dashboard/DashboardPage.tsx
services/ui-src/src/components/pages/ReviewSubmit/ReviewSubmitPage.tsx
services/ui-src/src/components/reports/ModalOverlayReportPage.tsx
services/ui-src/src/components/reports/OverlayModalPage.test.tsx
services/ui-src/src/components/reports/OverlayModalPage.tsx
services/ui-src/src/components/statusing/StatusTable.tsx
services/ui-src/src/components/tables/EntityRow.tsx
services/ui-src/src/types/states.ts
services/ui-src/src/utils/state/useStore.ts
services/ui-src/src/utils/testing/setupJest.tsx

This branch is to address the missing parts as well as consolidate some of the logic when differentiate edit / view mode of a report.
From Kim:
State users are the only users who can ever add, edit, delete data to the form, and only when the form is unlocked — the following statuses:
- In progress
- Not started
- In revision
All other times the form is view-only for them.
All other users (Admin, Help desk) the form itself is always view only. Admin have the ability to approve, lock/unlock, and archive/unarchive.
---
As a means to make switching between modes easier and updating, I added the tracking to the state management. When you enter the report, it checks the state it should show the form in and adjust accordingly.
[Figma for …

WP - Edit / View Mode UI

---

services/app-api/utils/types/formFields.ts
services/app-api/utils/validation/completionStatus.test.ts
services/app-api/utils/validation/completionStatus.ts
services/ui-src/src/types/formFields.ts

This is mostly additional unit tests, but there is also some dead code removal.
MCPAR in MCR has a FormField property called `repeat`. This is distinct, and behaves differently from the MFP FormField property called `repeatable`. The `repeat` validation code only existed in MFP because it was copied from MCR, so I have removed it rather than adding tests for it.
n/a
---
1. Run the unit tests
2. Verify that the only instances of `/\brepeat\b/` in the entire app are inside comments (or yarn.lock files), so there is no way the `repeat` validation code could have been doing anything.
n/a
---

Add some tests around completionStatus.ts

---

services/app-api/forms/sar.json
services/app-api/handlers/reports/create.ts
services/ui-src/src/components/accordions/InstructionsAccordion.tsx
services/ui-src/src/components/pages/Dashboard/DashboardPage.tsx
services/ui-src/src/components/reports/ModalOverlayReportPage.tsx
services/ui-src/src/components/tables/getEntityStatus.tsx
services/ui-src/src/utils/other/parsing.ts

Changed the data structure of how we saved WP data in SAR so that the State- or Territory-Specific Initiatives page will render in SAR and cleaned up some of the text rendering.
The logic for ModalOverlayReport page is if there's no modal being used, certain items won't render or display.
CMDCT-32
---
1) Sign into MFP, any state user
2) Fill out a WP and submit it
3) Create a SAR
4) In the SAR, select State-or-Territory Initiative 
5) Check to see that the page renders with the initiative from the WP and looks more or less like this: https://www.figma.com/file/oOJMUZerbafZefLQQ33GwI/MFP_Playground?type=design&node-id=21-4592&mode=design&t=B0BP0dH3mJg0ylWY-4
---
--- …

SAR State or Territory Initiative Page

---

services/app-api/handlers/reports/create.ts
services/app-api/utils/other/copy.ts
services/ui-src/src/components/modals/AddEditReportModal.tsx
services/ui-src/src/components/pages/Dashboard/DashboardPage.tsx

A request by design to be able to toggle the testing for copy over on and off. It will generate the next report based on the previous report whenever the previous report is Approved.
@karla-vm helped me create a flag and its turned on in dev. 
The flag is not turned on locally so you'll have to turn it on manually in the code.
In AddEditReportModal.tsx line 44, check isCOpyOverTest to equal true
---
1) Change code in script first
2) Sign into MFP as a state user.
3) Create a new WP
4) Fill out the form and submit
5) Go into admin an approve
6) Go back to state user and you should be able to create a new form.
7) Process should be repeatable.
---
--- …

Adding Flag to Toggle Copy Over Testing

---

services/app-api/forms/wp.json

Note: first commit was just auto-formatting on save, so the form must not have been formatted in a previous change.
Only real change is [the second commit](https://github.com/Enterprise-CMCS/macpro-mdct-mfp/commit/fbad98d785eee29793191574dc9cb033ed1c63aa), lines 1207-1209, which add the currency mask
CMDCT-3131
---
- Create a WP
- Creating a funding source for that initiative
- Verify that the funding sources per quarter have the dollar sign mask, remove decimals beyond 2 places, and allow `N/A` and `Data not available` as valid inputs
---
---

Funding sources currency mask 3131

---

services/ui-src/src/utils/forms/forms.ts

Adding "Not Applicable" option to the target populations choice list. 
[CMDCT-](https://jiraent.cms.gov/browse/CMDCT-3109)
---
1. Create a report 
2. Go to 'State- or Territory-Specific Initiatives' and create and edit a initiative
3. Edit 'I. Define initiative'
4. In the Target population(s) choice list you should see the 'Not applicable' option.
---
---

Add Not Applicable Option to Target Pop. Choice List

---

services/ui-src/src/components/modals/AddEditOverlayEntityModal.tsx

As per design we want the view only experience for these modals to have the "Save" button disabled, rather than changing the text and enabling it.
CMDCT-3132
---
- Sign in as a state user
- Create a WP
- In the initiative, create an objective and a funding source
- Logout
- Sign in as an admin
- View the initiative you created and verify the objective and funding source modals have a "Save" button that is disabled
---
---

Make funding source and objectives modals match view only experience

---

services/ui-src/src/utils/forms/forms.ts

Report was crashing when skipping a question because it performed a check on the empty field without null handling
Video of bug in action (tab through Define Initiative and skip the radio options for end date)
https://github.com/Enterprise-CMCS/macpro-mdct-mfp/assets/57802560/fadceadb-bce1-4345-90c5-3ea540b25edf
CMDCT-3124
---
Do the same steps in this branch and verify that it doesn't crash
- Go to Define Initative
- **TAB THROUGH** each option, skipping the final radio and hitting spacebar on "Save & Return"
- Verify it triggers validation on the radio instead of crashing
---
---

Fix Define Initiative end date not populated error

---

services/ui-src/src/components/export/ExportedModalDrawerReportSection.tsx

Target Populations that were marked as Not Applicable were showing up in red and marked as No Answer. Changed to black and marked as N/A
CMDCT-3129
---
Create a work plan
Go to Target Populations
Edit one and mark it as Not Applicable (Answer No)
Check the PDF to see that its black and marked as N/A
Create a new Target Population
Edit one and mark it as Not Applicable (Answer No)
Check the PDF to see that its black and marked as N/A
---
---

Make not applicable target populations show as NA in export

---

services/ui-src/src/components/pages/Dashboard/DashboardPage.test.tsx
services/ui-src/src/components/pages/Dashboard/DashboardTable.tsx
services/ui-src/src/components/pages/Dashboard/MobileDashboardTable.tsx
services/ui-src/src/components/pages/ReviewSubmit/AdminReview.tsx
services/ui-src/src/components/reports/ReportProvider.tsx
services/ui-src/src/utils/testing/mockReport.ts
services/ui-src/src/utils/testing/setupJest.tsx

A couple of issues with the admin unlock feature.
All of this is happening on the Admin dashboard
_1) Approved WP was still unlockable, which should not be the case._
Fix: I thought approved was an unlockable state, just needed to remove the check.
_2) Admin state selector page became view only after going to a view only WP._
Fix: The editable state management did not update after exiting the WP so any button / fields was stuck in the previous state.
_3) An error message pops up when unlocking a WP from the dashboard, there should be no error message_
Fix: There was a call for hydrating in the api call which does not exist in MCR unlock and also passed in an empty report. Removed because it looked to be an accident that was causing us to get an error. If this is not okay, please let me …

Admin Unlock Bugs

---

services/ui-src/src/components/accordions/TemplateCardAccordion.test.tsx
services/ui-src/src/components/alerts/getWPAlertStatus.test.tsx
services/ui-src/src/components/app/AppRoutes.test.tsx
services/ui-src/src/components/banners/AdminBannerProvider.test.tsx
services/ui-src/src/components/cards/EntityStepCard.test.tsx
services/ui-src/src/components/forms/AdminBannerForm.test.tsx
services/ui-src/src/components/forms/FormLayoutElements.test.tsx
services/ui-src/src/components/modals/CloseEntityModal.test.tsx

Nothing fancy, just some tests. They add up to +2.14% line coverage for ui-src.
CMDCT-3121
---
`yarn test --coverage`
n/a
---

Add some miscellaneous tests in ui-src

---

services/ui-src/src/components/reports/ReportPageFooter.tsx

Page one of the WP was generating a console error because of `praDisclosure` being spread as a property into the ReportPageFooter
If you do a search in the repository for `<ReportPageFooter` the results indicate there is never a case where we pass in unexpected props (not in Props for that component) we want to spread
Removing this spread eliminates this issue.
We could even go further to declare `praDisclosure` in the Props definition for ReportPageFooter and remove the `[key: string]: any` only used for that property. Let me know if you want to go that course.
---
- On branch `main`
- Create a WP
- Open your console and clear it
- Click "Edit" to enter the WP
- Verify there is a console error about `praDisclosure`
- Switch to this branch `pra-console-error`
- …

Remove props spread from report footer to avoid console errors

---

services/ui-src/src/components/layout/Footer.tsx

The page footer was creating a console error related to using `:first-child` in the styling for links.
The top answer in [this stack overflow post](https://stackoverflow.com/a/24657721) does a pretty good job explaining the difference between these selectors. In this use case it does not matter that they don't work exactly the same because they do the same thing when applied here.
---
- On branch `main`
- Before logging in open the console
- Verify that an error about `:first-child` shows up in the console
- Switch to this branch `fix-first-el-error`
- Logout and relog in with the console open
- Verify the same error does not come up
- Verify the "Contact Us | Accessibility Statement" links in the footer look the same (spacing, bar between, etc.)
- You can change …

fix first child console error in footer

---

services/app-api/forms/wp.json

React Fragments cannot accept properties other than key and children.
Because of how we do content parsing any blob provided as `"type": "html"` is rendered inside a react fragment
[html assignment](https://github.com/Enterprise-CMCS/macpro-mdct-mfp/blob/main/services/ui-src/src/utils/other/parsing.ts#L30)
[element creation logic](https://github.com/Enterprise-CMCS/macpro-mdct-mfp/blob/main/services/ui-src/src/utils/other/parsing.ts#L62-L68)
This was causing a console error when "style" was passed into the fragments properties. It turns out only one piece of content of type html was using props, and it didn't actually change the view, so I removed it. Now the error doesn't show up
Feedback:
- Do we want to instead remove styling from anything that is of type html? this feels wasteful …

Remove styling from html where it did nothing and to avoid console error

---

services/app-api/forms/wp.json
services/ui-src/src/components/cards/EntityCardTopSection.tsx
services/ui-src/src/components/forms/Form.tsx
services/ui-src/src/components/pages/Dashboard/DashboardTable.tsx
services/ui-src/src/components/reports/OverlayModalPage.tsx
services/ui-src/src/verbiage/pages/wp/wp-dashboard.ts

addressed more UI issues from the QA doc - these updates have been reviewed and approved by Kim
- Addressed left alignment in WP submission dashboard  (admin SAR view will be addressed in CMDCT-3137)
------------------------------------------------------------------
- place AddEntityButton above the dashboardTitle in the Evaluation and Funding pages
------------------------------------------------------------------
- update funding and evaluation card headers to be 16px, and spacing
------------------------------------------------------------------
- add 2.5rem of space between footer and transition benchmark strategy form
------------------------------------------------------------------
CMDCT-3125
---
- go to the pages where these items are and compare them against the Figma doc
---
--- …

UI Updates pt 2

---

services/app-api/forms/wp.json
services/app-api/handlers/reports/update.ts
services/ui-src/src/components/cards/EntityCardTopSection.tsx
services/ui-src/src/components/export/ExportedModalOverlayReportSection.tsx
services/ui-src/src/components/forms/Form.tsx
services/ui-src/src/components/layout/Footer.tsx
services/ui-src/src/components/pages/Dashboard/DashboardTable.tsx
services/ui-src/src/components/reports/OverlayModalPage.tsx
services/ui-src/src/components/reports/ReportPageFooter.tsx
services/ui-src/src/components/tables/EntityRow.tsx
services/ui-src/src/components/tables/getEntityStatus.tsx
services/ui-src/src/verbiage/pages/wp/wp-dashboard.ts

- Remove props spread from report footer to avoid console errors (CMDCT-none) [PR](https://github.com/Enterprise-CMCS/macpro-mdct-mfp/pull/298)
- fix ":first-child" console error in footer (CMDCT-none) [PR](https://github.com/Enterprise-CMCS/macpro-mdct-mfp/pull/299)
- [PDF] Statusing Fix for WP Initiatives on Export (CMDCT-3128)
- Remove styling from html where it did nothing and to avoid console error (CMDCT-3110)
- Update copy on evaluation plan modal [PR](https://github.com/Enterprise-CMCS/macpro-mdct-mfp/pull/296)
- Variable rename: Change blacklist to blocklist [PR](https://github.com/Enterprise-CMCS/macpro-mdct-mfp/pull/304)

main -> val (sprint #49, part 2)

---

services/ui-src/src/components/export/ExportedModalDrawerReportSection.tsx
services/ui-src/src/components/tables/Table.tsx
services/ui-src/src/constants.ts

The Transition Benchmarks PDF table had some more rules to follow. Some of these didn't work due to "Answered" being capitalized instead of lowercase in some equality checks. See How to test for more details on the rules we are trying to follow
CMDCT-3151
---
- Create a WP
- Open the PDF and view the `Transition Benchmark Projections` table
- Answer the questions on the transition benchmarks page and verify the table follows these rules as you do so (you'll need to refresh the pdf page after making changes):
• If a user doesn't answer the drawer (radio buttons) for Transition Benchmarks Projections for a target population (it's still in its default state), then show "Not answered" on the PDF table column for that population (in color-error-darker red). Any sums of …

Update PDF table per design requests

---

services/ui-src/src/components/alerts/getWPAlertStatus.test.tsx
services/ui-src/src/components/alerts/getWPAlertStatus.tsx
services/ui-src/src/components/forms/Form.tsx

A previous update had removed the * from the initiative entity's labels but it missed making the change for tracking by the alert status, which prevented the WP from being marked as complete. This PR will rectify that. It also fix the label not cleaning up "(*if applicable)" correctly.
---
1) Sign into MFP, any stateuser
2) Create a new WP
3) Fill out the State- or Territory-Specific Initiatives
4) Alert box should respond accordingly
N/A
---
---

Initiative Alert Status

---

services/ui-src/src/components/reports/ReportProvider.test.tsx

Nothing fancy, just some tests. They add up to +1.59% coverage for ui-src, I believe.
The interactions between the provider and the store (such as `setReport`) remain untested, because that would be difficult for me and they only add up to a few lines anyway.
CMDCT-3121
---
`yarn test --coverage`
n/a
---

Add some tests for ReportProvider

---

services/ui-src/src/components/modals/AddEditReportModal.tsx
services/ui-src/src/components/pages/Dashboard/DashboardTable.tsx
services/ui-src/src/components/pages/Dashboard/MobileDashboardTable.tsx

Removing the `Target populations` column from the SAR admin dashboard and adding the `Edit` button.
CMDCT-3137
---
- Create and submit a Work Plan
- Log in as an admin
- Approve that Work Plan
- Log back in as a state user
- Create (no need to submit) a SAR
- Log back in as an admin
You should see an `Edit` icon button on the SAR dashboard that opens a view-only modal and the `Target populations` column should be gone.
N/A
---
---

CMDCT-3137: SAR Admin Dashboard Updates

---

services/app-api/utils/other/other.ts
services/app-api/utils/testing/mocks/mockReport.ts

Adds 'MFP' to report names between state and report type
I only found one test that used this so let me know if you know of more places! Tests pass.
Note: Product said existing reports are ok to leave as is
CMDCT-3139
---
- Create a WP
- Verify the name is follows the format `{state} MFP Work Plan ....`
- If you feel up for it fill out and submit the WP and create a SAR to test that one too
---
---

Add MFP to report names

---

services/ui-src/src/components/export/ExportedModalDrawerReportSection.tsx
services/ui-src/src/components/export/ExportedReportWrapper.test.tsx

Add jest tests for ExportedReportWrapper
Update the ExportedModalDrawer component to not show an empty h2 if there isn't a pdfDashboardTitle
CMDCT-3154
---
---
---

add exportedReportWrapper tests CMDCT-3154

---

services/ui-src/src/components/accordions/TemplateCardAccordion.test.tsx
services/ui-src/src/components/accordions/TemplateCardAccordion.tsx
services/ui-src/src/components/cards/TemplateCard.tsx
services/ui-src/src/verbiage/pages/home.ts

Updating the WP and SAR homepage to match the latest verbiage, as well as adding a link for `User Guide and Help File` download. 
**NOTE:** The links themselves are not available yet, they will be updated as part of a follow-up ticket. 
CMDCT-3138
---
Log in as a state user and verify that the updated verbiage and new links match the Figma mockups:
---
---

CMDCT-3138: Updated WP and SAR Homepage (Verbiage + Styling)

---

services/app-api/utils/other/other.ts

When creating a SAR we also update the associated WP. We fetch the WP, [spread its metadata](https://github.com/Enterprise-CMCS/macpro-mdct-mfp/blob/main/services/app-api/handlers/reports/create.ts#L308), adding the `associatedSar` field, and update it. The problem is this uses our report fetch, which [returns metadata, formTemplate, and fieldData all together](https://github.com/Enterprise-CMCS/macpro-mdct-mfp/blob/main/services/app-api/handlers/reports/fetch.ts#L98-L104) for the frontend. Then `formTemplate` and `fieldData` mistakenly get spread in as metadata when we add the field for the SAR.
This takes a structured clone of the fetch and removes those two fields so that the metadata is pure.
CMDCT-3167
---
- As a state user, create and submit a WP
- As an admin user, approve that WP …

Fix formtemplate and fieldData getting saved in WP metadata upon SAR creation

---

services/app-api/forms/sar.json
services/ui-src/src/components/cards/EntityCardBottomSection.test.tsx
services/ui-src/src/components/cards/EntityCardBottomSection.tsx
services/ui-src/src/components/cards/EntityCardTopSection.test.tsx
services/ui-src/src/components/cards/EntityCardTopSection.tsx
services/ui-src/src/components/cards/EntityStepCard.test.tsx
services/ui-src/src/components/cards/EntityStepCard.tsx
services/ui-src/src/components/reports/OverlayModalPage.tsx
services/ui-src/src/utils/testing/mockEntities.tsx

This PR addresses the answers for Qualitative Objectives (not quantitative, that comes in a future PR).
The status symbol should be correct
the Report/Edit buttons should show up correctly based on if the state user has updated their progress or not
State users responses should show up in the blue boxes after they submit via the modal
CMDCT-44
---
- create a work plan, add some fun data to an initiative - evaluation plan (that's what you'll see later in the test)
- approve the WP
- create a SAR and head to the State- or Territory-Specific Initiatives section and click into an initiative
- click into the Objective Progress step
- view the Objective Progress card and verify that it matches the figma designs
- click the "Report Objective Progress" button
- modal appears, answer the …

SAR objective progress - add modal

---

services/app-api/forms/sar.json
services/ui-src/src/components/export/ExportedModalOverlayReportSection.tsx
services/ui-src/src/components/export/ExportedReportFieldTable.tsx
services/ui-src/src/components/export/ExportedSectionHeading.tsx
services/ui-src/src/components/pages/Export/ExportedReportPage.tsx
services/ui-src/src/components/reports/ReportPageIntro.tsx
services/ui-src/src/components/reports/StandardReportPage.test.tsx
services/ui-src/src/utils/other/export.tsx
services/ui-src/src/verbiage/pages/sar/sar-export.ts

1. Add Additional Achievements to SAR PDF (w/ style ajustments)
2. Nested choices now render in SAR PDF
[CMDCT-3108](https://jiraent.cms.gov/browse/CMDCT-3108)
---
1. Fill out SAR
2. View PDF and scroll to bottom to check Additional Achievements 
( The red border was already there. It may be to mark the table sections so I left it alone )
---
---

SAR PDF - Additional Achievements 

---

services/app-api/handlers/reports/create.ts
services/app-api/utils/formTemplates/formTemplates.test.ts
services/app-api/utils/formTemplates/formTemplates.ts

Using hash to determine which version of the formTemplate to return to the user.
When a user creates a form, the system will get the base WP/SAR json, make a copy of it and then run the scan and transformation rules on the form copy. Once it finishes modifying that form, it will generate a hash out of that data and then check the database to see if a formTemplate with the same hash exist. If that hash exist, we retrieve that saved formTemplate and return it to the user, if not, we save the form copy we just created to the database. 
This is a temporary fix for the bug in prod until we can fully implement @benmartin-coforma FormTemplate version.
CMDCT-3161
---
1) Run local dynamodb to be able to see if the versions are updating correctly
1) Sign into MFP as a state user.
2) Create, fill …

FormTemplate Versions Option 1 - Hash

---

services/ui-src/src/components/export/ExportedModalOverlayReportSection.tsx
services/ui-src/src/components/export/ExportedReportFieldTable.tsx
services/ui-src/src/components/export/ExportedReportMetadataTable.tsx
services/ui-src/src/components/export/ExportedSarDetailsTable.tsx
services/ui-src/src/components/index.ts
services/ui-src/src/components/pages/Export/ExportedReportPage.tsx
services/ui-src/src/verbiage/pages/sar/sar-export.ts
services/ui-src/src/verbiage/pages/wp/wp-export.ts

Creating and styling the PDF for the `SAR General Information` page (and its internal sections), as well as pulling the metadata for the PDF.
CMDCT-3104
---
There's the _old_ way:
- Create and submit a Work Plan
- Log in as an admin user
- Approve the Work Plan
- Log back in as state user
- - Create a new SAR
- Fill in the `General Information` page (the first page of this form)
- Navigate to `Review & submit` and click on `Review PDF`
And then there's the _coooool_ way:
- Use @gmrabian and @keeysnc 's handy dandy `MFP Postman Collection` to create, fill, submit, AND approve a WP 😎 
- Create a new SAR
- Fill in the `General Information` page (the first page of this form)
- Navigate to `Review & submit` and click on `Review PDF`
The metadata tables at the top of …

CMDCT-3104: [PDF] SAR General Information Page + Metadata Table

---

services/ui-src/src/components/overlays/EntityDetailsDashboardOverlay.tsx
services/ui-src/src/components/tables/EntityRow.tsx
services/ui-src/src/components/tables/getEntityStatus.test.ts
services/ui-src/src/components/tables/getEntityStatus.tsx
services/ui-src/src/types/reports.ts
services/ui-src/src/utils/testing/mockForm.tsx

Some new tests, with two changes to "real" code:
1. Fix the type for EntityRow.formEntity.
* This was set to the wrong type (ReportJson), but it was being cast to `any` on the way in (in EntityDetailsDashboardOverlay) and on the way out (to getEntityStatus.getInitiativeDashboardStatus)
* This is almost a no-op change; Typescript type annotations have no effect on runtime behavior.
* However it _did_ expose a bug with the `EntityRow.key`; I believe all rows were getting the same key. Now they will get an index-based key.
2. Fix a potential bug when detecting optional fields in getCloseoutStatus
* Sometimes validation is a string, sometimes it's an object.
* I don't believe this bug ever manifested; if I recall correctly, all of our optional fields currently have validation as a string in …

Add tests for getEntityStatus

---

services/app-api/forms/wp.json
services/app-api/utils/validation/completionValidation.ts

Currently, in the `WP Define Initiative` step, if a user selects `No` to the last question of the form, they are not able to submit using the `Save & return` button. 
The issue was that the "Yes" option has a nested child input field, but it was not marked as `nested` in the `wp.json` and users weren't able to submit because the form was "incomplete" unless that field was filled.
CMDCT-3181
---
You should be able to select `No` and submit this form now.
---
---

CMDCT-3181: [Bug] WP - Define Initiative

---

services/ui-src/src/components/reports/StandardReportPage.tsx

When a SAR report is started the resubmission field was showing up. I added to the conditional to properly hide it until a report is being resubmitted.
new logic:
1. if report is a SAR AND submissionCount isn't there - hide the resubmission field. ( submissionCount doesn't show until a 
submission is complete)
OR
2.  if report is Submitted AND submissionCount is 1 AND report is locked - hide the resubmission field ( this is the first time a user submits a report then decides to refresh the page. The resubmissionCount property shows up and has a value as 1 and the report is locked). 
CMDCT-https://jiraent.cms.gov/browse/CMDCT-3200

Resubmission Field Bugfix

---

services/ui-src/src/components/export/ExportedRETTable.test.tsx
services/ui-src/src/components/export/ExportedRETTable.tsx

The R, E & T section in SAR pdf renders a bunch of charts based on the transition benchmarks that were selected. When there was no transition benchmark being utilized, the pdf was erroring out. This PR will fix the render issue and display a message saying, "Your associated MFP Work Plan does not contain any target populations.", if no chart is rendered.
CMDCT-3214
---
1. Sign into MFP, any state user
2. Fill out a WP, say no to all transition benchmark and submit
3. Sign out and login as admin user
4. Approve the previously submitted WP
5. Signout and sign back in as the state user
6. Create a SAR
7. Go to Review & Submit section, click Review PDF
8. The page should rendered and each R, E & T section should show a message saying "Your associated MFP Work Plan does not contain any target …

[Bugfix] SAR PDF Not Rendering with Transition Benchmarks

---

services/ui-src/src/components/export/ExportedModalOverlayReportSection.test.tsx
services/ui-src/src/components/export/ExportedModalOverlayReportSection.tsx
services/ui-src/src/components/export/ExportedOverlayModalReportSection.test.tsx
services/ui-src/src/components/export/ExportedOverlayModalReportSection.tsx
services/ui-src/src/components/export/ExportedReportFieldTable.test.tsx
services/ui-src/src/components/export/ExportedReportFieldTable.tsx
services/ui-src/src/components/export/ExportedReportWrapper.test.tsx
services/ui-src/src/components/export/ExportedReportWrapper.tsx
services/ui-src/src/utils/testing/mockForm.tsx
services/ui-src/src/utils/testing/mockReport.ts

Tests for the following export files. (update to ExportedReportFieldTable.tsx which also increases coverage)
1. ExportedModalOverlayReportSection.tsx
2. ExportedReportFieldTable.tsx
CMDCT-[MDCT-3194](https://qmacbis.atlassian.net/browse/MDCT-3194]
---
---
---

3194 Export Coverage Continued

---

services/ui-src/src/components/overlays/EntityDetailsOverlay.test.tsx
services/ui-src/src/components/overlays/EntityDetailsOverlay.tsx
services/ui-src/src/utils/testing/mockForm.tsx
services/ui-src/src/utils/testing/mockReport.ts

Increasing code coverage from EntityDetailsOverlay. 
I removed one of the mock form field being a dropdown as I don't think we have any dropdowns in WP or SAR and it was preventing me from being able to to test onSubmit. We may have also removed some code with rendering dropdowns at one point too?
From 40% to 96% line coverage:
---
Run **yarn coverage** in the **/ui-src/ folder**
---
---

EntityDetailsOverlay Test Coverage

---

services/ui-src/src/utils/reports/entities.ts

Adding a comma-separated mask to qualitative target values on the `II. Evaluation plan` step for an initiative.
CMDCT-3227
---
- Create a WP
- Navigate to the initiatives dashboard
Go to step `II. Evaluation plans` and enter a bunch of really long numbers for the `Qualitative targets` question, they should display as comma-separated numbers in the card.
N/A
---
---

CMDCT-3227: [WP] Mask Values w/ Comma for Qualitative Objective Cards

---

services/app-api/handlers/reports/archive.test.ts
services/app-api/handlers/reports/create.test.ts
services/app-api/handlers/reports/create.ts
services/app-api/handlers/reports/fetch.test.ts
services/app-api/handlers/reports/fetch.ts
services/app-api/handlers/reports/release.test.ts
services/app-api/handlers/reports/submit.ts
services/app-api/handlers/reports/update.ts
services/app-api/utils/auth/authorization.test.ts
services/app-api/utils/auth/authorization.ts

Copies work from [MCR](https://github.com/Enterprise-CMCS/macpro-mdct-mcr/pull/11575)
We have an auth utility called `hasPermissions` that verifies the requesting user has the role expected for a given request (ex: ADMIN for create banner, STATE USER for submit report, etc.)
Key changes:
- `services/app-api/utils/auth/authorization.ts` the `hasPermissions()` method is updated to optionally accept `state`. It performs different verification logic as a result.
- also added the `isAuthorizedToFetchState()` method to verify that if they are a state user, they are a state user for the requested state. Admins and other types can request any state.
CMDCT-3197
---
To verify the `create` updates (same logic as `update` and `submit`)
- With the network tab open, create a WP …

Restrict requests by assigned state for state users

---

services/app-api/utils/transformations/transformations.ts

There's an issue with SAR reports that are created from a copied over WP. The SAR Objective Progress is not auto-hydrating the Target Value textboxes. What's causing this is not because of the copy over but because of the target transformation not generating the correctly ids & labels by quarters. 
**IMPORTANT**: This issue affected the objectives of reporting period 2 only. So when testing the SAR and WP reporting, check that it is for reporting period 2.
CMDCT-3208
---
1) Sign into MFP, any state user
2) Fill out and submit a WP
- When filling out evalution plan, make sure to select yes and fill out the target quantitative targets.
3) Signout of state user and sign in as admin
4) Approve the previously made WP
5) Sign back into the state user, and copy the approve WP
7) Fill out the …

[Bugfix] SAR - Objectives Progress Copyover Hydration

---

services/ui-src/src/types/formFields.ts
services/ui-src/src/utils/forms/forms.ts

updated the `convertChoiceToEntity` function to only assign `field.key` if it exists, otherwise assign the field.id. Hopefully this fixes the targetPopulation issue where the id was showing as undefined and breaking the addEditModal
CMDCT-3244
---
- create a SAR off of a work plan that has Target Populations
- click the edit icon from the dashboard view
- the modal should appear with no errors
---
---

fix edit icon error

---

services/app-api/utils/validation/completionStatus.ts

The strangest case of this should have been broken the whole time but somehow managed to not be until the copy. 
WP Review and Submit status for State- or Territory Specific Initiatives status would show only complete when a WP copy was made. The issue was that the status did not actually run because it was trying to check for an initiativeId that only existed in dynamic modal overlay report pages. This PR adds a simple check to the conditional.
CMDCT-3250
---
- Sign into MFP, any state user
- Fill out and submit a WP
- Signout of state user and sign in as admin
- Approve the previously made WP
- Sign back into the state user, and copy the approve WP
- Go to into the copied WP, check Review and Submit.
- Check to make sure the status of State- or Territory Specific Initiatives is false
- …

[Bugfix] WP Copy Initiative Status in Review & Submit

---

services/app-api/forms/sar.json

This one turned out to be very simple, the id name in the SAR.json was missing some information to find the validation. Updated the id name and now the nested validation is working.
Shown below is the area where the validation was not firing. When user selected no in both quantitative and qualitative measures, the error wouldn't run on an empty textbox.
CMDCT-3220
---
- Sign into MFP, any state user
- Fill out and submit a WP
- When filling out evalution plan, make sure to select yes and fill out the target quantitative targets.
- Do another one for qualitative targets by selecting no
- Signout of state user and sign in as admin
- Approve the previously made WP
- Sign back into the state user, and copy the approve WP
- Fill out the copied WP, go through the approval process again
- Create …

[Bugfix] Objective Progress - Missing Nested Validation

---

services/ui-src/src/components/pages/Dashboard/DashboardPage.tsx

In IDM, states are assigned by profile, not by role. If an IDM user is a `state user` in one application (e.g. MFP) and an `admin user` in a different one (e.g. MCR), their IDM profile carries over the assigned state. Because of this, the current check in the Admin User Dashboard is sometimes ignored for that user's IDM profile assigned state. That state should be ignored / not relevant when the user is logged in as an admin.
CMDCT-2796
---
Log in as an admin and as a state user, verify that you are able to navigate to the correct reports.
N/A
---
---

CMDCT-2976: Fix Admin User Access to Reports

---

services/app-api/forms/sar.json
services/ui-src/src/components/reports/OverlayModalPage.tsx
services/ui-src/src/components/reports/ReportPageIntro.tsx

Add SMART goals instructions accordion to Objectives Progress page
CMDCT-3280
---
go to the Objectives Page of the SAR and see that the Instructions Accordion matches the figma design
---
---

Add SMART goals instructions accordion to Objectives Progress page

---

services/app-api/handlers/reports/create.test.ts
services/app-api/handlers/reports/create.ts
services/app-api/utils/constants/constants.ts
services/app-api/utils/other/other.ts

Currently our UI disabled a button when we don't want to allow the user to create multiple work plans. The API does not prevent this action, so you can circumvent the UI and create as many as you want 😱 
Open to feedback on status codes and error messaging for this situation!
CMDCT-3251
---
- Using either your browser or the MFP Postman collection, attempt to create multiple Work Plans
- In browser you can just try resending the network call multiple times
- Ensure the first one gets created. Any after that return 400.
- If you complete a WP you can then create another. Then the pattern repeats.
---
---
I tried adding a test file: `other.test.ts` and it gave many errors when I only tried to test the name formatting function. Maybe I need to mock the fetch calls even though they weren't in …

Add check for repeated work plan creation

---

services/ui-src/src/utils/forms/forms.ts

Changing the "Not applicable" option in the `Define initiative` initiative step to "HCBS infrastructure/system-level development" based on design updates.
CMDCT-3201
---
- Create a new Work Plan
The `Define initiatives` step should look like this:
---
---

CMDCT-3201: Content Changes for "Define Initiative" Step

---

services/ui-src/src/components/cards/EntityCardBottomSection.tsx
services/ui-src/src/components/cards/EntityCardTopSection.test.tsx
services/ui-src/src/components/cards/EntityCardTopSection.tsx
services/ui-src/src/components/cards/EntityStepCard.tsx

display the 2 first quarters in the reporting period for Quantitative Objective Progress in the SAR
upon completing the entity, the display of quantitative info moves to the blue section
CMDCT-3233
---
- create a WP with an objective that contains quantitative info
- create a SAR off of that WP, go to State Initiatives -> Objectives progress and you should see the 1st two quarters displaying in the quantitative objective progress card
---
---

display quarters in quantitative progress

---

services/ui-src/src/components/reports/ReportPageIntro.tsx

CMDCT-3248
---
Check headings on each page and confirm that there is an h1 heading on each page, and that the visual styling stayed the same
---
---

[MFP] WP General Info heading missing - 508 remediation

---

.github/setBranchName.sh
.github/workflows/deploy.yml
.github/workflows/destroy.yml
scripts/destroy.sh

The purpose of this pull request is to correct destroy actions for Snyk or Dependabot created branches by providing a consistent means to generate shortened stage names from autogenerated branches that may exceed Cloudformation length requirements when prefixed to services managed by Cloudformation stacks.  Additionally, this pull request adds the ability to trigger destroy actions manually against any non-protected target using any Github hosted branch.
- `GITHUB_REF` environment variable is the same as `github.ref` and includes the fully qualified path
- Destroy actions always trigger on the default branch so `GITHUB_REF`/`github.ref` would be `/refs/heads/master`
- Destroy actions know what the target is based on `github.event.ref` which is NOT the fully qualified path
- Defining …

Fix infrastructure destroy action

---

services/ui-src/src/utils/validation/schemas.ts
services/ui-src/src/utils/validation/validation.test.ts

In the field data, choice list option IDs start with the parent field ID, followed by the option ID. Therefore when we test to see if a choice is selected, we must match on the suffix of the option ID.
CMDCT-3277
---
1. Create a WP with at least one applicable target population
2. Create a SAR based on that WP
3. Navigate to the RET disenrollment page
4. Confirm that patient counts disenrolled for "other" reasons must be numeric.
n/a
---

Fix nested field validation

---

services/app-api/forms/sar.json

The sar.json file was missing two words to complete the sidebar text.
As of now no WP or SAR reports are created in prod, so there is no need to run a script to update existing forms. Existing Dev and Val reports will continue to have this typo. We can decide with product and design if we want to update those or not (the quickest way I would suggest is deleting existing dev and val reports).
Before:
After:
CMDCT-3276
---
I recommend using the postman collection to save time
- Log in as a state user 
- Create and submit a WP
- Log in as an admin user and approve that WP
- Log in as a state user and create a SAR
- Verify the first nested sidebar text shows a complete sentence (doesn't end with "in the") and matches the second screenshot above
---
---

Add missing text to sar.json

---

services/ui-src/src/components/tables/EntityStatusIcon.tsx
services/ui-src/src/components/tables/getEntityStatus.tsx

The PDF for WP copyover was showing false for the initiative statusing even when it was completed. The issue stems from the fact that the statusing code is tracking close out even when there was no close out selected. We did have tracking for that but it didn't take into account copyover. This branch fixes that conditional.
This should say "Complete": 
CMDCT-3304
---
1) Sign into MFP
2) Fill out WP & submit
3) Sign out and sign into admin
4) Approve the submitted WP
5) Sign out and sign back into user
6) Copyover WP
7) Fill out copy WP until everything is completed
8) Go to "Review & Submit" section and click "Review PDF"
9) Review the PDF to make sure the statuses are accurate.
---
--- …

WP PDF - Copyover WP Incorrect Statusing

---

services/app-api/forms/sar.json
services/ui-src/src/utils/other/parsing.test.tsx
services/ui-src/src/utils/other/parsing.ts

Fix for SAR Pdf error showing up due to 'createElementWithChildren' not being called. Added a conditional to call createElementWithChildren' when an element has children (ordered or unordered list). 
Error:
---
---

Bufgix SAR PDF page error

---

services/ui-src/src/components/export/ExportedModalDrawerReportSection.test.tsx
services/ui-src/src/components/export/ExportedModalDrawerReportSection.tsx

The PDF Transition Benchmarks table for copied reports was not showing the new quarters unless you filled some in. Once you did, it did not populate new cells in N/A columns.
This PR updates the table logic such that:
- Quarter labels are generated based on report year and period (instead of pulled from form data) to ensure we get 12 correct quarters
- Number of table cell values for a given column must be 12
- N/A columns now populate with 12 immediately if the Target population is not applicable
- Columns where the user has not yet filled in new quarters will populate remaining with "Not answered"
CMDCT-3285
---
- Create a WP
- Select "Yes" on at least one target population
- Try a mix of numbers and N/A values for fun!
- Submit and Approve the WP
- Create a new WP that copies from the …

Update PDF display logic for quarters

---

.github/branch-name-validation.sh

The branch validation script has never worked.
The logic was wrong
if branch name not valid AND branch name longer than 64 chars
The regex was invalid
"^[a-z][a-z-0-9-]*$"
(the - between z and 0 is not valid)
It was also discovered that fully qualified function names must be less than 64 characters.  For instance, if a branch name is `test`, a service name is `database`, and a function name is `seedUsers`, the fully qualified name would be `database-test-seedUsers`.  The character limit for a branch has been set to 64 characters which won't prohibit fully qualified names from throwing errors, but is longer than Snyk and Dependabot generated branch nanes.
This PR fixes this, but it also adds the ability to filter on known reserved words.  I did some digging and wasn't able to locate a …

Fix branch validation

---

tests/cypress.config.js
tests/cypress/e2e/footer.cy.js
tests/cypress/e2e/home.cy.js
tests/cypress/e2e/profile.cy.js
tests/cypress/e2e/wp/dashboard.cy.js
tests/cypress/support/commands.js

Adds cypress tests for the homepage, profile and dashboard
The password is pin to the top of the devs channel, if you are missing it.
CMDCT-3303
---
- Navigate to tests/cypress
- Run `CYPRESS_ADMIN_USER_PASSWORD='insertpasswordhere!' CYPRESS_STATE_USER_PASSWORD='Insertpasswordhere!' yarn test`
- Click e2e configuration
- Run the new tests! 
Cypress config was updated.
---

CMDCT-3303 - Add Cypress tests for homepage, profile, and dashboard

---

services/ui-src/src/components/export/ExportedEntityDetailsTable.tsx
services/ui-src/src/components/export/ExportedReportMetadataTable.tsx
services/ui-src/src/components/export/ExportedSarDetailsTable.tsx
services/ui-src/src/components/pages/Export/ExportedReportPage.tsx

`Using kebab-case for css properties in objects is not supported. Did you mean tableLayout? `
Updated css selector `"table-layout"` -> tableLayout to get rid of console warning. I also verified that the tables haven't been altered from the update. 
CMDCT-https://jiraent.cms.gov/browse/CMDCT-3364
---
1. Go to WP and SAR PDF's and verify no styling changes to the table layouts
---
---

Console Error Table Layout Fix

---

services/app-api/utils/data/data.test.ts
services/app-api/utils/data/data.ts
services/ui-src/src/utils/forms/forms.test.ts
services/ui-src/src/utils/forms/forms.ts
services/ui-src/src/utils/testing/mockEntities.tsx

When creating a work plan, the user should always see default target populations in the Define Initiatives view, regardless of whether they are applicable to the MFP as defined in the Transition Benchmarks view. 
CMDCT-3228
---
There are ~4~ 5 user flows. For the first 4 user flows, the steps are the same:
1. Log in as a state user
2. Create a work plan
3. On the Transition Benchmarks section, either create or edit existing target populations according to the details for each flow.
4. On the State or Territory Specific Initiatives section, create a new initiative.
5. Click the Edit button, and on the next screen, in the Define Initiative row, click the Edit button.
6. The expected view for target populations are detailed in each flow below.
- Skip the Transition Benchmarks section (or …

Always display default target populations in initiatives

---

services/ui-src/src/components/export/ExportedEntityDetailsOverlaySection.tsx
services/ui-src/src/components/export/ExportedModalOverlayReportSection.tsx
services/ui-src/src/components/export/ExportedOverlayModalReportSection.tsx
services/ui-src/src/components/tables/Table.tsx

The following error was displaying due to divs wrapping `tr` tags inside some of the PDF tables. 
`<tr> cannot appear as a child of <div> `
I removed the div's and updated the `tr` tags so the styling wouldn't change. Direct child `div` tags inside `tr` tags were converted to `td` tags.
Note: I think initially adding the div as a wrapper was to be able to wrap a whole entity section with this `key={`${reportType}${idx}`}` .  I removed the div and placed the key on the `tr` which only wraps the heading of the section. I think since the key is on each section header it should be enough (if its just an identifier ). I'm open to any thoughts on this.
CMDCT-https://jiraent.cms.gov/browse/CMDCT-3369
---
1. Fill out both WP and SAR reports then check the tables in the PDF against the mockup. …

Fix on TR Console Error

---

services/app-api/package.json
services/app-api/tsconfig.json
services/app-api/utils/time/time.test.ts
services/app-api/utils/time/time.ts
services/app-api/yarn.lock

We can skip a package import (and all of the resulting Snyk/dependabot noise) by invoking the built-in `Intl.DateTimeFormat` functions. This function has been fully supported in NodeJS since 13.0.
This upgrade should be safe because we are only changing the API - therefore we are not relying on browser versions or users' machine configurations. If the unit tests pass in Github's runner, and reports are created with the correct date format in this branch's ephemeral environment, we will know we are regression-free.
n/a
---
* Log in to this branch's cloudfront environment as a state user
* Create a Work Plan
* Examine the payload in the network tab when you fetch this work plan. The top-level `reportYear` property should be 2024.
* For bonus points, fill out & submit that Work Plan, then …

Remove date-fns and date-fns-tz from app-api

---

services/app-api/handlers/reports/create.ts
services/ui-src/src/components/pages/Dashboard/DashboardPage.test.tsx
services/ui-src/src/components/pages/Dashboard/DashboardPage.tsx
services/ui-src/src/components/pages/Dashboard/DashboardTable.tsx
services/ui-src/src/components/pages/Dashboard/MobileDashboardTable.tsx
services/ui-src/src/types/reportContext.ts
services/ui-src/src/utils/testing/mockReport.ts
services/ui-src/src/utils/testing/setupJest.tsx

When an WP report is approved and user selects "continue MFP Work Plan for next period", the new copied report will display this sub text dynamically displays "copied from { reportYear - reportPeriod }".
Note: isCopied logic is being set on the api side so when testing it on the frontend I'm only testing "if the subtext is displayed if isCopied is set to true"
CMDCT-https://jiraent.cms.gov/browse/CMDCT-3422
---
1. Create a WP with stateuser
2. Approve WP with admin user
3. Go back to stateuser dashboard and select "continue MFP Work Plan for next period"
4. A new "not started" WP should be generated with the copy over text under the submission name
---
--- …

[MFP]  Add Copy Over Subtext to WP Dashboard

---

.github/workflows/codeql-analysis.yml
.github/workflows/deploy.yml
.github/workflows/pull-request.yml
.github/workflows/scan_security-hub-jira-integration.yml

Update action versions that trigger deprecation warnings in workflows. These are almost all just upgrades from Node 16 to Node 20, or else contain non-breaking updates.
The code climate action needs an update as well, but the maintainer has yet to do so. They are seeking help in this [issue](https://github.com/paambaati/codeclimate-action/issues/731) from their repository. Looks like someone has responded and that change may happen soon.
---
All actions in this branch pass. No deprecation warnings (outside of the code climate action) appear.
---
---

Update deprecated action versions

---

.github/audit-account.sh
.github/workflows/audit-account.yml

This PR applies a scheduled infrastructure audit to this application which can be manually executed or be run on a cron.  For more information, see [this PR](https://github.com/Enterprise-CMCS/macpro-mdct-qmr/pull/2148)
CMDCT-3476
---
---
---

Add workflow that creates scheduled job to audit AWS account

---

services/app-api/forms/wp.json
services/ui-src/src/components/tables/EntityRow.tsx
tests/cypress/e2e/wp/form.cy.js
tests/cypress/support/form.js

It be doing what it titled friend.
CMDCT-3372
---
Note the password is the same for logging in as a state user or admin user in MFP. If you don't have the password or think its been updated, check the proj-cms-mdct-devs channel for the pinned message at the top called MDCT App Access
- Navigate to tests/cypress
- Run `CYPRESS_ADMIN_USER_PASSWORD='insertpasswordhere!' CYPRESS_STATE_USER_PASSWORD='Insertpasswordhere!' yarn test`
- Click e2e configuration
- Run the new tests! 
---
---
---

[CMDCT-3372] Add E2E test for workplan

---

services/ui-src/src/components/forms/Form.tsx

Changed disabled field color to correct gray based on figma mockup (#262626)
Before:
After:
CMDCT-https://jiraent.cms.gov/browse/CMDCT-3489
---
Log in as an admin user and view any report that has text fields that have been previously filled by a state user. Example in screenshots below.
---
---
---

Fix Disabled Field Color 

---

.github/workflows/deploy.yml
services/ui-src/src/components/pages/Dashboard/DashboardTable.tsx
tests/cypress.config.js
tests/cypress/e2e/wp/dashboard.cy.js
tests/cypress/e2e/wp/form.cy.js
tests/cypress/support/commands.js
tests/cypress/support/form.js

This adds a cypress command to make sure that any e2e test that fails can reset itself and be able to run again without having to clean anything out of the DB or start a whole new PR. It also enables the dashboard and WP e2e test to run as part of the Git Action
CMDCT-3502
---
Note the password is the same for logging in as a state user or admin user in MFP. If you don't have the password or think its been updated, check the proj-cms-mdct-devs channel for the pinned message at the top called MDCT App Access
- Navigate to tests/cypress
- Run `CYPRESS_ADMIN_USER_PASSWORD='insertpasswordhere!' CYPRESS_STATE_USER_PASSWORD='Insertpasswordhere!' yarn test`
- Click e2e configuration
- Run the new tests! 
---
---

Add ensureAvailableReport to Cypress commands

---

services/ui-src/src/components/pages/ReviewSubmit/ReviewSubmitPage.tsx

Added styling to report submit container -> mobile view of 560px wide or less 
CMDCT-https://jiraent.cms.gov/browse/CMDCT-3499
---
1. Log in as a state user and go to the Review and Submit page, then shrink the viewport below 560px wide.
2. Review PDF and Submit button should stack with 1.5rem gap. 
---
---
---

Fix Submit Container styling for Mobile View

---

services/ui-src/src/components/reports/ReportPageFooter.test.tsx
services/ui-src/src/components/reports/ReportPageFooter.tsx

* State users are allowed to make changes to report data, and admin users are not.
* Every report page is a form for report data, and the report page footer contains a submit button for that form
* Currently, when an admin user navigates from page to page, they are continually submitting and re-submitting those forms
* This fails because the API recognizes that admin users are not allowed to PUT to report endpoints
* It also fails because the API endpoint for updating reports contains a state abbreviation, pulled from the user's data. Since admin users aren't associated with a specific state, this URL ends up malformed.
* This PR replaces the footer's submit button with a simple navigation button, when it detects that the user is an admin
* Or when it detects that the form would not be …

Prevent submission of forms when the API would reject them

---

services/ui-src/src/components/modals/AddEditOverlayEntityModal.test.tsx
services/ui-src/src/components/modals/AddEditOverlayEntityModal.tsx
services/ui-src/src/components/reports/ModalDrawerReportPage.tsx
services/ui-src/src/components/reports/OverlayModalPage.test.tsx
services/ui-src/src/utils/testing/mockReport.ts

The `Report on objective progress` modal title is incorrectly showing the entity name, not the objective name. 
I also snuck in a lil' styling fix!
CMDCT-3536
---
- Create and submit a WP
- Log in as an admin user
- Approve submitted WP
- Log back in as a state user
- Create a SAR
- Navigate to the `/sar/state-or-territory-specific-initiatives` section
- Go to the **Report on objectives progress** step
You should see the objective name in the title, not the initiative name.
---
---
---

CMDCT-3536: [SAR] "Report objective progress" Modal Title

---

.github/workflows/deploy.yml

There were a few problem with the artifact upload:
- Unit tests were configuration in such a way that they would probably not upload artifacts should the tests fail (this is an unverified assumption).  Also api unit tests were not being packaged.
- Cypress and A11y test paths pointed to directories one level deeper than they were actually being stored.
- Cypress and A11y artifact name would produce a collision and fail the job, so if both failed, the slower job would not be able to upload artifacts
- No retention was set so it would default to 90 days.  I picked 14 because I wouldn't expect to need to retrieve artifacts from a build older than 2 weeks
CMDCT-3551
---
I pushed a build set to always upload artifacts.  The artifacts can be seen to be correctly publishing …

Fix Artifact Upload

---

.github/workflows/destroy.yml
scripts/destroy.sh

Add the cleanup process to the end of the destroy.sh rather than attempting to invoke it in the destroy.yml.
This should resolve failing destroys going forward
Note: this invokes main's destroy topics command, as we're setup to only allow that lambda to do the cleanup process. 
N/A
---
---
---
---

invoke cleanup at the end of .sh

---

services/app-api/handlers/reports/create.ts
services/app-api/utils/transformations/transformations.ts
services/ui-src/src/components/modals/AddEditReportModal.tsx

Deployed env: https://d1evf704f7yu4c.cloudfront.net/
- Remove `reportPeriod` from create payload
- Remove `reportPeriod` from field data schema
- Tighten up reportPeriod equalities to type check
**Feedback** do we need to modify this [add/edit SAR definition](https://github.com/Enterprise-CMCS/macpro-mdct-mfp/blob/main/services/ui-src/src/forms/addEditSarReport/addEditSarReport.json#L32-L34)? I think our edit buttons were disabled anyway 🤔 
CMDCT-3477
---
Test WP and SAR creation.
No change to app functionality. No new errors.
I created some reports on `stateuser1` if you want to verify any data from those
---

clean up non-number report period

---

services/ui-src/src/components/fields/ChoiceListField.test.tsx
services/ui-src/src/components/fields/RadioField.tsx
services/ui-src/src/components/forms/Form.tsx
services/ui-src/src/components/reports/OverlayModalPage.tsx
services/ui-src/src/utils/forms/forms.test.ts
services/ui-src/src/utils/forms/forms.ts
services/ui-src/src/utils/testing/mockForm.tsx

[Dev link](https://d158nmtni3yrdc.cloudfront.net/)
Disabled editable capabilities on Funding Source RadioList when a state user is in a 'copy over' report. 
CMDCT-[ cmdct-3487-disablefs](https://jiraent.cms.gov/browse/CMDCT-3487)
---
1. Create a WP report 
2. Create a copy over report 
3. Go into report and select an an initiative from State or Territory-Specific Initiatives
4. Edit III. Funding sources and you should only be able to access the quarters ( radio buttons should all be disabled )
---
---
---

Disable Funding Source Radio List 

---

tests/package.json
tests/yarn.lock

[Cypress changelog](https://docs.cypress.io/guides/references/changelog#13-8-0)
In version 13.7.3 cypress fixed* an issue with the vulkan warnings in CI environments. Although it's not a great solution, I'm hoping this will reduce errors and retries on our end.
*[suppressed the warning](https://github.com/cypress-io/cypress/pull/29278/files#diff-97683c9a2857a02cef5d6db17bfc7c2bb6957e10b38b1f62dfc387c6031ea2f0R76)
CMDCT-
---
[Original push to this branch](https://github.com/Enterprise-CMCS/macpro-mdct-mfp/actions/runs/8757012526/job/24035933456#step:3:101) (no changes)
[CI run after upgrade](https://github.com/Enterprise-CMCS/macpro-mdct-mfp/actions/runs/8757044196/job/24036535448#step:3:80) didn't show warning on the same test, or any
---

Upgrade cypress to resolve vulkan issue

---

services/app-api/forms/wp.json
services/app-api/utils/transformations/transformations.ts
services/ui-src/src/components/forms/Form.tsx
services/ui-src/src/utils/reports/entities.test.ts
services/ui-src/src/utils/reports/entities.ts

Changes validation for _quarterly projection_ "number" fields in the WP so that users can enter whole numbers OR percentages.
CMDCT-3541
---
**Test link: **https://d3ozpalbymoth5.cloudfront.net/
User with plans: `stateuser@test.com` / PR / Puerto Rico
1. Create a work plan and go the the State or Territory-Specific Initiatives section.
2. Add a new initiative and in the Evaluation Plan section, click "Add objective."
3. In the Add Objective modal, select Yes for "Does the performance measure include quantitative targets?"
- The quarterly objectives fields should allow user to enter any text, not just numbers. (e.g., "50%" should be a valid input)
- The validation for required should still work. 
- There should be no masking of input.
- The styling of the input should look the same as …

3541 - Change validation for quarterly projections in WP

---

services/ui-src/src/components/pages/Dashboard/DashboardPage.tsx
services/ui-src/src/types/users.ts
services/ui-src/src/utils/api/requestMethods/report.ts
services/ui-src/src/utils/auth/UserProvider.tsx

This fixes two issues:
1. the frontend of MFP does not currently account for internal users at all
2. read-only users were not being handled correctly in the admin dashboard state selection form
Changes:
- Added internal user to valid users for the frontend
- Extended read-only user check to include internal user alongside help desk user
- Changed logic related to state selection so the correct state will be selected now
n/a
---
1. Log in as internal user, navigate to dashboard, select state and WP, confirm it loads correctly.
2. Repeat the same as help desk user.
3. Repeat the same as state user to confirm no lost functionality.
n/a
---
---
--- …

Add handling for internal user

---

services/ui-src/src/components/fields/DropdownField.tsx
services/ui-src/src/forms/adminDashSelector/adminDashSelector.ts

Fix console errors and warnings on the home page
CMDCT-3413
---
**Cloudfront URL: https://d2m59pw5vafr8o.cloudfront.net/** 
1. Log in to MFP as an admin user
2. Open the console in dev tools and make sure there is no console error about invalid property `autosave`
3. Run the unit tests for Homepage. There should be no console errors and no warnings about providing `ariaLabel` to the Dropdown component.
---
---
---

3413 - Fix home page console errors and warnings

---

services/app-api/handlers/reports/approve.test.ts
services/app-api/handlers/reports/approve.ts
services/app-api/handlers/reports/archive.test.ts
services/app-api/handlers/reports/archive.ts
services/app-api/handlers/reports/fetch.test.ts
services/app-api/handlers/reports/fetch.ts
services/app-api/handlers/reports/release.test.ts
services/app-api/handlers/reports/release.ts
services/app-api/handlers/reports/submit.test.ts
services/app-api/handlers/reports/submit.ts
services/app-api/handlers/reports/update.test.ts
services/app-api/handlers/reports/update.ts
services/app-api/storage/reports.test.ts
services/app-api/storage/reports.ts
services/app-api/utils/constants/constants.ts
services/app-api/utils/dynamo/dynamodb-lib.test.ts
services/app-api/utils/dynamo/dynamodb-lib.ts
services/app-api/utils/s3/s3-lib.test.ts
services/app-api/utils/s3/s3-lib.ts
services/app-api/utils/testing/mocks/mockDynamo.ts
services/app-api/utils/testing/mocks/mockReport.ts
services/app-api/utils/testing/setupJest.ts
services/app-api/utils/types/reportContext.ts
services/app-api/utils/types/reports.ts
services/app-api/utils/validation/completionStatus.ts

**Broad strokes**
* Create a new directory for "storage" methods. Today, it will include helper methods for fetching report data stored in DynamoDB and S3. Eventually, it should include helper methods for _all_ Dynamo and S3 access. Possibly SSM access as well.
* Tweak dynamodb-lib.ts and s3-lib.ts to expose their clients directly. Eventually, the wrapper methods should be completely removed; the storage helpers will provide sufficient abstraction.
* Update all the report API endpoints to use the new storage helpers (except create).
* In some cases this replaces direct calls to dynamo, making the storage helper a clear win for readability
* In other cases this replaces internal calls to the fetch endpoint. This saves us `event` manipulation shenanigans, JSON deserialization, and usually …

Create helper methods for retrieving report data

---

services/ui-src/src/components/app/AppRoutes.test.tsx

It be titled what it be doing
CMDCT-3415
---
cd services/ui-src
yarn watchTest
hit p for the regex option and type "appRoutes"
See no console errors pop up!

[CMDCT-3415] Fix console errors in AppRoutes

---

services/ui-src/src/components/export/ExportEntityDetailsTable.test.tsx
services/ui-src/src/components/export/ExportEntityDetailsTable.tsx
services/ui-src/src/utils/reports/entities.test.ts
services/ui-src/src/utils/reports/entities.ts

Fixes display of large currency values to include commas
CMDCT-3535
---
Cloudfront: https://d67035zzzhyab.cloudfront.net/
`stateuser@test.com` has a WP and SAR with big numbers you can review
---
| Incorrect | Correct |
| --- | --- |
| $1000.00 | $1,000.00|
| $1000 | $1,000.00|
1. In a work plan, under the State or Territory-Specific Initiatives section, add a funding source. Include some numbers over 1,000 in the quarter fields.
2. After saving the funding source, the table in the card should display the large numbers in the correct format.
3. Review the PDF. The table for the funding source section should display the large numbers in the correct format.
4. Submit and approve the work plan, then create a SAR.
5. In the funding sources section, the large numbers should display in the …

[CMDCT-3535] - Fix display value for currency data

---

services/app-api/utils/testing/mocks/mockForm.ts
services/ui-src/src/components/fields/ChoiceListField.test.tsx
services/ui-src/src/components/fields/DateField.tsx
services/ui-src/src/components/fields/NumberField.tsx
services/ui-src/src/components/fields/TextAreaField.test.tsx
services/ui-src/src/components/fields/TextField.test.tsx
services/ui-src/src/components/fields/TextField.tsx
services/ui-src/src/utils/testing/mockForm.tsx

Fixing more console errors in the unit tests
CMDCT-3420
CMDCT-3418
---
Run the following test suites, notice no more console errors:
- ModalDrawerReportPage
- ModalOverlayReportPage
- ChoiceListField
- DateField
- NumberField
- TextField

[3420, 3418] Fixing more console errors

---

tests/package.json
tests/yarn.lock

Some users have `concurrently` installed on their system and some do not.
Our `test` command for cypress local uses concurrently.
By installing it in the package we eliminate the need to have it on machines.
---
- You can run cypress locally
- Run `which concurrently` to see if you have it installed already

add concurrently for cypress local

---

services/ui-src/src/components/fields/DateField.tsx
services/ui-src/src/components/fields/NumberField.tsx
services/ui-src/src/components/fields/TextField.tsx

In this [PR eliminating console errors](https://github.com/Enterprise-CMCS/macpro-mdct-mfp/pull/580/files#diff-b5bb9d5fd923df504028e2ba652e8d21568c4c273d8156111f9d8693e96783d3) we ended up removing some properties we needed, like disabled! 
This pulls out the properties we see getting to the components when props are spread, and ensures those make it
Date field with spread:
Date field without spread:
Number field with spread:
Number field without spread:
CMDCT-3646
---
Deployed url: https://d17paipffuuz1g.cloudfront.net/
- Login as `adminuser@test.com` in the deploy environment
- For Puerto Rico, verify the WP and SAR fields are disabled
- The last initiative has the maximum fields displayed (like nested ones) if you want to verify those
---

ensure fields have disabled prop for non-state users

---

services/app-api/handlers/reports/approve.test.ts
services/app-api/handlers/reports/approve.ts
services/app-api/handlers/reports/archive.test.ts
services/app-api/handlers/reports/archive.ts
services/app-api/handlers/reports/create.test.ts
services/app-api/handlers/reports/create.ts
services/app-api/handlers/reports/release.test.ts
services/app-api/handlers/reports/release.ts
services/app-api/handlers/reports/submit.test.ts
services/app-api/handlers/reports/submit.ts
services/app-api/handlers/reports/update.test.ts
services/app-api/handlers/reports/update.ts
services/app-api/storage/reports.test.ts
services/app-api/storage/reports.ts
services/app-api/utils/constants/constants.ts
services/app-api/utils/formTemplates/formTemplates.test.ts
services/app-api/utils/formTemplates/formTemplates.ts
services/app-api/utils/other/copy.test.ts
services/app-api/utils/other/copy.ts
services/app-api/utils/other/other.test.ts
services/app-api/utils/other/other.ts
services/app-api/utils/testing/setupJest.ts
services/app-api/utils/types/other.ts
services/app-api/utils/types/reportContext.ts
services/app-api/utils/types/reports.ts

This is a continuation of the work in PR #582. There shouldn't be any surprises here; we're just filling out the rest of the helper methods needed for reports. Once it is merged, there will be no direct DynamoDB or S3 access in any of the report handlers.
**Detailed list of moderately-interesting changes**
* create.test - some tests were actually testing "deeply", verifying functionality in copy.ts or formTemplates.ts. Those functions are now mocked, simplifying the tests here. The unit tests in copy.test.s, formTemplates.test.ts, and transformations.test.ts already cover their own functionality.
* create.ts - remove some deprecated parameters when calling helper methods
* update.ts - remove a check that would catch a metadata object without formTemplateId or fieldDataId. These fields are …

Add helpers for creating/updating reports and template versions

---

services/app-api/forms/sar.json
services/ui-src/src/components/accordions/AccordionItem.tsx
services/ui-src/src/components/overlays/EntityDetailsOverlay.tsx
services/ui-src/src/components/reports/DynamicModalOverlayReportPage.tsx
services/ui-src/src/components/reports/ReportPageIntro.tsx

This story started with the intention of moving one line of text above some paragraphs...and evolved into a full-fledged refactor of how text is structured on our report page intros. As you do.
I am sorry this PR looks scary.
CMDCT-3595
---
**Cloudfront link:** https://d2z5kjhukpisg4.cloudfront.net/
**User:** `stateuser@test.com`
This refactor ends up touching every page of WP and SAR, honestly. BUT it's pretty quick to visually review.
1. Look at each page of WP (the intro text before any forms) and nothing should look weird.
2. Look at each page of the SAR (the intro text before any forms) and nothing should look weird.
3. In the SAR, go to State or Territory-Specific Initiatives, click into a specific initiative, and view each step (Objectives progress, Initiatives progress, …

[CMDCT-3595] Refactor ReportPageIntro

---

services/app-api/utils/types/users.ts
services/ui-auth/libs/users.json
services/ui-src/src/types/users.ts

As it turns out, the correct IDM user role for internal users is `mdctmfp-cms-internal-user`, not `mdctmfp-internal-user`. 
n/a
---
n/a for now, but then...
- In dev, get @ntsummers1 to test it with IDM login
- In val, get @BearHanded to test it with IDM login
- In prod, get @jessabean to test it with IDM login
n/a
---
---
- ~~[ ] Design: This work has been reviewed and approved by design, if necessary~~
- ~~[ ] Product: This work has been reviewed and approved by product owner, if necessary~~
- ~~[ ] These changes are significant enough to require an update to the SIA.~~
- ~~[ ] These changes are significant enough to require a penetration test.~~
---
_convert to a different template: …

modify internal user role to match idm

---

services/ui-src/package.json
services/ui-src/src/global.d.ts

Remove references to [react-scripts, which has been removed](https://github.com/Enterprise-CMCS/macpro-mdct-mfp/pull/604)
---
- Deployed app works: https://d1se5txk52qcml.cloudfront.net/
- App runs locally
- All tests pass in CI

remove old react-scripts references

---

services/ui-src/src/forms/addEditSarReport/addEditSarReport.json

Remove break tags from modal field hint text
CMDCT-3611
---
Deployed env: https://d1y6xdxhkaqfwq.cloudfront.net/
- Log in as `stateuser@test.com`
- Go to the SAR dashboard
- Click on the create modal and inspect the hint text for "Associated MFP Work Plan" and "Reporting period"
- Verify these are newlined via paragraph instead of break tags
- DO NOT create a SAR so it's easy for others to review :)
If you test locally you can enable the SAR modal right away by commenting out the [disabler in the dashboard component](https://github.com/Enterprise-CMCS/macpro-mdct-mfp/blob/main/services/ui-src/src/components/pages/Dashboard/DashboardPage.tsx#L376)
---
- ~[ ] I have added [thorough](https://shorturl.at/aejkF) tests, if necessary~

remove br tags from add sar modal

---

services/ui-src/src/utils/statusing/getRouteStatus.ts

Currently, we're counting the "General Information" page towards the Work Plan report completion status, but that page doesn't contain any form fields, so we're filtering it out going forward.
CMDCT-3675
---
- Create a WP
- Navigate to the Review & submit page
You should not see "General Information" on the status table and you should be able to submit your report without any trouble.
N/A
---
---
---

CMDCT-3675: Removing "General Information" from Review & Submit page

---

services/ui-src/src/components/modals/AddEditEntityModal.test.tsx
services/ui-src/src/components/modals/AddEditEntityModal.tsx
services/ui-src/src/components/reports/ModalDrawerReportPage.tsx
services/ui-src/src/utils/testing/mockForm.tsx

Before:
**After:**
CMDCT-3679
---
Load up a WP
Enter the Transition Benchmarks
Mark all the defaults as a no
See the error above the benchmarks
Add a new benchmark, call it 'a'
Attempt to another add a new benchmark called 'a'
See the error appears in the modal at the same time as the one on the main page with different text.
Close the modal
Reopen and see the errors gone in the modal unless you type 'a' again.
Mark a default benchmark as a yes and see the original alert on the page is gone.
---
---

CMDCT-3679: Fix error alert on Transition page from showing all the time

---

services/app-api/forms/wp.json

Added the missing text from close-out section:
CMDCT-3684
---
Go into a WP that was copied over, to Transition Benchmarks, to Close-Out section, see that the text is on the page.
---
---
---

cmdct-3684 - add missing intro text to closeout section

---

services/app-api/serverless.yml
services/app-api/storage/reports.ts
services/app-api/utils/constants/constants.ts
services/app-api/utils/kafka/kafka-source-lib.ts
services/database/package.json
services/database/scripts/sync-kafka-2024.js
services/database/scripts/utils/dynamodb.js
services/database/scripts/utils/s3.js
services/database/yarn.lock

The unmarshaller is part of the kafka sync process, which runs when we update a DB or S3 record. Thus the easiest way to fix the malformed records is to correct the unmarshaller and re-fire all events that could have happened since the issue started (earlier this year). This PR does the following:
To fix the issue:
- Fix unmarshaller by removing options
To reprocess malformed records:
- Add trigger to kafka lambda on S3 Object Tagging
- This allows us to re-submit the records by adding a tag, as opposed to having to touch the record and possibly interfering with state users
- Move reportTables and reportBuckets constants back to constants file to fix broken kafka handler
- Add sync-kafka-2024 script to be run against each environment to re-trigger record processing for 2024
- Add dynamodb …

Fix unmarshaller and kafka handler; add script to re-run kafka sync for malformed records

---

services/ui-src/src/components/modals/CreateSarModal.tsx
services/ui-src/src/components/pages/Dashboard/DashboardPage.tsx
services/ui-src/src/utils/forms/forms.test.ts
services/ui-src/src/utils/forms/forms.ts
services/ui-src/src/utils/testing/mockEntities.tsx

Before:
After:
CMDCT-3681
---
Fill out, submit and approve a Work plan preferably with an additional other target population
Create a SAR and see in the modal only the populations you checked as applicable are checked.
After you create the SAR see that the dashboard only lists out the populations that were applicable.
---
---

[CMDCT-3681] - Update SAR Creation Modal to check only applicable populations

---

services/ui-src/src/components/pages/Dashboard/DashboardPage.test.tsx
services/ui-src/src/components/pages/Dashboard/DashboardPage.tsx

Ensure SAR error alert only shows up under the following conditions
- You are on the SAR dashboard
&&
- There is no WP ready to be associated with a SAR (meaning there is no approved WP at all, or none that are not already associated with a SAR)
&&
- There is no existing SAR that is incomplete (incomplete meaning it is not submitted or archived)
CMDCT-3647
---
Test locally
- Log in as `stateuser@test.com` and go to the SAR dashboard
- Use the `yarn db:seed` script to generate an approved WP
- Refresh the SAR dashboard and verify the error message disappears
- Create a SAR
- Verify there is still no error message
- Fill out and submit the SAR
- Verify the error message shows up on the dashboard again
---

Adjust SAR dashboard error logic

---

services/app-api/handlers/reports/create.test.ts
services/app-api/handlers/reports/create.ts
services/app-api/utils/other/other.test.ts
services/app-api/utils/other/other.ts
services/ui-src/src/components/reports/ReportProvider.tsx
services/ui-src/src/utils/reports/reports.test.ts
services/ui-src/src/utils/reports/reports.ts

When creating a SAR and associating it with a Work Plan, we will...
**Current:**
1. Find all Eligible Workplans (Ones that are approved and are not associated with a SAR)
2. Pick the newest workplan of that list
**Updated To**:
1. Find all Eligible Workplans (Ones that are approved and are not associated with a SAR **and are not archived**)
2. Pick the **oldest** workplan of that list
CMDCT-3693
---
Create 2 work plans
Fill them both out
Approve them
Create a SAR
See the SAR picked the oldest workplan of the two.
---
---

[CMDCT-3693] - Update getLastCreatedWorkPlan to return the oldest workplan thats eligible

---

services/ui-src/src/components/layout/Header.tsx
services/ui-src/src/styles/theme.ts
tests/cypress/e2e/wp/form.cy.js

The "Leave form" call to action should be marked up as a link and there should be no <button> element inside.
The "Leave form" call to action should be styled as an outline button
original:
CMDCT-3662
---
Login, create WP, enter WP and see that 'Leave form' still looks the same but is no longer a `button`.
---
---
---

Cmdct 3662 - remove button from inside link

---

services/ui-src/src/utils/state/useStore.ts

In this PR: https://github.com/Enterprise-CMCS/macpro-mdct-mfp/pull/653, the `persist` middleware was removed from the Zustand store to fix a user authentication bug. However, it's caused an issue where upon exporting a report, the report object is no longer in the store and a PDF is not able to generate properly. Here we're partializing the store to allow the report to persist across tabs.
N/A
---
- Create a report
- Export as PDF
It should load correctly for you.
N/A
---
---
---

[Bug Fix] Persist Report in Zustand Store

---

package.json
run
services/app-api/serverless.yml
src/run.ts
yarn.lock

It was noticed after the destroy action modifications, that AwsApiGateway Client Certificates were leaking and not being cleaned up.  Our previous destroy script had a specific action item to clean these certificates up, but because they had been leaking, the quota was overrun which was causing deployment issues.  
The initial effort to resolve included exploring the following:
- modifying the serverless stage destroyer to clean up certs;  this was abandonded when it was found that certs are not tagged and would have to be collected by namespace
- adding a custom resource that would be triggered by a Cloudformation stack event to clean them up
But after additional digging, it was appearing that the plugin used to manage the certs was in fact causing leaks, as each ephem would have two …

Remove client certificates and fix run script

---

services/ui-src/src/components/export/ExportedModalDrawerReportSection.test.tsx
services/ui-src/src/components/export/ExportedModalDrawerReportSection.tsx

Adds aria-labels with full-length entity names for the truncated PDF table headers. Currently only impacts the target population headings for Transition Benchmarks in the Work Plan.
CMDCT-3682
---
Link: https://d2yjt98l5zoxbx.cloudfront.net/
- Create a work plan
- Go straight to the Review & Submit section and view the PDF page.
- In the "Transition Benchmark Totals" section, the table headers for default populations should be abbreviated
- Inspect the source code for the table headers. Each `th` should have an `aria-label` attribute and it should contain the full text for the header.
---
---
---
_convert to a different template: [test → val](?expand=1&template=test-to-val-deployment.md)_ …

Format aria labels for PDF table headers

---

playwright.config.ts
tests/e2e/helpers.ts
tests/e2e/wp.spec.ts

Added helper function to archive work plans before starting the state user test

Fix WP test to start from clean slate

---

src/run.ts

The purpose of this PR is create a run wrapper that can invoke topic destruction in the topics service.  The wrapper will be invoked in the destroy step and will ensure topics are removed when ephemeral environments are destroyed.  Just like the destroy action, this will always execute against the integration branch, targeting ephems, so while this action has been tested independently, it cannot fully be exercised until it is merged into the integration environment, but I have a high level of confidence it will work as expected.
CMDCT-3797
---
To test locally
`./run delete-topics --stage [stage]`
To test in CI, this has to be merged first, and then an ephem can be stood up and destroyed.  
Once this is merged in, the topics this branch created will need to be destroyed, and this can be …

Add topic destruction to destroy mechanism

---

services/app-api/utils/types/other.ts

Add remaining US territories to backend list
CMDCT-3830
---
https://dfjaxidlcbkne.cloudfront.net/
- Log in as an admin user
- Attempt to go to the dashboard for any of the territories added
- Verify it loads and the reports fetch in the network tab returns a 200 (even if empty)
Go to MFP dev
- Repeat the above steps and verify it throws an error (400) when you attempt a territory that was added in this Pull Request
The frontend already has a full list (which is what generates the admin dropdown). I just made sure the backend had the same list.
---
---

add missing territories to state enum

---

.github/workflows/deploy.yml

I noticed an issue where Upload Report for playwright was running and failing in production even though the tests do not run in production. I think it was because of the `if: always()` condition. I modified it to be "always so long as it's not production"
[Production deploy with failed upload](https://github.com/Enterprise-CMCS/macpro-mdct-mfp/actions/runs/9877736178/job/27280595541)
CMDCT-
---
- Next time prod deploys it does not fail this step, or run it at all
---

Only run upload report in lower envs

---

services/app-api/utils/time/time.test.ts
services/app-api/utils/time/time.ts

- Use 9/3/24 as due date for Work Plans for 2024 - Period 2
- Refactor method to use more readable date strings
- Refactor to revert changes made in https://github.com/Enterprise-CMCS/macpro-mdct-mfp/pull/498 past the needed time period
- Reorganize/add unit tests
CMDCT-3771
---
2. Run `yarn db:seed` to quickly create a work plan. Since the seeder chooses a random year and reporting period, you may not get a 2024R2 on the first try.
3. Verify that the due date for a WP for 2024R2 is 9/3/24
---
---

Refactor calculate due date for Work Plans 2024 - Period 2

---

.github/workflows/destroy.yml

The order of delete is different every time. If `database` gets deleted before `app-api` the `app-api` stack fails to delete because of a dependency on S3 buckets from the `database` stack.
With this change our delete ensures app-api completes before deleting the database stack
Note: `--verify false` is necessary for CI because the `true` case is interactive. It still waits for the entire stack to delete before proceeding due to the `wait` parameter which defaults to true
---
Verify the order of events in [this destroy run](https://github.com/Enterprise-CMCS/macpro-mdct-mfp/actions/runs/9995579306/job/27628047181) against a test branch
Verify there are no stacks with the name `test-delete-me` in Cloudformation
---

Make app-api destroy first

---

.github/audit-account.sh
.github/workflows/audit-account.yml

This is a super simple change to keep the orphaned_topics job from causing a build failure when there are no orhpaned topics.
No ticket, just a fix
---
See this [workflow run](https://github.com/Enterprise-CMCS/macpro-mdct-mfp/actions/runs/10165615200) for reference.
---
---
---

Fix audit failing when there are no orphaned topics

---

tests/e2e/helpers.ts
tests/e2e/wp.spec.ts

Fixes an issue where the archive existing WPs function would time out occasionally, resulting in a flaky e2e test for the work plan.
CMDCT-3842
---
1. _In the project root_, run `yarn test:e2e tests/e2e/wp.spec.ts`
2. Try it a bunch of times
3. Nothing should fail
4. Check the build for this PR and everything should be passing

fix API request promises in the playwright test

---

services/ui-src/src/components/pages/Dashboard/DashboardPage.test.tsx
services/ui-src/src/components/pages/Dashboard/DashboardTable.tsx
services/ui-src/src/components/pages/Dashboard/MobileDashboardTable.tsx
services/ui-src/src/verbiage/pages/accordion.ts
tests/cypress/e2e/wp/dashboard.cy.js

Feedback from Kim regarding the changes to `archive`. After archiving, the dashboard should have text that says `Archived`, instead of a disabled outline button. Also missed a period in the accordion verbiage.
Also, not something that was a part of the original PR for CMDCT-3881, but the `View` button should never be disabled for admin.
CMDCT-3881
---
Login as admin, seed the db to create a workplan. Archive it and see the `Archived` text in place of the `Archive` button. Make sure styling is the same in mobile view. See that the `View` button is enabled, regardless of the status.
---
---
---
_convert to a different template: [test → val](?expand=1&template=test-to-val-deployment.md)_ | …

archived program should be text, not disabled button

---

services/ui-src/src/components/layout/Timeout.tsx
services/ui-src/src/utils/auth/authLifecycle.test.tsx
services/ui-src/src/utils/auth/authLifecycle.tsx
services/ui-src/src/utils/other/time.ts

see title
date-fns is a package we already had installed, and is a recommended swap for momentjs.
the moment package is a sub-dependency of `serverless-bundle`. we cannot remove it from yarn.lock, but hopefully this still resolves the issue.
References:
[Security issue](https://www.invicti.com/web-vulnerability-scanner/vulnerabilities/version-disclosure-momentjs/)
[MomentJS recommends using alternatives](https://momentjs.com/docs/#/-project-status/)
CMDCT-3910
---
Tests pass
- Modify the values for `IDLE_WINDOW` and `PROMPT_AT` in the src/constants.ts file to be shorter (change leading values to 1 and 0.5 or something)
- Run locally
- Let the app sit until the timeout hits
- Ensure the prompt shows up as expected
- Ensure the prompt still does the correct actions when you click on them
- …

remove implementations of momentjs

---

.github/workflows/deploy.yml
tests/e2e/sar/create.spec.ts
tests/e2e/wp/approve.spec.ts

- Reverts changes to `deploy.yml` from https://github.com/Enterprise-CMCS/macpro-mdct-mfp/pull/729
- Skips tests dependent on seeding until we come up with a better solution.
---
1. Locally, run `yarn test:e2e` or `yarn test:e2e-ui` for interactive tests
2. Verify all tests pass

Revert deploy.yml and skip e2e tests

---

services/app-api/handlers/reports/create.ts
services/app-api/utils/other/other.test.ts
services/ui-src/src/components/export/ExportEntityDetailsTable.test.tsx
services/ui-src/src/components/modals/CreateWorkPlanModal.test.tsx
services/ui-src/src/components/modals/CreateWorkPlanModal.tsx
services/ui-src/src/components/pages/Dashboard/DashboardPage.test.tsx
services/ui-src/src/components/pages/Dashboard/DashboardPage.tsx
services/ui-src/src/forms/addEditWpReport/addEditWpReport.json
services/ui-src/src/forms/addEditWpReport/resetWpReport.json
services/ui-src/src/utils/testing/mockReport.ts

Move the reset work plan button from the continue modal to the dashboard page
See ticket for more details
Dev choices:
- Removed reset logic from app-api (did I miss anything?) and had the frontend treat new and reset the same (both let you control the year and period)
- Gave reset modal the same form ids as create, but passed in `"clear": true` prop so that it would not try to hydrate the modal
- Changed test year to 2024 so I could test error alert
[Figma](https://www.figma.com/design/oOJMUZerbafZefLQQ33GwI/MFP_Playground?node-id=0-1&node-type=CANVAS&t=tpiSjk0ZXRgiHqiI-0)
CMDCT-3882
---
https://dmprc1ij4x0jj.cloudfront.net/
I’ve set up three state users so you can see different scenarios:
1. `stateuser@test.com` existing report, not complete
2. `stateuser1@test.com` no existing reports …

Move reset button to dashboard

---

services/ui-src/src/components/cards/EntityStepCard.tsx
services/ui-src/src/components/cards/TemplateCard.tsx
services/ui-src/src/components/drawers/Drawer.tsx
services/ui-src/src/components/modals/Modal.tsx
services/ui-src/src/components/pages/Dashboard/DashboardTable.tsx
services/ui-src/src/components/pages/Dashboard/MobileDashboardTable.tsx
services/ui-src/src/styles/components/button.ts
services/ui-src/src/styles/components/index.ts
services/ui-src/src/styles/components/link.ts
services/ui-src/src/styles/foundations/breakpoints.ts
services/ui-src/src/styles/foundations/colors.ts
services/ui-src/src/styles/foundations/filters.ts
services/ui-src/src/styles/foundations/fonts.ts
services/ui-src/src/styles/foundations/index.ts
services/ui-src/src/styles/foundations/lineHeights.ts
services/ui-src/src/styles/foundations/sizes.ts
services/ui-src/src/styles/styles.ts
services/ui-src/src/styles/theme.ts

[RFC](https://docs.google.com/document/d/1zyHGfboYyhncV0MXnoCNipn1xWoD8IfAS_oVK5-FExk/edit#heading=h.rz1wnztilpui)
Proposed organization of theme files. Breaking up main theme file into more atomic pieces that include foundation styles and component styles, along with their variants.
- This kind of touches every part of the app (ugh, sorry), so it will require looking around at all the pages
- Everything should look mostly the same and nothing obviously broken

Organize theme files

---

services/app-api/handlers/reports/create.test.ts
services/app-api/handlers/reports/create.ts
services/ui-src/src/components/modals/CreateWorkPlanModal.tsx

Frontend:
- Reset all component state on modal closure so that the error triggers properly on re-opening
Backend: 
- Add check to create flow that ensures unarchived report in same year and period does not exist
- Add tests
CMDCT-3985
---
(if testing locally, use `yarn db:seed` to create approved WP)
https://d1vtt2axjhiobw.cloudfront.net/
- Log in as stateuser2@test.com
- Go to WP dashboard
- Open "reset" modal
- Verify alert shows as expected (when year and period match existing report)
- Close and re-open the modal multiple times. Make sure it still works as expected
- Open the network tab
- Create a reset report in a different year and period
- Resend the network request and verify it returns a 400
please log in as admin and archive any created reports to make testing easy for other …

Improve checks for existing report

---

services/app-api/forms/wp.json

All the other items in this list have `padding` and this one had `paddingTop`. Now they are consistent.
Is this work making an ETL to fix existing reports?
CMDCT-3982
---
https://d1avl5sgzabx32.cloudfront.net/
- Log in as `stateuser@test.com`
- Enter the existing work plan
- Go to the State or Territory-Specific Initiatives Instructions page
- Note the roman numeral list under "For each initiative, recipients will be asked to provide:"
- Note all items are aligned the same
- Compare to any WP in [MFP dev](https://mdctmfpdev.cms.gov/)
---
- ~[ ] I have added [thorough](https://shorturl.at/aejkF) tests, if necessary~
---
---

Fix padding in list

---

services/ui-src/src/components/pages/Dashboard/DashboardPage.tsx
services/ui-src/src/styles/components/button.ts

This is a hotfix for a bug I noticed: the disabled buttons and links on the work plan dashboard were extremely light and do not meet accessibility contrast standards
N/A
1. Log in as a state user and create a work plan
2. Stay on the dashboard and see the disabled "Continue MFP Work Plan" and "Reset MFP Work Plan" buttons. They should be legible.
**Before**
**After**

Fix disabled state for dashboard buttons

---

services/ui-src/src/styles/index.scss

Running MFP locally we get this deprecation warning
```
ui| DEPRECATION WARNING: Sass's behavior for declarations that appear after nested
ui| rules will be changing to match the behavior specified by CSS in an upcoming
ui| version. To keep the existing behavior, move the declaration above the nested
ui| rule. To opt into the new behavior, wrap the declaration in `& {}`.
ui|
ui| More info: https://sass-lang.com/d/mixed-decls
ui|
ui|    ╷
ui| 42 │ ┌   &:visited {
ui| 43 │ │     color: inherit;
ui| 44 │ │   }
ui|    │ └─── nested rule
ui| 45 │     transition: all 0.3s ease !important;
ui|    │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ declaration
ui|    ╵
ui|     src/styles/index.scss 45:3  root stylesheet
```
As per the warning I moved the transition styling above the nested rules and the …

fix scss deprecation warning

---

services/ui-src/src/components/tables/EntityRow.tsx

There wasn't any padding between the text and edit button, which was visible when the title went long
change:
This change is viewable in all Entity Rows
CMDCT-3993
---
Create a WP, see table in the WP has padding. Create SAR, see that initiatives table has correct padding.
---
---
---

Cmdct 3993 - add padding between text and edit button in entity row

---

services/app-api/forms/sar.json
services/ui-src/src/components/app/AppRoutes.test.tsx
services/ui-src/src/components/export/ExportedReportBanner.tsx
services/ui-src/src/components/modals/CreateWorkPlanModal.tsx
services/ui-src/src/components/pages/Export/ExportedReportPage.test.tsx
services/ui-src/src/components/pages/Export/ExportedReportPage.tsx
services/ui-src/src/components/pages/Home/HomePage.test.tsx
services/ui-src/src/components/pages/ReviewSubmit/AdminReview.test.tsx
services/ui-src/src/components/pages/ReviewSubmit/ReviewSubmitPage.test.tsx
services/ui-src/src/types/reports.ts
services/ui-src/src/utils/other/time.ts
services/ui-src/src/utils/testing/setupJest.tsx
services/ui-src/src/utils/text/translate.test.ts
services/ui-src/src/utils/text/translate.ts
services/ui-src/src/verbiage/pages/sar/sar-export.ts
services/ui-src/src/verbiage/pages/wp/wp-export.ts

- Add a `translate` util that replaces any keys in `{{key}}` format within a string with defined values
- Use the util in `ExportedReportPage` with a LaunchDarkly flag
- Remove old LD flags in tests
CMDCT-3677
---
1. Create a WP and SAR.
2. Verify the headings are as expected.
3. Unit tests also provide coverage.
If we like this pattern, there are several other components where  we can use the util.
---

Add text translate util

---

services/ui-src/src/components/overlays/EntityDetailsDashboardOverlay.tsx
services/ui-src/src/components/reports/DynamicModalOverlayReportPage.tsx
services/ui-src/src/components/reports/ModalDrawerReportPage.tsx
services/ui-src/src/components/reports/ModalOverlayReportPage.tsx
services/ui-src/src/components/tables/EntityRow.tsx

Table borders for td and th cells should use the palette variable gray_light (resolve to #a6a6a6). Impacted areas:
WP: Transition Benchmarks
WP: State or Territory-Specific Initiatives page (all initiatives dashboard)
WP: individual initiative dashboard page
SAR: State or Territory-Specific Initiatives page
SAR: individual initiative dashboard page
When a table appears directly above the ReportPageFooter component (the previous/continue buttons), the table cells in the last row should not have a border. Impacted areas:
SAR: State or Territory-Specific Initiatives page
CMDCT-3983
---
compare the tables in dev (or val or prod) with this PR, see that all rows have the same border color in the WP and SAR. See that in SAR: State or Territory-Specific Initiatives page, the last row does not …

Cmdct 3983 - updates to tables

---

tests/e2e/pages/profile.spec.ts
tests/e2e/utils/fixtures/base.ts
tests/e2e/utils/pageObjects/banner.page.ts
tests/e2e/utils/pageObjects/base.page.ts
tests/e2e/utils/pageObjects/profile.page.ts

Moves some itty bitty profile tests to Playwright
CMDCT-3861
---
- From the root, run `yarn test:e2e` or `yarn test:e2e-ui` and run the profile test. 
- There should be 4 tests now instead of 2, and they should all pass

Migrate profile tests to Playwright

---

.gitignore
playwright.config.ts
tests/e2e/pages/admin.spec.ts
tests/e2e/pages/home.spec.ts
tests/e2e/pages/profile.spec.ts
tests/e2e/utils/auth.setup.ts
tests/e2e/utils/fixtures/base.ts
tests/e2e/utils/pageObjects/base.page.ts
tests/e2e/utils/pageObjects/wp/wpInitiativeDefine.page.ts
tests/e2e/utils/pageObjects/wp/wpInitiativeOverlay.page.ts
tests/e2e/wp/create.spec.ts

Sets up a workflow to store and reuse authentication for specific users (admin, state user) that can be loaded and used in our tests. This means we can avoid running a login flow before each test that involves pages behind auth, and instead navigate directly to certain areas of the app with an already authenticated user.
CMDCT-3990
---
1. From the root, run the Playwright tests with `yarn test:e2e` or `yarn test:e2e-ui`
2. Try to run all tests. They should all pass
3. Try to run individual tests. They should pass.
4. Before each/all of the tests, you should see the `utils/auth.setup.ts` file run first, as a dependency to all other tests.
---
---
---
_convert to a different template: [test …

Spike: Storing auth for playwright tests

---

services/ui-src/src/components/export/ExportedModalOverlayReportSection.test.tsx
services/ui-src/src/components/export/ExportedModalOverlayReportSection.tsx
services/ui-src/src/utils/testing/mockReport.ts

There is a bug when adding an initiative in the workplan with the topic `Other, specify`. The text that renders is `Other, specify` instead of the text the user added in the textfield. This PR fixes that bug.
CMDCT-4025
---
Create a workplan, add an initiative, select `Other, specify`, add a description, see that the added text appears beneath the Initiative name.
---
---
---

get correct initiative wp topic text to render

---

services/app-api/db/helpers.ts
services/app-api/db/options.ts
services/app-api/db/seed.ts
tests/seeds/fixtures/banner.ts
tests/seeds/fixtures/work-plan.ts
tests/seeds/helpers.ts
tests/seeds/options.ts
tests/seeds/types.ts

The seed script was erroring silently if it couldn't create a WP or SAR and would terminate the script. These updates print errors to console and leaves the script running.
Also:
- Split changing reporting period to separate year and period options
- Remember selected reporting period when script goes back to main menu
- Add "Back to menu" options when in WP and SAR submenus
---
1. Start MFP locally
2. Run `yarn db:seed`
3. Confirm WPs and SARs can be created for reporting period
4. Confirm if WPs and SARs already exist for reporting period, receive an accurate error message
---

Improve error handling in seed script

---

.github/branch-name-validation.sh
.github/workflows/pull-request.yml
.pre-commit-config.yaml

Serverless automates naming of resources based on the branch name, and long names can often overrun the automatically generated limit. We've shortened this limit before, but we're still seeing errors pop up. Shorten the length limit to 20 for all repos.
CMDCT-3700
---
checkout this branch, create a new branch that is longer than 20 characters, and make a change on your branch (e.g. change the text on a button)
run pre-commit run and you should see the error message Bad branch name detected in your terminal. A branch name under 20 characters that starts with a letter should pass this pre-commit check.
---
---
--- …

limit branch name character count to 20

---

services/ui-src/package.json
services/ui-src/src/styles/index.scss
services/ui-src/vite.config.mts
services/ui-src/vite.config.ts
services/ui-src/yarn.lock

Properly fixes #139816 
Updates SASS to 1.80.6 and migrates changes
Updates vite-tsconfig-paths from 4.3.2 -> 5.1.2 and migrates changes
---
Run the app and take a peek! Icons should show properly, data should save and load, etc.
---

Update SASS & Vite-TSConfig-Paths

---

services/ui-src/src/utils/auth/UserProvider.tsx

Garrett and I have been working on the Amplify logout issues and we think its because the call get cancelled due to the redirect happening. Amplifys signout seems to handle this redirect just fine with out it, so we're hoping by just removing that line the logout issue will be fixed!
---
Sign into MFP with IDM
Click logout in the application
Wait until you're in the IDM site and log out of that too
Navigate to mdctmfpdev.cms.gov
Click sign into MFP with IDM
If you were taken to the login screen to input your username and password, it worked!
If you were taken directly into the application, it did not work :(

Amplify V6: Remove window.location call in logout to stop cancelling cognito call

---

services/ui-src/src/components/export/ExportedModalOverlayReportSection.test.tsx
services/ui-src/src/components/export/ExportedModalOverlayReportSection.tsx
services/ui-src/src/utils/testing/mockReport.ts

Fixes a bug where an initiative's work plan topic is not displayed on the export page.
---
To recreate the original bug, you'll have to somehow get your report into a state where your initiative object in the fieldData includes `"initiative_wp_otherTopic": "",`. It is important to include the key and the empty string value. That's how we see that the ["fix" implemented here](https://github.com/Enterprise-CMCS/macpro-mdct-mfp/pull/789/files#diff-9eb44d4565acab11cf8719a06fa704a52ebafaf509478a1319abef892cc14e9fR167-R168) inadvertently introduced the bug we're seeing in prod.
1. Create a work plan and enter at least 2 initiatives on the State or Territory-Specific Initiatives page.
- Create one initiative with an MFP work plan topic from the provided radio list
- Create one initiative with an …

bugfix: display WP topic on the export page

---

services/app-api/utils/sanitize/sanitize.test.ts
services/app-api/utils/sanitize/sanitize.ts

**Note:** This is a duplicate PR from MCR: https://github.com/Enterprise-CMCS/macpro-mdct-mcr/pull/12000
The CCIC penetration testing team was able to inject HTML into the `Admin Banner` form. @benmartin-coforma investigated a potential issue with `DOMpurify` not cleaning up a string that was larger than 16KB and found a solution which is being addressed here. 
CMDCT-4227
---
N/A
---
---
---

CMDCT-4227: Address Pen Test Findings

---

services/app-api/utils/sanitize/sanitize.test.ts
services/app-api/utils/sanitize/sanitize.ts
services/database/package.json
services/database/yarn.lock
services/ui-auth/package.json
services/ui-auth/yarn.lock
services/ui-src/package.json
services/ui-src/yarn.lock

---
- CMDCT-4227: Address pen test findings
- Snyk security upgrades
| package | prior version | upgraded version|
|-|-|-|
| `package-name` | 0.0.0 | 1.0.0 |

test → val (9 January 2025)

---

services/ui-src/src/components/pages/Dashboard/DashboardTable.test.tsx
services/ui-src/src/components/pages/Dashboard/DashboardTable.tsx

While testing https://github.com/Enterprise-CMCS/macpro-mdct-mfp/pull/861, I came across a bug with how we filter out table headers, leaving out `Due date` if switching between admin and state users.
Steps to reproduce:
1. Run mfp on the `main` branch
2. Create a submitted or approved work plan with `yarn db:seed`
3. Log in as state user and view dashboard
4. See table headers are `Submission name`, `Due date`, `Last edited`, `Edited by`, and `Status`
5. Log out and log in as admin user
6. View work plans for Puerto Rico
7.  See table headers are `Submission name`, `Last edited`, `Edited by`,`Status`, and `#`
8. Log out and log in as state user
9. See table headers are `Submission name`, `Last edited`, `Edited by`, and `Status`
---
1. Run mfp locally
2. Create a submitted or approved work …

Fix how tableBody is returned

---

services/ui-src/src/components/export/ExportedReportBanner.tsx

Copying from MCR
- Add styling condition to export page header such that it only remains sticky at zooms below ~200%
- (using mobile & tablet sizing as condition)
Applies to all export pages, regardless of report type
CMDCT-4297 bonus
---
- Create a WP report
- Go to Review & Submit page and open the PDF
- At desktop width scroll up and down
- Zoom in (`Cmd` + `+`) and test at various sizes
- Banner should become fixed to top of page at around 200% zoom
This just happens to be the functionality with mobile & tablet as the condition. We may be able to tweak further if needed, but this meets the requirements of the ticket and I think is a pretty reasonable breakpoint visually.
---
~- [ ] I have added [thorough](https://shorturl.at/aejkF) tests, if necessary~
~- [ ] …

Make export page header static at 200+ zoom

---

tests/cypress/support/commands.js
tests/playwright/utils/a11y.ts
tests/playwright/utils/pageObjects/base.page.ts

Add WCAG 2.1 AA and WCAG 2.2 AA [rules to axe-core](https://www.deque.com/axe/core-documentation/api-documentation/#:~:text=the%20analysis%20again.-,axe-core%20tags,-Each%20rule%20in).
CMDCT-4342
CMDCT-4341 (same work in CARTS)
CMDCT-4336 (the same work in MCR)
---
---
---

CMDCT-4342 Add WCAG 2.1 and 2.2 axe-core rules

---

services/ui-src/src/components/app/MainSkipNav.test.tsx
services/ui-src/src/components/app/MainSkipNav.tsx

Copied from [MCR](https://github.com/Enterprise-CMCS/macpro-mdct-mcr/pull/12068)
Fix skip nav on export page so it navigates to main content instead of the (nonexistent) sidebar.
CMDCT-4299
---
- Create a MCPAR report
- Go to the Review and Submit page and click the "Review PDF"
- `Tab` to the "Skip to main content" text and hit `Return` on your keyboard
- When you hit `tab` again it should focus one of the links in the report (if filled out) or the footer (if empty new report)
- It skips over the "Download PDF" button
- If you tab backwards to the top and tab through, you'll notice it tabs over the download button before going to main content
By skipping this button, you have been sent to main content!
---
---
---

fix skip-nav in export page

---

services/app-api/db/helpers.ts
services/app-api/db/seed.ts
tests/seeds/fixtures/banner.ts
tests/seeds/options.ts

Following https://github.com/Enterprise-CMCS/macpro-mdct-mfp/pull/897, `yarn db:seed` needs to be updated. The script now can:
- Create active banner
- Create inactive banner
- Create scheduled banner
- Delete all banners
---
1. Start MFP
2. In a separate terminal window, run `yarn db:seed`
3. Verify options under `Banners` work
---

Update seed banners

---

.github/workflows/destroy.yml

Serverless needs to be prompted to remove stacks that aren't there anymore.
CMDCT-4469
---
I did the test but you have to be using AWS for mfp creds and then `serverless usage` and see the stacks that you've created. Then destroy them using the github action and then do another `serverless usage` and see that they are no longer listed.
NA
---
---
---

CMDCT-4469 updating the destroy workflow

---

services/ui-src/src/components/layout/Header.tsx

- Remove tabindex such that "Leave form" link is accessible with keyboard
CMDCT-4439
---
[Deployed env](https://d3cnu2h6tr215l.cloudfront.net/)
- Create and open any report
- Tab through the page and verify you can access the "Leave form" button
- Verify you can activate the button by hitting the return key
- Verify it returns you to the dashboard
---

a11y: allow leave form button to be keyboard accessible

---

.github/workflows/destroy.yml

We had some lingering serverless specific commands in our destroy workflow
Now this section of the workflow matches what we see in [HCBS](https://github.com/Enterprise-CMCS/macpro-mdct-hcbs/blob/main/.github/workflows/destroy.yml#L64)

remove serverless destroy commands

---

.gitignore
src/run.ts
src/write-seed-env-file.ts
tests/seeds/helpers.ts

With the CDK conversion, `API_URL` is now dynamically generated, so the key was removed from `.env`. The `yarn db:seed` script was using that key, so we need a another way to pass that value to the script. This PR creates a `.env.seed` file when you run MFP locally.
---
2. Open another terminal window and run `yarn db:seed`
3. All seed commands should work
---

Generate a .env.seed with API_URL

---

services/app-api/utils/validation/completionStatus.test.ts
services/app-api/utils/validation/completionStatus.ts

If a user copies a work plan and closes out an initiative without filling out required info, the user can't submit the work plan, but they can't go back and fill in the missing info either. This PR changes the `completionStatus` check to skip checking the required info for a closed initiative.
CMDCT-
---
2. Create a work plan, submit and approve it
3. Copy the work plan by selecting "Continue MFP Work Plan for next Period"
4. Close out an initiative without filling in missing info
5. Create another initiative for the one you're closing out
6. Fill in missing info for the other copied-over initiatives
7. Form should be submittable
PR https://github.com/Enterprise-CMCS/macpro-mdct-mfp/pull/917 fixes `yarn db:seed` which will make testing this PR easier.
---
---

Skip completion status checks for closed initiative

---

.github/workflows/scan_secrets.yaml

The latest version of gitleaks is failing in our checks. There was a [change to the allowlist](https://github.com/gitleaks/gitleaks/pull/1777) settings that is causing ours to fail. 
In the future we can look into this more, or perhaps move back to latest when it's fixed. For now lets make sure these pass and not get used to ignoring them.
Docs:
[gitleaks changelog](https://github.com/gitleaks/gitleaks/releases)
[DockerHub gitleaks tag list](https://hub.docker.com/r/zricethezav/gitleaks/tags)
---
- Verify gitleaks [passed](https://github.com/Enterprise-CMCS/macpro-mdct-mfp/actions/runs/14756637587/job/41426476569) with the locked version `v8.24.3`
- Verify gitleaks [failed](https://github.com/Enterprise-CMCS/macpro-mdct-mfp/actions/runs/14734940791/job/41358712033) with implicit latest on …

pin gitleaks version to prevent config errors

---

services/database/scripts/fix-reopen-initiative.js
services/database/scripts/sync-kafka-2024.js

Update the local table and S3 bucket locations in the `sync-kafka-2024.js` script. Update URLs in comment.
CMDCT-
---
2. In a different window, run `DYNAMODB_URL="http://localhost:4566" S3_LOCAL_ENDPOINT="http://localhost:4566" node services/database/scripts/sync-kafka-2024.js`
3. There should be no errors
Scripts in other repos after CDK migration would need similar updates.
---

Update kafka sync script

---

deployment/stacks/data.ts
deployment/stacks/ui-auth.ts
deployment/stacks/ui.ts

This change will mean that we no longer have issues destroying branches which destroys the stack.
CMDCT-4622
---
The app still works the same.
NA
---
---
---

CMDCT-4622 gets cloudfront logging to stop breaking destroys for ephemeral apps

---

services/ui-src/src/utils/forms/forms.ts

Change `autocomplete` field attribute from `one-time-code` to `off`.
This attribute is used to help assistive technology easily identify a fields purpose and help users fill often reused information (things like "email", "given-name", "street-address"). I'm not sure why "one-time-code" was used in the past, perhaps just to fill the attribute with something we knew was not needed? As such we will just use "off" for now on.
Docs:
[MDN attribute: autocomplete](https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Attributes/autocomplete)
[WCAG Criterion - 2.1 AA 1.3.5: Identify Input Purpose](https://www.w3.org/WAI/WCAG22/quickref/?showtechniques=135&currentsidebar=%23col_overview&versions=2.1#identify-input-purpose)
CMDCT-4498
---
[Deployed env](https://dqcjfjc2g320l.cloudfront.net/) …

A11y: `autocomplete` field attribute fix

---

services/ui-src/src/components/layout/Header.tsx

Make app header position static at high zoom/small screen size
Note: we have already done this same change for the Export view header https://github.com/Enterprise-CMCS/macpro-mdct-mfp/pull/885
CMDCT-4447
---
[deployed env](https://dr8d3x35p1bqo.cloudfront.net/)
- Log in as any user
- Click around few different pages and:
- Zoom in past 200% and verify the header becomes fixed to the top
- Shrink screen size to mobile or tablet at normal zoom and verify header becomes fixed to the top
Sidebar still sticks to its position lower on the page. Do we want to change this? The problem I foresee would be that it could end up behind the header if we make its positioning dynamic (if it's set to the top at tablet and mobile but you are at the top of the page it would be behind or in front of the …

Make header unsticky at small screen size/high zoom

---

services/ui-src/src/components/pages/Dashboard/DashboardPage.test.tsx
services/ui-src/src/components/pages/Dashboard/DashboardTable.tsx

Add labels for dashboard actions that give more details to assistive tech.
Copied from https://github.com/Enterprise-CMCS/macpro-mdct-mcr/pull/12188
CMDCT-4463
CMDCT-4465
---
- Run the application locally
- Run `yarn db:seed` to create an approved WP and SAR
- Navigate to /wp and /sar and check the accessible names of the buttons inside of the dashboard table to ensure that they are:
- unique
- better describe what the button does
---

Add aria-label to dashboard table buttons

---

logs/launchdarkly-flags.log
services/app-api/handlers/reports/create.test.ts
services/app-api/handlers/reports/create.ts
services/app-api/utils/other/other.test.ts
services/ui-src/src/components/modals/CreateWorkPlanModal.tsx

- Remove WP copy feature flag from code
- Remove condition preventing users from copying a report when they are still in the same period as the previous report
CMDCT-4473
---
Easiest when running locally
- Run MFP
- use `yarn db:seed` to create an approved WP
- Click the button to continue MFP WP on the WP dashboard
- Verify it creates a copied WP
[Deployed env](https://d3249eji7hebn0.cloudfront.net/)
- log in as `stateuser@test.com`
- Go to the Work Plan dashboard and click the Continue button
- Verify it creates a report for the next period
- As a courtesy to other reviewers, log in as `adminuser@test.com` and archive the new report (under Puerto Rico for `stateuser@test.com`)
Need someone with launchdarkly access to remove flag once this is in prod
---
---
---

Remove isCopyOverTest feature flag

---

services/ui-src/src/utils/validation/schemas.test.ts
services/ui-src/src/utils/validation/schemas.ts

Update frontend validation schemas for optional fields to:
- accept `null` values
- convert empty strings to `null` values
Fields where no value is entered or a previous value was removed now save as `null` instead of empty string. Is this something we need to communicate to DataConnect?
I did not update the schemas in the backend because they only receive a singular value. They do not have to determine validation to changing values. 
CMDCT-4444
---
[Deployed env](https://d18uja5w5t1kux.cloudfront.net/)
Admin user
- Log in as an admin and navigate to `/admin`
- Enter text in the banner form's Link field and then delete it
- Verify validation goes away when the field is empty
- Verify you can still submit the form when link had text entered and then removed
State user
- Run MFP locally
- …

Update optional field schemas

---

.github/setBranchName.sh
.github/workflows/dependabot-auto-merge.yml
.github/workflows/deploy.yml

Undo the removal of dependabot:
https://github.com/Enterprise-CMCS/macpro-mdct-mfp/pull/507/files
This PR reenables the following:
- Branch names for dependabot are converted to an md5sum and shortened
- Dependabot branches deploy
- Dependabot branches auto-merge assuming required checks pass
CMDCT-4378
---
Once this is merged, monitor future PRs
---
---

[CMDCT-4378] Enable dependabot automerge on success

---

.pre-commit-config.yaml

I had trouble running `tsc` on my local. If you add yarn it should use the project installed tsc and not be machine-dependent.
- Pull down this branch
- Make any file change
- Run `git commit -am "test"`
- Verify the commit hooks all run 
- Don't push :) 
Bonus: see if yours works on main
- Run `which tsc` to see if you have tsc installed
- If not, make a branch off main and do the same steps locally and see if the pre-commit hook throws an error

add yarn to pre-commit tsc command

---

.github/workflows/deploy.yml
.github/workflows/e2e-test.yml
.github/workflows/regression-test.yml

- Extracted Playwright test configuration from the deploy workflow and moved it into a shareable workflow called e2e-test.yml
- Created a new workflow called regression-test.yml that runs the e2e-test.yml workflow on a cron that runs every Monday at 7am UTC.
CMDCT-4873
---
* Run the workflow manually in Github actions
* Wait until Monday 7am UTC
* In both instances, the workflow should run without issues
---
---
---

moved playwright test logic into shared workflow

---

.github/workflows/pr-notification.yml

The pr-notification action notifies the `#mdct-integrations-channel` when a PR is opened. The notifications have been listing `Cloudfront URL: endpoint not found` because it can't find the stack name. This PR updates the stack name.
---
1. Future MFP PRs will have the Cloudfront URL populated
---
---

Update stack name in PR notification

---

services/ui-src/src/styles/components/button.ts

Add background color to outline buttons on hover
CMDCT-5033
---
[deployed env](https://d3qkfj45pmpheg.cloudfront.net/)
- Find any outline button style and hover over it
- Verify gray background appears on hover
---
---
---

CMDCT-5033: Add background color on hover to outline buttons

---

tests/playwright.config.ts

* The regression workflow we run on a schedule was not executing the tests due to an empty string which was caused by our Playwright config.
* This change only runs the webserver step if we're running the tests locally, avoiding an empty string being sent to the downstream workflow.
No related ticket as the work seemed small enough.
---
* Run the regression workflow and the deploy workflow.
* Tests should pass in deploy
* Tests should run in regression workflow, though likely some will fail since it runs unstable tests not run in deploy
* Updated the playwright.config.ts
---
---
---
_convert to a different template: [val release](?expand=1&template=val-deployment.md)_ | _[production …

Fix Regression Workflow

---

deployment/stacks/ui.ts

Bangbay found an error in the tealium code change -- tealium-tags.cms.gov wasn't whitelisted so utag.sync.js and utag.js were blocked from loading.
CMDCT-5090
---
---
---
---

whitelist tealium-tags.cms.gov

---

services/ui-src/src/components/drawers/Drawer.tsx

Move drawer header content to the drawer body definition.
Why? The drawer header (managed by chakra) sticks to the top of the drawer. When zoomed in, or on small screens, the header can take up the entire page and not let users view the rest of the drawer body (see for yourself in dev or val). By moving this content to the body, users can scroll past it and get to the form fields. The close button remains in the header so its usable at all times, at the cost of occasionally overlapping with text in the rest of the drawer.
Drawbacks:
- Can no longer view header content from anywhere in the drawer (if it's a long form)
- Close button can overlap text when scrolling
This change addresses an accessibility concern and the drawbacks noted are considered acceptable. Without this change, the …

Update drawer information organization for accessibility
