- .github/workflows/deploy.yml
- services/ui-auth/serverless.yml
---
- Cleanup ui-auth serverless
- Deploy with new ssm params to support IDM SAML
> Test -> Val

- .github/workflows/deploy.yml
- services/ui-auth/serverless.yml
val-> prod
Cognito Config
Redeployment with SAML metadata parms
---
---
---
> Val -> Prod

- .github/workflows/git-secrets.yaml
- .gitleaks.toml
- .pre-commit-config.yaml
- SECRETSCANNING.md
> Implementing secret scanning tools Gitleaks and Precommit

- scripts/destroy.sh
- Remove `yarn install` step as we don't need that right now
- Fix bucket script to empty buckets with a large amount of items
- Make stage disassociation conditional on existence
- Remove hanging log groups
Create a branch
Run destroy
Weeeeeeeeee
> Fix destroy with stuff from other apps

- services/ui-auth/libs/users.json
Adding some state users for MFP
N/A
---
---
---
> Adding state users

- .github/workflows/schedule-jira-sync.yml
Same update as applied to [MCR](https://github.com/Enterprise-CMCS/macpro-mdct-mcr/pull/11411)
Actions began working again after the update.
N/A
---
Proved in MCR
---
---
> Sec sync 1.0.3

- services/ui-src/src/components/app/AppRoutes.tsx
See description! 
N/A
---
Navigate to `/profile` or click `Manage account` to see more ✨ 
---
---
> Add Profile Page Route to MFP

- services/ui-auth/libs/users.json
> Adding / Fixing Admin Users

- services/ui-src/src/components/fields/DateField.test.tsx
- services/ui-src/src/components/fields/DateField.tsx
- services/ui-src/src/components/fields/DropdownField.test.tsx
- services/ui-src/src/components/fields/DropdownField.tsx
- services/ui-src/src/components/fields/DynamicField.test.tsx
- services/ui-src/src/components/fields/DynamicField.tsx
- services/ui-src/src/components/fields/NumberField.test.tsx
- services/ui-src/src/components/fields/NumberField.tsx
- services/ui-src/src/components/index.ts
- services/ui-src/src/components/reports/EntityProvider.tsx
- services/ui-src/src/components/reports/ReportPageWrapper.tsx
- services/ui-src/src/types/reports.ts
- services/ui-src/src/utils/autosave/autosave.ts
- services/ui-src/src/utils/forms/forms.ts
- services/ui-src/src/utils/other/checkInputValidity.ts
- services/ui-src/src/utils/other/clean.ts
- services/ui-src/src/utils/other/mask.test.ts
- services/ui-src/src/utils/other/mask.ts
- services/ui-src/src/utils/testing/fields/mockDropdownChoices.tsx
- services/ui-src/src/utils/testing/mockForm.tsx
Added Dynamic, Date, Number, and Dropdown fields. Updating masking as well from Ajaita's latest work.
MDCT-2735
---
go to /standard, see all the new fields.
---
---
> mdct-2735 fields 

- services/app-api/forms/mfp.json
- services/app-api/forms/sar.json
- services/app-api/forms/wp.json
Creating a basic `wp.json` and `sar.json` to facilitate these forms going forward.
N/A
---
---
---
> MFP Work Plan and SAR JSON (base)

- .github/workflows/scan_security-hub-jira-integration.yml
- .github/workflows/scan_snyk-jira-integration.yml
The workflow wasn't running when we wanted it to, was erroneously assigning @BearHanded instead of @kx6z, and needed to have custom field selection IDs updated.
Changes made:
- Snyk & SecurityHub workflow cron jobs updated to run daily at 6am UTC.
- Auto-assignee is now Rehman instead of Brendan.
- Custom `Application` field selection ID is now correct for this app.
- Update workflow filenames to be more descriptive.
PS - Do you like this PR? If so, you're in luck -- there's a matching one in each repo for you to review and approve!
n/a
---
n/a
n/a
---
---
> update security scan / jira integration workflows

- services/ui-src/src/utils/testing/mockLaunchDarkly.tsx
I missed a file in the previous LaunchDarkly PR 😭 
---
---
---
> Adding mockLaunchDarkly.tsx

- .github/workflows/dependabot-auto-merge.yml
- README.md
- services/ui-auth/libs/users.json
- updated readme with mfp codeclimate badges
- added dependabot workflow
- added cypress users
MDCT-2628
---
---
---
> mfp github pipeline updates

- services/app-api/handlers/banners/create.test.ts
- services/app-api/handlers/banners/create.ts
- services/app-api/handlers/banners/delete.test.ts
- services/app-api/handlers/banners/delete.ts
- services/app-api/handlers/banners/fetch.test.ts
- services/app-api/handlers/banners/fetch.ts
- services/app-api/serverless.yml
- services/app-api/utils/testing/mocks/mockBanner.ts
- services/app-api/utils/testing/setupJest.ts
- services/ui-src/src/components/banners/AdminBannerProvider.tsx
- services/ui-src/src/components/forms/AdminBannerForm.tsx
- services/ui-src/src/utils/api/requestMethods/banner.test.ts
- services/ui-src/src/utils/api/requestMethods/banner.ts
- services/ui-src/src/utils/index.ts
https://github.com/Enterprise-CMCS/macpro-mdct-mfp/assets/19439679/59c2bcec-702d-4c2d-85b7-1b27f8446cd9
MDCT-2723
---
Login as an admin
Go to the admin banner form
You don't need to fill the form out, just click create. The form won't submit due to validation not being added yet
The page will show your new banner
You can leave and come back to see its still there
You can delete it and come back to the page to see its gone!
---
---
> API Handlers - Banner Create/Delete/Fetch

- services/ui-src/src/components/tables/EntityRow.tsx
- services/ui-src/src/components/tables/EntityStatusIcon.tsx
Outdated import got into `main` 
---
---
---
> Update useStore import (Bug Fix)

- .env_example
- services/app-api/serverless.yml
- services/database/serverless.yml
- services/uploads/serverless.yml
It do what it say
MDCT-2902
---
./dev local
In a separate terminal run `DYNAMO_ENDPOINT=http://localhost:8000 dynamodb-admin`
Navigate in the browser to localhost:8001
See the tables!
Look in your local uploads folder and see theres a new local-sar-form folder in it!
.env_example was updated. Make sure you update your root .env!
---
> Add SAR Buckets and DB

- services/ui-src/src/components/pages/ReviewSubmit/ReviewSubmitPage.test.tsx
- services/ui-src/src/components/pages/ReviewSubmit/ReviewSubmitPage.tsx
- services/ui-src/src/components/reports/ReportProvider.tsx
- services/ui-src/src/components/statusing/StatusTable.test.tsx
- services/ui-src/src/components/statusing/StatusTable.tsx
- services/ui-src/src/types/reportContext.ts
- services/ui-src/src/utils/auth/UserProvider.tsx
- services/ui-src/src/utils/index.ts
- services/ui-src/src/utils/statusing/getRouteStatus.test.ts
- services/ui-src/src/utils/statusing/getRouteStatus.ts
- services/ui-src/src/utils/testing/mockReport.ts
- services/ui-src/src/utils/testing/setupJest.tsx
- services/ui-src/src/verbiage/pages/mfp/mfp-review-and-submit.ts
https://github.com/Enterprise-CMCS/macpro-mdct-mfp/assets/19439679/bdeb6fbd-28ae-453d-9258-463a75eac2fc
Theres still some snags due to validation so this page won't actually _work_ yet but you can see all the screens and move through them with a little code manipulation. Will be creating tickets for the left over work in JIRA
Tickets created in Jira:
- Update routing and statusing for State and Territory Initiative https://qmacbis.atlassian.net/browse/MDCT-2926
- Ensure submit code submits the form https://qmacbis.atlassian.net/browse/MDCT-2927
MDCT-2819
---
Create a new submission
Navigate to the Review and Submit page
Check it out! 
Hide the disabled field on the submit button to activate the modal to see that
Update line 95 to `{report?.status !== ReportStatus.SUBMITTED ? (` if you …
> [MDCT-2819] Add updated Review and Submit Page

- .env_example
See title
---
Login to MFP locally
Logout and verify it stays on `localhost:3000` instead of redirecting to test.idm.whatever
add this to your .env!
> Add post-signout-redirect to env so local stays on localhost

- services/app-api/forms/wp.json
- services/app-api/utils/types/formFields.ts
- services/ui-src/src/components/alerts/getWPAlertStatus.test.tsx
- services/ui-src/src/components/alerts/getWPAlertStatus.tsx
- services/ui-src/src/components/fields/TextField.tsx
- services/ui-src/src/components/modals/AddEditEntityModal.test.tsx
- services/ui-src/src/components/modals/AddEditEntityModal.tsx
- services/ui-src/src/components/reports/ModalDrawerReportPage.tsx
- services/ui-src/src/components/reports/ModalOverlayReportPage.tsx
- services/ui-src/src/components/reports/OverlayModalPage.tsx
- services/ui-src/src/components/tables/EntityRow.tsx
- services/ui-src/src/types/reports.ts
- services/ui-src/src/utils/forms/forms.ts
- services/ui-src/src/utils/index.ts
- services/ui-src/src/utils/reports/entities.ts
Incremental progress on State and Territory Alert Box & Initiative Empty, Incomplete, Complete tickets. 
Swap the alertbox conditional to save data.
Note: There's an issue with the text needing some formatting, currently still thinking about how to do it. 
https://github.com/Enterprise-CMCS/macpro-mdct-mfp/assets/127151429/4e9e6a6d-a0b1-4498-b5ee-6620f00057c4
**It's using not the core validation atm but will be replaced with core later**
Note: This will still require a final update once core is in, but I wanted to get the code and function in for now so that there won't be merge issues later
MDCT-2776
MDCT-2795
---
N/A
---
---
> Alertbox Conditional & EntityRow Update

- services/app-api/forms/wp.json
Text update to Transition Benchmark Strategy.
https://qmacbis.atlassian.net/browse/MDCT-2772
> Transition Benchmark Strategy - Small Text Change

- services/ui-src/src/components/export/ExportedReportBanner.tsx
- services/ui-src/src/components/layout/Header.test.tsx
- services/ui-src/src/components/layout/Header.tsx
- services/ui-src/src/components/reports/ReportProvider.tsx
- services/ui-src/src/types/states.ts
- services/ui-src/src/utils/state/useStore.ts
- services/ui-src/src/utils/testing/mockReport.ts
- services/ui-src/src/utils/testing/setupJest.tsx
https://github.com/Enterprise-CMCS/macpro-mdct-mfp/assets/19439679/0733b68f-1a59-45ba-8e71-03cb50163807
MDCT-2979
---
Create a report
See the new header and timestamp in it when you open it!
Edit a field
See the timestamp update if its a new minute (And actually saved to the DB, anything past page 4 is subject to not saving)!
---
> [MDCT-2979] Report header

- .github/workflows/scan_security-hub-jira-integration.yml
Updated security hub version from 1.0.3 to 1.0.5 and also added auto-assign to the user who is also assigned the snyk tickets
MDCT-
---
Verify new tickets are being assigned to the user in jira.
Changed sechub workflow file to update version number and add auto-assign
---
---
> Implementing SecHub updates and Auto-assign

- services/ui-src/src/components/layout/Header.tsx
Before: 
After: 
---
./dev local
Stare into the abyss that is the blue header and feel soothed at its aligned nature
> Make header treatment aligned again

- services/ui-src/src/components/overlays/EntityDetailsDashboardOverlay.tsx
- services/ui-src/src/components/reports/ModalDrawerReportPage.tsx
- services/ui-src/src/components/reports/ModalOverlayReportPage.tsx
- services/ui-src/src/components/tables/EntityRow.test.tsx
- services/ui-src/src/components/tables/EntityRow.tsx
- services/ui-src/src/utils/reports/entities.ts
Follow-up pull request to cover a few comments found here:
https://github.com/Enterprise-CMCS/macpro-mdct-mfp/pull/112
MDCT-2813
---
---
---
> MDCT-2813 (Follow-Up): Code Cleanup

- services/app-api/forms/sar.json
Updating `sar.json` to include the `entitySteps` added last week with the Initiatives Dashboard.
N/A
---
---
---
> Adding SAR Initiatives Steps

- services/ui-src/src/components/reports/ModalOverlayReportPage.tsx
- services/ui-src/src/components/reports/ReportPageFooter.test.tsx
- services/ui-src/src/components/reports/ReportPageFooter.tsx
State and Territory-Specific Initiatives:
Bottom right button should say "Review & Submit" instead of "Continue"
CMDCT-
---
See that every page (besides the review page) says 'Continue', and `State and Territory-Specific Initiatives` page says 'Review & Submit'.
---
---
> update button text

- services/app-api/handlers/reports/create.test.ts
- services/app-api/utils/other/other.ts
- services/app-api/utils/testing/mocks/mockReport.ts
- services/ui-src/src/components/reports/ReportProvider.tsx
- services/ui-src/src/utils/reports/reports.test.ts
- services/ui-src/src/utils/reports/reports.ts
- services/ui-src/src/verbiage/pages/accordion.ts
This adds some tests to the create handler as well as reduces cognitive load. Spent a little too much time on this, so finishing this out for now.
CMDCT-159
---
yarn test in services/app-api
---
> [CMDCT-159] Nicks Create API Final cleanup

- services/ui-src/src/utils/forms/forms.test.ts
We didn't add tests when writing the clear code. This fixes that! (Also matches whats being pushed to MCR)
CMDCT-2
---
yarn test
---
---
> [CMDCT-2] Add tests for resetClearProp code

- .github/workflows/scan_security-hub-jira-integration.yml
- .github/workflows/scan_snyk-jira-integration.yml
updated Both snyk and security hub workflow configurations with Jira Enterprise values
---
---
> updated to jira ent

- services/app-api/forms/wp.json
- services/ui-src/src/components/export/ExportedEntityDetailsTable.tsx
- services/ui-src/src/components/export/ExportedModalDrawerReportSection.tsx
- services/ui-src/src/components/export/ExportedReportFieldTable.tsx
- services/ui-src/src/components/export/ExportedReportMetadataTable.tsx
- services/ui-src/src/components/pages/Export/ExportedReportPage.tsx
- services/ui-src/src/types/reports.ts
- services/ui-src/src/verbiage/pages/wp/wp-export.ts
this PR address the content of the folllowing sections:
- Header ({State} MFP Program Work Plan for {2024} - {Period 1 or Period 2})
- Submission Table
- Transition Benchmark Projections
_- transition bench totals table will be addressed in a separate tkt_
- Transition Benchmark Strategy
- State & Territory Specific Initiatives Instructions
it stops at State and Territory-Specific Initiatives - I'll do that in the next PR
CMDCT-220
---
You can create a workplan and then click Review PDF to be taken to the PDF export and you should see the above items
---
---
> CMDCT-220 WP PDF

- services/ui-src/src/components/reports/ModalDrawerReportPage.tsx
**Before**
**After**
---
Create a transition benchmark
Look through them by opening the benchmark!
---
> Bugfix: Fix false showing in ModalDrawer Header

- services/ui-src/src/components/export/ExportedModalOverlayReportSection.tsx
- services/ui-src/src/components/export/ExportedReportFieldRow.tsx
- services/ui-src/src/components/export/ExportedReportFieldTable.tsx
- services/ui-src/src/components/index.ts
- services/ui-src/src/utils/other/export.tsx
get radio and textinput to display, get alert to display if needed
CMDCT-
---
---
---
> get radio and textinput to display, get alert to display if needed

- services/app-api/utils/data/data.test.ts
- services/app-api/utils/data/data.ts
> [CMDCT-3087] - Ben's Beast Mode Edit

- services/app-api/utils/other/copy.test.ts
Nothing fancy, just covering those special cases.
CMDCT-3121
---
`yarn test --coverage`
n/a
---
> Add tests for copy.ts

- services/app-api/handlers/reports/update.ts
Changing blacklist to blocklist. Improves comprehension. Eliminates bias.
CMDCT-none
---
Nothing is broken when you update a report (this is just a naming change so should be no impact)
---
---
> Change blacklist to blocklist

- services/app-api/handlers/reports/release.ts
Remove`versionControl` field data that got copied from MCR
There will be a similar version of this for SAR that will be covered in CMDCT-3015
CMDCT-none
---
Unlocking a report still works
This code was running, though had no real impact because it didn't have a matching question
---
---
> Remove code that came from mcr and does not apply to mfp

- services/app-api/handlers/reports/create.ts
- services/app-api/handlers/reports/release.ts
- services/app-api/utils/constants/constants.ts
- services/app-api/utils/formTemplates/formTemplates.test.ts
- services/app-api/utils/formTemplates/formTemplates.ts
- services/app-api/utils/other/copy.ts
- services/app-api/utils/other/other.ts
- services/ui-src/src/components/pages/Dashboard/DashboardPage.tsx
- services/ui-src/src/components/reports/OverlayModalPage.tsx
- services/ui-src/src/utils/reports/reports.test.ts
- services/ui-src/src/utils/reports/reports.ts
> main -> val (sprint #49, pt 3)

- services/app-api/forms/sar.json
- services/ui-src/src/components/overlays/EntityDetailsOverlay.tsx
- services/ui-src/src/types/reports.ts
CMDCT-58
---
1. Set up a WP, it does not need to be completely filled out, but make sure that at the very least there is one initiative created
2. Create a SAR, and navigate to "State- or Territory-Specific Initiatives" -> select an initiative -> click "Edit" for section "Initiative Progress"
3. Confirm that the UI matches what is [in the Figma](https://www.figma.com/file/oOJMUZerbafZefLQQ33GwI/MFP_Playground?type=design&node-id=2152%3A118560&mode=design&t=oywsQui0DT4v55Ac-1) and that all buttons on this page are functional
4. Confirm that the UI for other pages that utilize OverlayModal are not affected UI-wise (I. Define Initiative and IV. Close Out in initiative steps in WP)
---
--- …
> SAR - Initiative Progress

- services/ui-src/src/components/export/ExportedSectionHeading.test.tsx
add exportedSectionHeading tests
CMDCT-3159
---
---
---
> add exportedSectionHeading tests

- services/app-api/forms/wp.json
- services/ui-src/src/components/export/ExportedModalDrawerReportSection.tsx
- services/ui-src/src/components/forms/Form.tsx
- services/ui-src/src/utils/forms/forms.ts
Added aria label descriptions to required WP topics and hint on when adding Initiatives.
WP topics:
Hint:
PDF
[CMDCT-3130](https://jiraent.cms.gov/browse/CMDCT-3130)
---
---
> Required Choice Aria Labels for SR 

- services/ui-src/src/components/logins/LoginCognito.test.tsx
- services/ui-src/src/utils/forms/forms.test.ts
- services/ui-src/src/utils/other/rendering.ts
- services/ui-src/src/utils/reports/entities.test.ts
- services/ui-src/src/utils/reports/reports.test.ts
Nothing fancy, just more tests. They add up to +1.53% line coverage for ui-src.
CMDCT-3121
---
`yarn test --coverage`
n/a
---
> Add some more tests around the place

- services/ui-src/src/components/export/ExportedReportFieldTable.test.tsx
- services/ui-src/src/components/export/ExportedReportFieldTable.tsx
added tests for ExportedReportFieldTable
CMDCT-3157
---
---
---
> add exportedReportFieldTable tests

- services/ui-src/src/components/export/ExportedModalDrawerReportSection.tsx
- services/ui-src/src/components/tables/Table.tsx
- services/ui-src/src/constants.ts
Refactor code
Feel free to add on or suggest changes!
Note: this is stacked on a pdf table fix branch that is related to ticket CMDCT-3151
CMDCT-none
---
- Create a WP
- View the PDF
- Update the Transition benchmarks and refresh the pdf to see it match your changes
- Verify nothing broke
---
---
> refactor transition benchmark table

- services/app-api/forms/sar.json
CMDCT-2948
---
- Create, submit, and approve a WP (or hack)
- Create a SAR
- Verify the PRA disclosure shows up on the first page of the SAR and nowhere else
---
---
> Add PRA disclosure to first page of SAR

- services/ui-src/src/components/export/ExportedReportFieldRow.test.tsx
- services/ui-src/src/components/export/ExportedReportFieldRow.tsx
tests for the exportedReportFieldRow component
CMDCT-3156
---
---
---
> add exportedReportFieldRow tests

- services/ui-src/src/utils/testing/mockReport.ts
updated ExportedReportWrapper with a new param
CMDCT-3145
---
---
---
> ExportedReportWrapper test - add mock param to get test passing

- services/app-api/handlers/reports/create.ts
- services/app-api/handlers/reports/submit.ts
- services/app-api/handlers/reports/update.ts
- services/app-api/utils/types/users.ts
- services/ui-src/src/types/users.ts
- services/ui-src/src/utils/auth/UserProvider.tsx
- services/ui-src/src/utils/testing/mockUsers.tsx
- services/ui-src/src/utils/testing/setupJest.tsx
Cleaning up the state representative role that was brought into MFP directly from MCR, but it is not being used. 
N/A
---
N/A
N/A
---
---
> Remove State Rep Role

- services/app-api/forms/wp.json
- services/ui-src/src/components/export/ExportedEntityDetailsOverlaySection.tsx
- services/ui-src/src/components/export/ExportedEntityDetailsTable.tsx
- services/ui-src/src/components/export/ExportedEntityDetailsTableRow.tsx
- services/ui-src/src/components/export/ExportedModalOverlayReportSection.tsx
- services/ui-src/src/components/export/ExportedReportFieldTable.tsx
For the WP PDF, display closeout information if the initiative has been closed out.
https://github.com/Enterprise-CMCS/macpro-mdct-mfp/assets/127151429/97b5708e-c446-4567-8444-2799d686776d
CMDCT-3160
---
1) Sign into MFP, any state user
2) Create and fill out a WP, submit for approval
3) Sign out and sign in as adminuser@test.com.
4) Find the submitted WP and approve it.
5) Sign back into the state user and create a WP copy.
6) Go and close out one of the initiative in the copied WP
7) In the "Review & Submit" section, click "Review PDF". 
8) Your closed out initiative should show something similar to this in the PDF
---
---
> WP PDF - Closeout

- services/app-api/forms/sar.json
- services/ui-src/src/forms/adminDashSelector/AdminDashSelector.test.tsx
added tests for AdminDashSelector.tsx
CMDCT-3199
---
run yarn coverage
---
---
>  AdminDashSelector.tsx tests

- services/ui-src/src/components/app/AppRoutes.test.tsx
- services/ui-src/src/components/pages/Export/ExportedReportPage.test.tsx
- services/ui-src/src/components/pages/Export/ExportedReportPage.tsx
- services/ui-src/src/utils/testing/mockReport.ts
Increased coverage for the following components in ticket MDCT-3194. 
ExportedReportWrapper.tsx
Updated coverage:
CMDCT- https://jiraent.cms.gov/secure/RapidBoard.jspa?rapidView=5874&projectKey=CMDCT&view=detail&selectedIssue=CMDCT-3198
---
---
---
> MDCT-3194 Test Coverage - Partial

- services/ui-src/src/components/export/ExportedReportFieldTable.test.tsx
- services/ui-src/src/components/fields/TextField.test.tsx
- services/ui-src/src/components/forms/FormLayoutElements.test.tsx
- services/ui-src/src/components/reports/EntityProvider.test.tsx
added tests for FormLayoutElements and EntityProvider, TextField
CMDCT-3212
---
yarn coverage
---
---
> add test for FormLayoutElements, EntityProvider, TextField

- services/app-api/forms/sar.json
- services/app-api/handlers/reports/create.ts
- services/app-api/utils/transformations/transformations.test.ts
- services/app-api/utils/transformations/transformations.ts
- services/app-api/utils/validation/completionStatus.ts
- services/ui-src/src/components/cards/EntityCardTopSection.test.tsx
- services/ui-src/src/components/cards/EntityCardTopSection.tsx
- services/ui-src/src/components/cards/EntityStepCard.tsx
- services/ui-src/src/types/other.ts
- services/ui-src/src/utils/reports/entities.ts
Make the completion status show that green checkmark thingy that gives the happy feels instead of the red exclaimation thingy that makes you sad
https://github.com/Enterprise-CMCS/macpro-mdct-mfp/assets/19439679/34715f60-04de-4056-8d0f-5705c6b50b8e
Things I'd like to do at a later time
- Fix up how completionStatus matches fieldData to form templates for initiatives. Too many for loops. Way too complex.
- Validation for choicelists in the initiatives isn't showing validation correctly
- Breakup evaluationPlan and fundingSources extraction to separate functions for cleaner tests
- Write more tests for the different objective card scenarios (what data has to show and when)
- Remove the unused data we don't need from workplan thats being pass to the SAR
- Confirm whether completionStatus …
> Make completion status work for dynamicModalOverlays

- services/ui-src/src/components/reports/ModalDrawerReportPage.test.tsx
> Add modalDrawerReportPage tests

- services/ui-src/src/components/reports/DrawerReportPage.test.tsx
> Add tests for DrawerReportPage

- services/ui-src/src/components/reports/StandardReportPage.test.tsx
> Update standard report page tests

- services/app-api/forms/wp.json
- services/ui-src/src/components/export/ExportedModalDrawerReportSection.test.tsx
- services/ui-src/src/forms/addEditWpReport/addEditWpReport.json
- services/ui-src/src/utils/testing/generalInfoMockForm.tsx
- services/ui-src/src/utils/testing/mockFullReportJSON.tsx
- services/ui-src/src/verbiage/pages/accordion.ts
- services/ui-src/src/verbiage/pages/home.ts
- services/ui-src/src/verbiage/pages/wp/wp-dashboard.ts
These content changes were made in a pairing session with Kim and Natalie. These changes affect the MFP home page, WP dashboard, WP General Information page, and the WP Transition Benchmarks page. 
CMDCT-
---
Two possible ways to test this, choose whichever works for you. 
1. [Follow the Figma](https://www.figma.com/file/oOJMUZerbafZefLQQ33GwI/MFP_Playground?type=design&node-id=0-1&mode=design&t=bynymBWZC8cVMffM-0) to confirm content changes made to the following pages:
MFP Home Dashboard
MFP Submission Dashboard
Add WP modal
General Information
Transition Benchmarks Projections
Report Transition Benchmarks by population drawer
Add other target population modal
Edit other target population modal
Delete other target population modal
<br>
2. Follow the table to confirm content changes made …
> MFP WP Content Changes - 01/30

- services/ui-src/src/utils/reports/entities.test.ts
- services/ui-src/src/utils/reports/entities.ts
Adding a dollar sign to funding sources values on the `III. Funding sources` step for an initiative.
CMDCT-3226
---
- Create a WP
- Navigate to the initiatives dashboard
Go to step `III. Funding sources` and fill in this step, the numbers should have a dollar sign on the card.
N/A
---
---
> CMDCT-3226: [WP] Display Values w/ Dollar Sign for Funding Sources Cards

- services/ui-src/src/components/reports/StandardReportPage.test.tsx
> Like actually make the standardreportpage test submission tho

- services/ui-src/src/utils/other/rendering.test.tsx
> Add prettifychoices test

- services/ui-src/src/components/reports/ModalOverlayReportPage.tsx
- services/ui-src/src/components/reports/ReportPageWrapper.test.tsx
- services/ui-src/src/components/statusing/StatusTable.test.tsx
- services/ui-src/src/utils/statusing/getRouteStatus.test.ts
- services/ui-src/src/utils/testing/mockForm.tsx
- services/ui-src/src/utils/testing/mockReport.ts
> Write ReportPageWrapper tests

- services/ui-src/src/components/pages/Dashboard/DashboardPage.tsx
- services/ui-src/src/forms/addEditSarReport/addEditSarReport.json
Content updates for the `Add new MFP SAR submission` modal:
CMDCT-3232
---
- Create, fill, and submit a WP
- Log in as an admin
- Approve that WP
- Log back in as a state user
- Create a new SAR
You should see the updated content.
---
---
> CMDCT-3232: Add New SAR Modal (Content Update)

- services/app-api/handlers/reports/create.test.ts
- services/app-api/handlers/reports/create.ts
- services/app-api/utils/constants/constants.ts
- services/app-api/utils/other/other.ts
Reverts Enterprise-CMCS/macpro-mdct-mfp#435
> Revert "Add check for repeated work plan creation"

- services/ui-src/src/components/cards/EntityStepCard.tsx
Added an aria label to the x label for objectives and funding sources card
CMDCT-3247
---
There are two places to check for this: the WP objective card and the WP funding sources card
Confirm that you can see an aria-label "Delete" present when you inspect the x button
---
---
> [MFP] WP Objective Card - 508 Remediation

- services/app-api/forms/sar.json
- services/ui-src/src/components/cards/EntityStepCard.tsx
- services/ui-src/src/components/export/ExportEntityDetailsTable.tsx
- services/ui-src/src/components/export/ExportedEntityDetailsOverlaySection.tsx
- services/ui-src/src/components/export/ExportedEntityDetailsTable.tsx
- services/ui-src/src/components/export/ExportedOverlayModalReportSection.tsx
- services/ui-src/src/components/export/ExportedRETTable.tsx
- services/ui-src/src/components/export/ExportedReportFieldTable.tsx
- services/ui-src/src/components/export/ExportedReportMetadataTable.tsx
- services/ui-src/src/components/export/ExportedSarDetailsTable.tsx
- services/ui-src/src/components/export/ExportedSectionHeading.tsx
- services/ui-src/src/components/pages/Export/ExportedReportPage.tsx
- services/ui-src/src/forms/addEditSarReport/addEditSarReport.json
- services/ui-src/src/verbiage/pages/sar/sar-export.ts
SAR PDF styling cleanup
1. Centered content container
2. Changes to header color.
3. Update spacing between sections
4. Fixed tables breaking out of container
CMDCT-https://jiraent.cms.gov/browse/CMDCT-3215
---
---
> SAR PDF Styling Cleanup Pt 1

- services/ui-src/src/components/forms/Form.tsx
- services/ui-src/src/styles/theme.ts
CMDCT-3246
---
Confirm that the following places now have the correct color of `--chakra-colors-palette-gray_medium`. There are two easy-ish ways to test this. 1) In the spots where I have updated the color value, locally update the value to something starkly different (such as red), and confirm that I have edited the expected spots. 2) Inspect the CSS while running the app via cloudfront or pulling + running the branch locally. There are 8 spots that are updated. 
---
---
> [MFP] Color contrast - 508 remediation

- services/app-api/forms/sar.json
- services/app-api/forms/wp.json
- services/ui-src/src/components/export/ExportedModalOverlayReportSection.test.tsx
- services/ui-src/src/components/export/ExportedSectionHeading.test.tsx
- services/ui-src/src/components/export/ExportedSectionHeading.tsx
- services/ui-src/src/components/pages/Export/ExportedReportPage.tsx
- services/ui-src/src/utils/testing/mockForm.tsx
- services/ui-src/src/utils/testing/mockFullReportJSON.tsx
- services/ui-src/src/verbiage/pages/overlays.ts
As title
CMDCT-3225
---
Confirm all instances of "State- or Territory-Specific Initiatives" is replaced with "State or Territory-Specific Initiatives"
---
---
> [MFP] Global content change: State or Territory-Specific Initiatives

- services/app-api/forms/sar.json
- services/ui-src/src/components/reports/StandardReportPage.tsx
Adding the `Review PDF` button and its corresponding hint text to the RE&T sections of SAR.
CMDCT-3275
---
Create a SAR, verify that these sections are rendering as expected and the button navigates to `/sar/export`
N/A
---
---
> CMDCT-3275: Adding "Review PDF" Button to RE&T Sections

- services/app-api/forms/sar.json
- services/app-api/forms/wp.json
- services/app-api/utils/transformations/transformations.ts
- services/ui-src/src/components/export/ExportEntityDetailsTable.test.tsx
- services/ui-src/src/components/export/ExportedModalOverlayReportSection.test.tsx
- services/ui-src/src/components/reports/ReportPageIntro.tsx
- services/ui-src/src/utils/testing/mockFullReportJSON.tsx
- services/ui-src/src/verbiage/pages/accordion.ts
- services/ui-src/src/verbiage/pages/sar/sar-dashboard.ts
- services/ui-src/src/verbiage/pages/sar/sar-export.ts
- services/ui-src/src/verbiage/pages/wp/wp-alerts.ts
as title!
CMDCT-
---
Follow the [Figma](https://www.figma.com/file/oOJMUZerbafZefLQQ33GwI/MFP_Playground?type=design&node-id=2186-39323&mode=design&t=tGbsectUs8UXCn0X-4) to confirm all content changes in SAR + SAR admin have been addressed
---
---
> SAR Content Changes

- services/ui-src/src/components/reports/ReportPageIntro.tsx
Some code didn't make it into dev, causing a rendering bug. Fixed here
steps to repro bug: "I entered all of the WP data manually, I did not select any `Target Populations`, and when I navigate to the `Recruitment, Enrollment, and Transitions` pages, I’m getting this error"
CMDCT-
---
---
---
> SAR Content Changes - Bug Fix

- .pre-commit-config.yaml
- README.md
- postman/MFP.postman_collection.json
- postman/MFP.postman_environment.json
- postman/README.md
See title
---
- Follow readme
This PR contains the same collection and environment shared in slack on 2/27
---
---
> Add postman folder with collection, environment, and instructions

- services/app-api/utils/types/reportContext.ts
- services/ui-src/src/components/alerts/Alert.tsx
- services/ui-src/src/components/alerts/ErrorAlert.tsx
- services/ui-src/src/components/forms/AdminBannerForm.tsx
- services/ui-src/src/components/pages/Dashboard/DashboardPage.tsx
- services/ui-src/src/components/reports/ReportProvider.test.tsx
- services/ui-src/src/components/reports/ReportProvider.tsx
- services/ui-src/src/types/reportContext.ts
- services/ui-src/src/verbiage/errors.ts
See https://github.com/Enterprise-CMCS/macpro-mdct-mfp/pull/480
> cmdct-3282 (brax's version)

- services/ui-src/src/components/pages/ReviewSubmit/AdminReview.test.tsx
- services/ui-src/src/components/pages/ReviewSubmit/AdminReview.tsx
- services/ui-src/src/components/pages/ReviewSubmit/ReviewSubmitPage.test.tsx
- services/ui-src/src/components/pages/ReviewSubmit/ReviewSubmitPage.tsx
- services/ui-src/src/verbiage/pages/sar/sar-review-and-submit.ts
- services/ui-src/src/verbiage/pages/wp/wp-review-and-submit.ts
This is a dupe of #490 just needed to fix the branch name. 😭
> #3377 Review and Submit page console errors

- services/app-api/utils/time/time.test.ts
- services/app-api/utils/time/time.ts
Update to WP Due date submission
CMDCT-https://jiraent.cms.gov/secure/RapidBoard.jspa?rapidView=5874&projectKey=CMDCT&view=detail&selectedIssue=CMDCT-3398
---
Log in and view WP report dashboard.
---
---
> Update WP Submission Due Date

- services/app-api/forms/sar.json
Changes the number field validation in the **Number of HCBS participants (including MFP participants) admitted to a facility from the community, by length of stay and age group section** to `numberOptional` so the optional fields do not fail validation at the submit report step.
CMDCT-3530
---
1. Log in as a state user and create a work plan for **period 2** of the report year.
2. Fill out, submit, and approve the WP.
3. Create a SAR from that work plan.
4. In the SAR, go to the **Number of HCBS participants admitted to a facility from the community, by length of stay and age group** section (`/sar/recruitment-enrollment-transitions/number-of-hcbs-participants-admitted-to-facility-from-community`)
5. Leave some of the number fields blank, and then go to the Review and Submit page.
6. See …
> Update validation for optional fields in SAR

- services/topics/handlers/createTopics.js
- services/topics/handlers/deleteTopics.js
- services/topics/libs/topics-lib.js
- services/topics/package.json
> Topics refactor

- scripts/destroy.sh
Need the serverless cli to successfully invoke a lambda.
N/A
---
---
---
---
> Destroy Install Deps before topic handling

- scripts/destroy.sh
Get deps from root for sls invoke
N/A
---
---
---
---
> Destroy action dependencies

- services/ui-src/src/components/alerts/Alert.tsx
- services/ui-src/src/components/export/ExportedModalOverlayReportSection.tsx
- services/ui-src/src/components/pages/Dashboard/DashboardPage.tsx
- services/ui-src/src/components/reports/DynamicModalOverlayReportPage.tsx
- services/ui-src/src/components/reports/ModalOverlayReportPage.tsx
- services/ui-src/src/verbiage/pages/wp/wp-alerts.ts
Correct:
https://jiraent.cms.gov/browse/CMDCT-3411
https://jiraent.cms.gov/browse/CMDCT-3532
---
3532: Create a new WP or edit a WP that does not have all required initiatives listed. In the alert banner, see that the bullets in the list are pulled slightly to the right of the paragraph text.
3411: Log in as a state user
Create a new work plan
Go to the State and Territory Specific Initiatives section (and then the specific State and Territory Specific Initiatives sub-section nested under that)
View the console to see the errors
---
---
--- …
> cmdct-3411 and 3532 - MFP UI bugs

- .github/workflows/scan_snyk-jira-integration.yml
Creates tickets for major version updates only
> Updated snyk-scan version

- .env_example
- services/app-api/forms/wp.json
- services/app-api/handlers/templates/fetch.test.ts
- services/app-api/handlers/templates/fetch.ts
- services/app-api/package.json
- services/app-api/serverless.yml
- services/app-api/utils/s3/s3-lib.test.ts
- services/app-api/utils/s3/s3-lib.ts
- services/app-api/utils/types/other.ts
- services/app-api/yarn.lock
- services/ui-src/src/components/cards/TemplateCard.tsx
- services/ui-src/src/components/pages/Home/HomePage.tsx
- services/ui-src/src/utils/api/requestMethods/getTemplateUrl.test.ts
- services/ui-src/src/utils/api/requestMethods/getTemplateUrl.ts
- services/ui-src/src/utils/index.ts
- services/ui-src/src/verbiage/pages/accordion.ts
- Add the download functionality the MCR has for "templates". I believe this can be further refined to be more agnostic to any files, but this should get us through the door.
- Remove the placeholder links for the template in the WP creation page and within the WP until building s3 downloads within those locations can be setup.
One used to be here!
Another used to be here:
CMDCT-3578
---
The template file is uploaded on the deployed branch. You should be able to download the help file for WP.
https://d1lcm6jiic8gg3.cloudfront.net/
The help has been uploaded to each env's bucket. Should just need to merge through and validate.
New env var TEMPLATE_BUCKET. Copy it from the .env_example.
---
---
_If either of the following are true, notify the team's ISSO (Information System Security …
> [CMDCT-3578] - Download Help File PDF

- .github/workflows/deploy.yml
The [code-climate action](https://github.com/paambaati/codeclimate-action) we use recently had an [upgrade to node 20](https://github.com/paambaati/codeclimate-action/issues/731). That was one of the lingering Node 16 actions across our apps so I'm taking this opportunity to bump actions across our apps.
CMDCT-3577
---
All actions pass and there are no warnings about Node 16 actions! 🎉 
No code changes
---
> Bump codeclimate action version

- services/ui-src/src/verbiage/pages/help.ts
**Before**
**After**
CMDCT-3579
---
Log in as a state user or admin user
Go to the get help page in the top right.
---
---
> [CMDCT-3579] Remove accordion items on the help page

- services/app-api/forms/sar.json
**Before**
**After**
CMDCT-3537
---
Create a work plan/SAR
Enter the SAR
Navigate to Additional Achievements
Resize the broswer See the new list in desktop and mobile view
---
---
> [CMDCT-3537] Fix spacing on SAR additional achievements list items

- services/ui-src/src/components/logins/LoginCognito.tsx
Main features: Hitting enter submits the form. Error messages look sharper. Inputs are spaced out nicely. Maybe you mess up and get a nice new error back. Maybe you decide to use the keyboard's enter function with the correct login inputted and you get sent to the homepage? I'm not saying this is like the invention of the wheel but its certainly more impressive then the invention of the thatched roof.
**Before:**
**After**:
---
./dev local
Enter in some login details.
Login is updated yo. 🤷 
---
Trust me.
---
> The 10 Minute Dev Login Experience Care Package

- .pre-commit-config.yaml
This check will run every commit, ensuring that the branch name won't cause any issues* in during AWS deployment.
*Some issues are still possible. The length check may not be exactly correct; 30 characters is a guess we may need to revise later. It may also be possible to create a branch name containing a reserved word, which some AWS services can object to.
My least favorite aspect of this change is the lack of in-band feedback. If a developer creates a branch with a name that contains capital letters, for example, their first commit to that branch will get a console error like this one. It's not super informative, and there aren't any good ways to give hints as to _why_ the `Don't commit to branch` check failed. No matter how informative the comments are in .pre-commit-config.yaml, they …
> Add precommit check for branch names

- package.json
- scripts/deploy.sh
- serverless-compose.yml
- services/app-api/serverless.yml
- services/topics/package.json
- services/topics/serverless.yml
- services/topics/yarn.lock
- services/ui-auth/serverless.yml
- services/ui-src/serverless.yml
- services/uploads/serverless.yml
- yarn.lock
Deploy with [serverless compose](https://www.serverless.com/framework/docs/guides/compose)
- add serverless-compose.yml to define our services and their dependencies
- add `@serverless/compose` package
- remove unused packages from root and redundancies from service directories
- remove warmup plugin
- update serverless invoke statements to use `aws lambda invoke` instead
- update variable references to use `params` from serverless instead of `cf:` outputs
- update deploy script to run from root, using serverless compose
| | w/o compose | with compose |
|----|----|-----|
| Clean deploy | 27:54  |  17:48  |
| Re-deploy no changes | 8:33  | 5:30  |
| Re-deploy no changes (2) | 8:10 | 5:31  |
CMDCT-3588
---
No changes to app functionality or deployed env.
Compare deploy times in this branch …
> Set up serverless compose

- services/app-api/utils/validation/checkInputValidity.ts
- services/app-api/utils/validation/schemaMap.test.ts
- services/app-api/utils/validation/schemaMap.ts
- services/ui-src/src/components/fields/CheckboxField.tsx
- services/ui-src/src/components/reports/ReportProvider.tsx
This is a very simply fix thankfully - We hadn't kept up the changes we've recently made to the validation in the ui and told the API about those changes. The API didn't know what a validInteger was and so I've ported those rules as well as all the other updated rules over so we should have much tighter control on whats being submitted.
**Values submitted for RE&T Page:**
https://github.com/Enterprise-CMCS/macpro-mdct-mfp/assets/19439679/e872d24f-1d19-4e33-b153-0915d850e295
**Heading Before:**
**Heading After:**
CMDCT-3596
CMDCT-3597
---
Create a workplan -> Submit -> Approve -> Create a SAR
Test inputs for validIntegers in the RE&T fields
Checkout the final RE&T Page to see the smaller header for the Other section!
---
---
> [CMDCT-3596/3597] - Fix SAR RE&T Page submissions and heading size

- services/app-api/handlers/reports/fetch.test.ts
These tests weren't adding any value, and they interfered with other tests when moved to other parts of the file. Given they aren't adding anything, let's remove them!
|  File                  | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s |
| -------------- | -------------- | -------------- |  -------------- |  -------------- | -------------- | 
// with tests
fetch.ts                |   87.87 |     62.5 |     100 |   87.87 | 33,64-68,92
// without tests
fetch.ts                |   87.87 |     62.5 |     100 |   87.87 | 33,64-68,92
CMDCT-3245
---
> Remove tests that don't add value

- services/app-api/forms/sar.json
- services/app-api/forms/wp.json
- services/ui-src/src/components/reports/ReportPageFooter.test.tsx
- services/ui-src/src/components/reports/ReportPageFooter.tsx
Sneaking in a small refactor to reduce unnecessary nested `<div>` tags and delete unused code in the footer component.
---
**Cloudfront link:** https://d3enky33yiekmt.cloudfront.net/
User: `stateuser@test.com`
1. Log in as a state user and navigate through **both** a WP and a SAR and verify that the "Previous" and "Continue" buttons work and look as expected. 
2. Do the same as an admin user.
_Note:_ You may see some variation between spacing above the footer compared to what is currently in production. I did this on purpose to get closer to what is defined in Figma, but need to refactor some additional pages in the future to remove padding/margin in some areas where it doesn't need to exist.
---
---
_If either of the following are true, notify the team's ISSO (Information System Security …
> Refactor ReportPageFooter with less HTML

- tests/cypress.config.js
- tests/cypress/e2e/sar/sar.cy.js
Hot fix to skip tests that keep failing PRs and require a lot of re-runs
---
- Run the cypress tests
- The SAR tests should not run
> Skip flaky SAR test for now

- tests/cypress.config.js
Using vite deploys to localhost and local cypress tests point at 127.0.0.1, and somehow that doesn't work. Update to use localhost. 
N/A
---
Run these test locally.
---
---
---
> Local Cypress: Use localhost

- services/ui-src/src/components/accordions/InstructionsAccordion.tsx
- services/ui-src/src/verbiage/pages/accordion.ts
Remove all `<br>` tags and use paragraph in place of span when possible
(sorry the videos are not embedded but they were too small so please open them in a new tab)
|       | WP | SAR |
| --- | --- | ---- |
|  Admin  |  https://github.com/Enterprise-CMCS/macpro-mdct-mfp/assets/57802560/12581b64-3cfe-44cd-9513-64ed909fd90e |  https://github.com/Enterprise-CMCS/macpro-mdct-mfp/assets/57802560/fbcc2db0-c443-459f-8cb0-04f472f1818b |
|  State  |  https://github.com/Enterprise-CMCS/macpro-mdct-mfp/assets/57802560/28996425-3546-4ff6-8c9a-17c6621ea525 |  https://github.com/Enterprise-CMCS/macpro-mdct-mfp/assets/57802560/df150be0-61e5-48a9-ab96-ff6158979e7c |
How to fix space between span and admin instructions 🤔 
I wasn't sure how to get the link into the paragraph without span because the p tag …
> Update accordion content and styling to be semantic html(er)

- .env.tpl
- run
- Remove `URL` env from template. It isn't referenced anywhere in the codebase.
- Remove pragma comments when using `--update-env` flag.
---
1. Run `./run local --update-dev` to update your local .env and start MFP
2. Verify there are no pragma comments in `.env`
3. Verify MFP works as normal
`URL` env variable is also defined in [CARTS](https://github.com/Enterprise-CMCS/macpro-mdct-carts) and [MCR](https://github.com/Enterprise-CMCS/macpro-mdct-mcr) and appears unused.
> Remove unused URL env variable

- services/ui-src/src/verbiage/pages/accordion.ts
**Before:**
State User
Admin
**After:**
State User
Admin
CMDCT-3860
---
Go to the SAR dashboard as an admin and as a state user!
---
---
> [CMDCT-3860] - Remove help link from SAR Dashboard accordion

- services/app-api/forms/sar.json
- services/ui-src/src/components/forms/Form.tsx
- services/ui-src/src/components/forms/FormLayoutElements.tsx
Currently there are two paragraphs under the heading of the RET pages
- Remove the second sentence of this section completely until we have the Help File from BO's. (In this section, provide information for the specified period. ~~For more information see the User Guide and Help File.~~)
- Remove the Bolded name of the page that started paragraph two (This is redundant copy that does not make sense for accessibility). (see screenshots for example)
- Combine the two paragraphs in this section. (Labeled p)
Feedback was received that it is difficult to distinguish between sections in the RET pages. 
- Please add a grey (color-gray-light #A6A6A6) line between sections in all RET pages that have multiple sections. i.e. quarter one/quarter two, institutions, Residences etc.) 
[New …
> Cmdct 3683 - add divider lines to RET pages

- services/ui-src/src/utils/state/useStore.ts
This is a replicated PR from MCR: https://github.com/Enterprise-CMCS/macpro-mdct-mcr/pull/11738
CMDCT-3669
---
- Log into MFP
- Navigate away from the app, visit Google or whatever page you want
- Wait (at least) 30 minutes
- Navigate back to <F{
You should be prompted to log back in.
N/A
---
---
---
> CMDCT-3669: User Authentication Bug

- services/ui-src/yarn.lock
Resolves a version of braces by letting yarn regen the references. Prior version was flagged.
N/A
---
---
---
---
> Snyk align braces and json5

- services/ui-src/src/components/cards/EntityCardTopSection.tsx
- services/ui-src/src/components/cards/EntityStepCard.tsx
- services/ui-src/src/components/export/ExportedEntityDetailsOverlaySection.tsx
- services/ui-src/src/components/export/ExportedModalDrawerReportSection.tsx
- services/ui-src/src/components/export/ExportedModalOverlayReportSection.tsx
- services/ui-src/src/components/export/ExportedOverlayModalReportSection.tsx
- services/ui-src/src/components/export/ExportedReportFieldTable.tsx
- services/ui-src/src/components/export/ExportedReportWrapper.tsx
- services/ui-src/src/components/export/ExportedSectionHeading.test.tsx
- services/ui-src/src/components/export/ExportedSectionHeading.tsx
- services/ui-src/src/components/pages/Export/ExportedReportPage.test.tsx
- services/ui-src/src/components/pages/Export/ExportedReportPage.tsx
- services/ui-src/src/types/reports.ts
- services/ui-src/src/utils/testing/mockReport.ts
- services/ui-src/src/verbiage/pages/sar/sar-export.ts
- services/ui-src/src/verbiage/pages/wp/wp-export.ts
- Update headings in report PDF view for WP and SAR
- Calculate child heading levels from parent
- Add `headingLevel` to components and define `HeadingLevel` type
- Update and add unit tests
CMDCT-3678
---
1. Start MFP
2. Create a WP and SAR (use `yarn db:seed`)
1. Login as stateuser at [https://d7jgww7pwtt4z.cloudfront.net/](https://d7jgww7pwtt4z.cloudfront.net/)
2. WP and SAR have already been created
3. Navigate to `Review PDF` button for both WP and SAR
4. Verify tags match hierarchy defined in [doc](https://docs.google.com/document/d/1gPWBOTqFyzsZZdyD6h3absIxZmkHmfLWEocwdKG_N4A/edit#heading=h.lwh6luwjoym6) 
6. On Chrome, you can use a HTML visualization extension to highlight heading tags. Example with HTML Visual Validation:
---
---
> Refactor PDF report headings

- services/app-api/utils/constants/constants.ts
This Kafka Topic needs a new name.
n/a
---
n/a
n/a
---
---
---
> modify kafka topic name

- run
- services/app-api/serverless.yml
- services/database/serverless.yml
- services/topics/serverless.yml
- services/ui-auth/serverless.yml
- services/ui-src/serverless.yml
- services/ui/serverless.yml
- services/uploads/serverless.yml
- src/run.ts
CMDCT-
The pull request introduces additional tags to each serverless service, which for the moment will largely appear as a noop change for most individuals, but it does pave the groundwork for future work items such as deploying multiple distinct projects into a single AWS account while avoiding conflicts.
But for the purpose of this PR, the main change is that destroy operations better target resources, and the `run destroy` command can now target specific services.
CMDCT-3642
---
This was tested in one environment by executing the destroy workflow against an ephem using the branch the changes were applied to.  It was also tested running from a workstation against a single service ('ui-src').
To destroy a single service, execute the following from a workstation:
`./run destroy --stage …
> improve tagging

- services/app-api/handlers/banners/create.test.ts
- services/app-api/handlers/banners/delete.test.ts
- services/app-api/handlers/banners/fetch.test.ts
- services/app-api/handlers/reports/approve.test.ts
- services/app-api/handlers/reports/archive.test.ts
- services/app-api/handlers/reports/create.test.ts
- services/app-api/handlers/reports/fetch.test.ts
- services/app-api/handlers/reports/release.test.ts
- services/app-api/handlers/reports/submit.test.ts
- services/app-api/handlers/reports/update.test.ts
- services/app-api/handlers/templates/fetch.test.ts
- services/app-api/utils/kafka/kafka-source-lib.test.ts
- Use spies for tests that intentionally output console messages
CMDCT-3825
---
1. cd to `macpro-mdct-mfp/services/app-api`
2. Run `yarn coverage`
3. Verify tests pass and coverage is unaffected
4. Verify console messages are gone
> Use spies for console output in tests

- services/topics/handlers/listTopics.js
- services/topics/libs/topics-lib.js
- services/topics/serverless.yml
- src/run.ts
The purpose of this pull request is to create a Lambda function, with an associated CLI runner action, that is able to query Kafka for all topics related to the project, or all topics related to the stage, which are active in BigMAC.  An addition to this work item, will be adding to the weekly infrastructure audit, a report which indicates all topics that have been orphaned.  Using this report, and the delete-topics runner action, topic clean up will be significantly simplified.  
CMDCT-3798
---
The run wrapper is configured to point to the `main` integration branch, since this will be the target of the audit action.  As such this can be tested in a few ways:
- Alter the run.src file to call this branch rather than main
- From services/topics, issue `sls invoke --stage topic-audit …
> Topic audit

- .github/audit-account.sh
- .github/workflows/audit-account.yml
This PR takes previous work, namely an idle Lambda function who's sole purpose is to query BigMAC for topics related to a given project (which can be filtered down to the stage), and finds the deltas between resources with stage names, and topic namespaces.  
Things to note:
- This compares STAGES to topic namespaces, meaning it only looks for tagged resources.
- This does not compare topics to branch names, only to deployed stacks.  
- If a Cloudformation stack is orphaned from a branch, it will still show up in the ci_inactive report.
- This audit will always execute against the Lambda function deployed to the integration branch.
CMDCT-3799
---
See [this workflow](https://github.com/Enterprise-CMCS/macpro-mdct-mfp/actions/runs/10062469695).
A step at the beginning of the workflow …
> Audit topics

- services/app-api/handlers/reports/approve.ts
- services/app-api/handlers/reports/archive.ts
- services/app-api/handlers/reports/create.ts
- services/app-api/handlers/reports/release.ts
- services/app-api/handlers/reports/submit.ts
- services/app-api/handlers/reports/update.ts
- services/app-api/utils/validation/completionStatus.ts
- services/app-api/utils/validation/completionValidation.ts
- services/app-api/utils/validation/validation.ts
- services/ui-src/src/components/banners/AdminBannerProvider.tsx
- services/ui-src/src/components/fields/NumberField.tsx
- services/ui-src/src/components/forms/AdminBannerForm.tsx
- services/ui-src/src/components/reports/ReportProvider.tsx
- services/ui-src/src/utils/auth/UserProvider.tsx
- services/ui-src/src/utils/other/clean.ts
- src/run.ts
Changes to this PR are related to an issue with ESLint, see this Slack thread for more info: https://coforma.slack.com/archives/C03GZ934P17/p1722461487969829
N/A
---
---
---
---
> ESLint Fix

- package.json
- tests/e2e/helpers.ts
- tests/e2e/pages/admin.spec.ts
- tests/e2e/pages/help.spec.ts
- tests/e2e/pages/home.spec.ts
- tests/e2e/pages/profile.spec.ts
- yarn.lock
Migrate accessibility tests from Cypress to Playwright for:
- Home page
- Admin page
- Profile page
- Help page
CMDCT-3862
---
1. Run `yarn test:e2e` or `yarn test:e2e-ui`
2. Verify all e2e tests pass
---
> Add e2e accessibility tests

- .github/workflows/scan_security-hub-jira-integration.yml
I didn't see any new features that would be helpful for us. The biggest change seems to be allowing you to link issues, but we usually just link an epic and leave it at that.
References:
[Confluence upgrade guide](https://confluenceent.cms.gov/pages/viewpage.action?spaceKey=MDSO&title=Security+Hub+v2+Upgrade+Steps)
[README with available tags](https://github.com/Enterprise-CMCS/mac-fc-security-hub-visibility/blob/v2/README.md)
CMDCT-
---
---
---
---
> Update macfc security hub github action

- services/ui-src/src/components/tables/EntityRow.tsx
Align content along entity row to center of row
BEFORE:
AFTER:
CMDCT-3980
---
- Pull up [this branch](https://d2s5d3ui53dos6.cloudfront.net/) alongside [MFP dev](https://mdctmfpdev.cms.gov/) and follow these steps in both
- Enter any report
- Go to the Transition Benchmark page
- Verify the status icon, population name, and edit button are center aligned, both before and after completing them (if the benchmark projection is incomplete then the midpoint of the population name and the red message to complete it should be center aligned)
- Go to the State or Territory-Specific Initiatives page
- Verify the same things along the row are center aligned, both before and after completing them
- Enter an initiative
- Verify the same things are aligned, both before and after completing them
Verify …
> adjust entity row alignment

- README.md
Completing the work started [here](https://github.com/Enterprise-CMCS/macpro-mdct-mfp/pull/692)
CMDCT-2550
---
View readme
---
- ~[ ] I have added [thorough](https://shorturl.at/aejkF) tests, if necessary~
- ~[ ] I have manually tested this PR in the deployed cloud environment~
> add project goals to readme

- tests/e2e/utils/archive.ts
- tests/e2e/utils/fixtures/wp.ts
- tests/e2e/utils/pageObjects/base.page.ts
- tests/e2e/utils/pageObjects/wp/wpInitiativeDefine.page.ts
- tests/e2e/utils/pageObjects/wp/wpInitiativeEvaluation.page.ts
- tests/e2e/utils/pageObjects/wp/wpInitiativeFunding.page.ts
- tests/e2e/utils/pageObjects/wp/wpInitiativeOverlay.page.ts
- tests/e2e/utils/pageObjects/wp/wpInitiativesDashboard.page.ts
- tests/e2e/utils/pageObjects/wp/wpInitiativesInstructions.page.ts
- tests/e2e/utils/pageObjects/wp/wpReviewAndSubmit.page.ts
- tests/e2e/utils/pageObjects/wp/wpTransitionBenchmarkProjections.page.ts
- tests/e2e/utils/pageObjects/wp/wpTransitionBenchmarkStrategy.page.ts
- tests/e2e/wp/create.spec.ts
Adds an e2e test for creating and submitting a work plan. Utilizes the page object model to split up the various pages of the work plan, as well as dynamically creating pages in areas like the State and Territory-Specific Initiatives.
CMDCT-3858
---
1. Run the Playwright tests `yarn test:e2e` or `yarn test:e2e-ui`
2. Run the "Creating a New Work Plan" test specifically. Notice that it is further serialized (as in, run one after the other) into "create" and "fill and submit."
3. Ideally, run the test more than once and ensure that it always passes. Trying to avoid flakiness!
- I am not 100% committed to the POM as the way to write these tests. It's possible it won't serve us that well in the long run or is more complex that it needs to be for what few tests we are likely to write. But, for …
> Playwright test for creating and submitting a WP

- services/app-api/package.json
- services/app-api/yarn.lock
- services/database/package.json
- services/database/yarn.lock
- services/ui-auth/package.json
- services/ui-auth/yarn.lock
Addressing snyk PRs:
https://github.com/Enterprise-CMCS/macpro-mdct-mfp/pull/773
https://github.com/Enterprise-CMCS/macpro-mdct-mfp/pull/774
> update aws-sdk dependencies

- package.json
- yarn.lock
I think this fixes the failures on our main ¯\\(°_o)/¯
> update playwright test

- services/ui-src/src/components/statusing/TableRow.test.tsx
- services/ui-src/src/components/statusing/TableRow.tsx
Fixes a bug where resizing the viewport to a mobile size on the Review & Submit page produces an error and the page does not render.
Took the opportunity to do a little refactoring so I could write a unit test for the viewport resizing.
https://github.com/user-attachments/assets/d53c2466-7d57-4232-a153-9a697940c885
---
1. Start a work plan
2. Go to Review & Submit page
3. Resize the window to be very smol, and back to big again.
4. You should not see any console errors, and the page should render as expected
> Return component JSX instead of calling function

- services/database/package.json
- services/database/yarn.lock
Takin' care of snyk in one PR
N/A
---
Log in to MFP and make sure nothing is broken? That report data is saved to the db.
> knock out these aws-sdk upgrades

- services/ui-src/package.json
- services/ui-src/src/utils/auth/UserProvider.tsx
- services/ui-src/yarn.lock
Amplify v6 IDM auth flow fix
snyk-y
> Main -> Val 

- services/ui-src/src/components/app/App.tsx
- services/ui-src/src/components/layout/Header.test.tsx
- services/ui-src/src/components/layout/Header.tsx
- services/ui-src/src/components/menus/Menu.test.tsx
- services/ui-src/src/components/menus/Menu.tsx
Stumbled upon some prop drilling which I believe had no benefit. This removes it, simplifies context access, and adds a test!
---
Tests pass
Logout still works as a user
> Remove unnecessary prop drilling

- services/database/package.json
- services/database/yarn.lock
Consolidating snyk PRs #818 and #819 and adding `client-dynamodb` update while we're in there
N/A
> Update `@aws-sdk` dependencies

- services/ui-src/src/components/pages/Dashboard/DashboardTable.tsx
- tests/e2e/wp/create.spec.ts
Adds test for resubmitting a work plan
CMDCT-3860
---
- run the playwright tests
- they should pass
> CMDCT-3860: Playwright test for resubmit WP

- .github/PULL_REQUEST_TEMPLATE/test-to-val-deployment.md
- .github/PULL_REQUEST_TEMPLATE/val-to-prod-deployment.md
- services/database/package.json
- services/database/yarn.lock
- services/ui-src/package.json
- services/ui-src/src/components/app/App.tsx
- services/ui-src/src/components/export/ExportedModalOverlayReportSection.test.tsx
- services/ui-src/src/components/export/ExportedModalOverlayReportSection.tsx
- services/ui-src/src/components/layout/Header.test.tsx
- services/ui-src/src/components/layout/Header.tsx
- services/ui-src/src/components/menus/Menu.test.tsx
- services/ui-src/src/components/menus/Menu.tsx
- services/ui-src/src/components/pages/Dashboard/DashboardTable.tsx
- services/ui-src/src/utils/testing/mockReport.ts
- services/ui-src/yarn.lock
- tests/e2e/wp/create.spec.ts
---
- Remove unnecessary prop drilling
- Playwright test for resubmit WP (CMDCT-3860)
- Bug fix: display WP topic on PDF export page
| package | prior version | upgraded version|
|-|-|-|
| `date-fns` | 2.28.0 | 2.30.0 |
| `vite` | 5.4.8 | 6.0.0 |
| `@aws-sdk/client-dynamodb` | 3.667.0 | 3.693.0 |
| `@aws-sdk/client-s3` | 3.667.0 | 3.693.0 |
| `@aws-sdk/lib-dynamodb` | 3.667.0 | 3.693.0 |
> main -> val

- services/app-api/handlers/templates/fetch.test.ts
- services/app-api/handlers/templates/fetch.ts
- services/app-api/utils/types/other.ts
- services/ui-src/src/components/pages/Home/HomePage.tsx
Adds the SAR help file link to state user home page
CMDCT-4240
---
1. Log in as a state user
2. On the home page, click the link that for "User Guide and Help File" in the SAR template card.
3. After a couple of seconds, it should open a PDF in a new tab.
> [CMDCT-4240] Add SAR help file download

- services/app-api/serverless.yml
Fix cypress tests after Serverless v4 update
---
---
---
---
> Fix cypress tests after Serverless v4 update

- .env.tpl
add dummy aws keys to .env.tpl for run local
CMDCT-
---
---
---
---
> add dummy aws keys to .env.tpl for run local

- run
- services/app-api/serverless.yml
Two minor fixes from Serverless v4 upgrade caught on other MDCT apps
CMDCT-
---
---
---
---
> Two minor fixes from Serverless v4 upgrade caught on other MDCT apps

- run
- services/app-api/serverless.yml
- services/uploads/serverless.yml
Adding config for s3 bucket
CMDCT-4279
---
Look and see that this s3 bucket is versioned and has blocked access
NA
---
---
---
> CMDCT-4279 - adds correct config for s3 bucket

- run
- services/ui/serverless.yml
- src/run.ts
- src/slsV4BucketPolicies.ts
S3 Bucket fixes for Serverless V4 and making S3 not serve a website as CloudFront does that
CMDCT-4312
---
Open the deployed website and verify it loads https://d2hveysfnz8hlj.cloudfront.net/
---
---
---
> S3 Bucket fixes for Serverless V4 and making S3 not serve a website as CloudFront does that

- .github/workflows/scan_security-hub-jira-integration.yml
Old ubuntu being retired. Let's get the latest version!
CMDCT-4335
---
Run the Github Action once it's merged like so:
NA
---
---
---
> CMDCT-4335 upgrading ubuntu for security hub jira integration

- services/ui-src/src/components/menus/Sidebar.tsx
Accessibility fix: There shouldn't be a header in the sidebar.
---
Create a workplan, see that there is no visual change to the sidebar and that there is no header component
---
---
---
> change header to text component

- .github/CODEOWNERS
> Update CODEOWNERS to add Bangbay!

- services/database/scripts/fix-reopen-initiative.js
- services/database/scripts/utils/s3.js
This script will reopen a closed initiative so a user can edit the initiative information again.
CMDCT-
---
2. Create an approved Work Plan with `yarn db:seed`
3. Copy the WP by selecting "Continue MFP Work Plan for next Period"
4. Close out an initiative in this new WP
5. Run `DYNAMODB_URL="http://localhost:4566" S3_LOCAL_ENDPOINT="http://localhost:4566" node services/database/scripts/fix-reopen-initiative.js {{reportId}}`. You can get the `reportId` by inspecting the Network tab for `localstack/reports/WP`.
6. Leave the form and return to the same report. The initiative should be reopened. Go to close out the initiative again and your previously entered closeout info should be there.
This is a workaround until …
> Add a script to reopen a closed initiative

- services/app-api/package.json
- services/app-api/utils/auth/authorization.test.ts
- services/app-api/utils/auth/authorization.ts
- services/app-api/yarn.lock
Its been reported in MFP and MCR that users are not seeing fields be saved when entering data. I've noticed this too while working locally. During my investigation, I found that the CognitoJwtVerifier was sending a call but timing out after 1.5 seconds. CognitoJwtVerifier is part of the aws-jwt-verify package, which actually has received this complaint a few times and has increased the timeout from 1.5 to 3 seconds in the latest 5.0.0 update. They also added the ability to increase the timeout further, noting that you might need to do this based on cold server instances. I've updated the timeout to 6 seconds. This is high, intentionally high. I've run through the application and the longest time for a response back I've had was 4.15. This doesn't seem like a good solution overall, but if …
> [CMDCT-4441] Authentication Timeout Fix

- deployment/README.md
- deployment/deployment-config.ts
A couple quick things to make a fix to https://jiraent.cms.gov/browse/CMDCT-4535 easier.
CMDCT-4535
---
NA
---
---
---
> adds a couple changes to make bootstrapping easier

- tests/playwright/pages/home.spec.ts
- tests/playwright/pages/profile.spec.ts
- tests/playwright/utils/pageObjects/base.page.ts
Playwright accessibility tests were not waiting long enough to actually test the page contents.
- Slight cleanup of a few specs
CMDCT-4665
---
- Pull down branch
- Navigate to /tests
- Run yarn test:e2e-ui
- In the Playwright UI, run all tests, they should pass
Also, if you look at the playwright action for this PR, they have all passed.
> CMDCT-4665 Add wait to playwright accessibility tests

- .github/workflows/deploy.yml
- .github/workflows/destroy.yml
- .github/workflows/update-code-json.yml
- code.json
ShareIT compliance is required
CMDCT-4692
---
See that this worked:
https://github.com/Enterprise-CMCS/macpro-mdct-mfp/actions/runs/15307935765
Also feel free to check out code.json in the project root now.
NA
---
---
---
> CMDCT-4692 ShareIT Compliance

- .github/workflows/create-main-to-val-pr.yml
- .github/workflows/create-val-to-prod-pr.yml
This is a follow-up to https://github.com/Enterprise-CMCS/macpro-mdct-mfp/pull/956. After merge to `main`, the release PR (https://github.com/Enterprise-CMCS/macpro-mdct-mfp/pull/955) updated only with the latest commit. Adding a `fetch-depth` value to retrieve the full git log history.
---
1. After merging this PR, https://github.com/Enterprise-CMCS/macpro-mdct-mfp/pull/955 should update with a complete commit log
---
---
> Add fetch-depth to checkout

- .github/workflows/create-main-to-val-pr.yml
- .github/workflows/create-pr.yml
- .github/workflows/create-val-to-prod-pr.yml
Add labels to release PRs so they stand out a little more and are filterable.
---
Future release PRs will be labeled automatically.
---
---
> Add label to release PRs

- services/ui-src/src/styles/theme.ts
add mdct prefix to css variables: [override theme config](https://v1.chakra-ui.com/docs/styled-system/theming/theme?scroll=true#config)
CMDCT-4843
---
login and inspect the page, see that the css variables have the prefix --mdct
---
---
---
> cmdct-4843 add css variable prefix

- package.json
- services/app-api/db/custom.d.ts
- services/app-api/db/helpers.ts
- services/app-api/db/seed.ts
- services/app-api/package.json
- services/app-api/tsconfig.json
- services/app-api/yarn.lock
- tests/seeds/custom.d.ts
- tests/seeds/helpers.ts
- tests/seeds/options.ts
- yarn.lock
Fixes `yarn db:seed` command.
- Declare `dotenv` module
- Removed packages from `app-api` that are installed in root
- Refactor seed commands to DRY
- Fix types not being loaded into tests
---
2. Run `yarn db:seed`
3. Create a WP and SAR
4. Create a banner
---
---
> Refactor db:seeds, remove unused packages

- .github/workflows/deploy.yml
- package.json
- tests/package.json
- tests/playwright.config.ts
- tests/playwright.md
- tests/playwright/work-plan.spec.ts
- tests/yarn.lock
- Tagged flaky tests with the @flaky flag
- Updated deploy.yml workflow to honor the @flaky and @probation tags
- Updated deploy.yml to cache the browser install to speed up the tests
- Updated commands so that tests can be run locally based on the tags
- Updated readme documentation to instruct on howto run tests locally based on the tags
- Updated the Playwright config so that it waits up to 3 mins for local test env to be provisioned
CMDCT-4862
---
1. Run `test:e2e-stable` locally
2. Run `test:e2e-stable-ui` locally
3. Check the Playwright tests in the deploy workflow, all tests should be passing
* Two banner tests will fail when the tests are run locally, they were broken locally before these changes so it is out of scope for this story and will be investigated and remediated in a …
> Cmdct 4862 stabilize e2e tests

- .github/workflows/pull-request.yml
- .pre-commit-config.yaml
- services/app-api/package.json
- services/app-api/utils/formTemplates/formTemplates.test.ts
- services/app-api/utils/formTemplates/formTemplates.ts
- services/app-api/yarn.lock
- services/ui-src/package.json
- services/ui-src/src/components/accordions/AccordionItem.tsx
- services/ui-src/src/components/accordions/FaqAccordion.tsx
- services/ui-src/src/components/export/ExportedModalOverlayReportSection.tsx
- services/ui-src/src/components/menus/Menu.tsx
- services/ui-src/src/utils/api/providers/ApiProvider.tsx
- services/ui-src/yarn.lock
- tests/yarn.lock
- Add pre-commit hooks for TypeScript in root, `app-api`, and `ui-src` 
- We normally don't find out about TS failures until deploy
- Use hooks locally only
- Update `typescript` package in `app-api` and `ui-src` to match the version used in app root
- Update `@types/node` package in `app-api`, `tests`, and `ui-src` to match the version used in app root
- Fix some type errors
- Ignore `TS2590: expression too complex` errors for now as not sure how to fix them
---
1. Check out `main`
2. In root, `app-api`, and `ui-src`, run `tsc --noEmit`
3. You should see several errors
4. Check out this branch
5. In root, `app-api` and `ui-src`, run `yarn install` then `tsc --noEmit`
6. You should see no errors
---
---
> Add TypeScript pre-commit hooks

- package.json
- tests/package.json
- tests/yarn.lock
- Addresses https://github.com/Enterprise-CMCS/macpro-mdct-mfp/security/dependabot/151
- Security alert is for `form-data` which is a transitive dependency of `@cypress/request` -> `cypress`
- Updated `cypress` from `13.8.0` to `13.17.0` to cascade down the other updates needed
---
1. PR passes CI/CD
---
---
> Update Cypress version to address form-data security alert

- deployment/prerequisites.ts
- deployment/stacks/parent.ts
Gets run local working post vpc endpoint introduction 
CMDCT-4961
---
Check if ./run local works
It should :)
NA
---
---
---
> CMDCT-4961 - gets run local working with vpc endpoint

- .eslintrc.yaml
- .github/workflows/regression-test.yml
- tests/package.json
- tests/playwright.config.ts
- tests/playwright/utils/auth.setup.ts
- tests/playwright/utils/consts.ts
- tests/playwright/utils/login.ts
- tests/playwright/utils/pageObjects/adminHome.page.ts
- tests/playwright/utils/pageObjects/stateHome.page.ts
- tests/yarn.lock
* Fixed the regression workflow but updating permissions
* Put the hard coded values for exp headers into consts that appeared in the auth util and some tests
* Added an override in our linting rules so that the tests can add console outs for debugging failing tests without having to add the exception inline which adds additional line noise in the code
* Added dev dependency on "amazon-cognito-identity-js": "^6.3.15", for handling headless cogntio auth
* Added several fallbacks where if headless auth fails in any way, we attempt to auth using the UI
CMDCT-4958
---
* Run the playwright tests - console output should confirm it works
* I verified that the UI fallback works by hard coding incorrect Cognito values
---
---
_If either of the following are true, notify the team's ISSO …
> added headless auth

- .github/workflows/audit-account.yml
CMDCT-
---
[Update audit-account.yml to fix list-topics error](https://github.com/Enterprise-CMCS/macpro-mdct-mfp/commit/f30556a2c9b1cb2ccea3dc4fdf7893c339c3851a)
---
---
---
> Update audit-account.yml to fix list-topics error

- .github/workflows/pr-notification.yml
- package.json
- yarn.lock
A harmless change as an excuse to create a PR to test that this fix works: https://github.com/Enterprise-CMCS/macpro-mdct-mfp/pull/1018
CMDCT-5045
---
1. After opening this PR, Cloudfront URL is populated in the PR's post to `#mdct-integrations-channel`.
---
---
> [CMDCT-5045] Update stack name and output key in pr-notification.yml

- .github/buildVars.sh
- .github/wafController.sh
- .github/workflows/deploy.yml
- .github/workflows/destroy.yml
- .github/workflows/git-secrets.yml
- .github/workflows/post-deploy-slack-notification.yml
Several of the files have gotten out of alignment between repos. This gets them matching without any controversial changes. Those will come later :)
CMDCT-5080
---
There should be no detectable differences in the apps.
---
---
---
> CMDCT-5080 aligns many .github files to other repos

- deployment/constructs/dynamodb-table.ts
- deployment/constructs/lambda-dynamo-event.ts
- deployment/constructs/lambda.ts
- deployment/constructs/waf.ts
- deployment/stacks/topics.ts
- src/runner.ts
Sync our CDK constructs across our apps
CMDCT-5014
---
---
---
---
> Sync our CDK constructs across our apps

- services/ui-src/index.html
Tealium tracking hasn't been working as expected. This PR updates the Tealium path following documentation [here](https://confluence.cms.gov/spaces/BLSTANALYT/pages/432352891/Tealium+Implementation+Documentation+for+Single-Page+Applications). Once we've confirmed with BlastX that they are seeing the expected analytics data in Adobe then we can move forward with making the same changes across all apps.
CMDCT-5090
---
We won't be able to test this until it gets merged in and we either give BlastX credentials to test on their own, or arrange a call with them to test.
---
---
--- …
> cmdct-5090 - update to tealium path

- deployment/stacks/ui.ts
We also need to whitelist https://dap.digitalgov.gov (the GSA Digital Analytics Program script that is injected to the OC domains/subdomains through Tealium)
CMDCT-5090
---
---
---
---
> white list dap.digitalgov.gov

- deployment/stacks/ui.ts
Update to add `https://dap.digitalgov.gov/Federated.js.map`
CMDCT-5090
---
---
---
---
> update url in two places

- tests/cypress/e2e/footer.cy.js
Looks like an external link is causing our tests to fail! This PR removes that check based on the discussions [here](https://coforma.slack.com/archives/C070F87BQG0/p1758834319141849), and [here](https://coforma.slack.com/archives/C03GZ934P17/p1758821247345209). Tests should pass now!
The git action be passing
---
> Remove Footer E2E Test's External Link

- deployment/deployment-config.ts
Trims down on isDev branch names since the branch names have been standardized.
CMDCT-5242
---
NA
NA
---
---
---
> CMDCT-5242 trimming down isDev branch names
